# ML editor configuration file - AUTO GENERATED
# DO NOT EDIT THIS FILE WITH "ML", USE ANOTHER EDITOR (BECAUSE ML WILL OVERWRITE YOUR CHANGES)

# find & file history
set editor(find_history) {}
set editor(replace_history) {}
set editor(file_history) {}

# fonts for each file type
# to specify/change the font for a specific file type insert a line as follows;
# set editor(font,extension) {FontName FontSize}
set editor(font) {Verdana 9}

# default extension (you'll need to edit the file manually to change the default extension)
set editor(default_ext) tcl

# syntax highlight for different file types
# set syntax(.extension,command) 1

# display toolbar
set editor(toolbar) 1

# word wrap
set editor(wordwrap) 0
