# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded simulation_generation 1.0.0 [list source [file join $dir sim_gen.tcl]]
package ifneeded symbol_generation 1.0.0 [list source [file join $dir gensym.tcl]]
package ifneeded tbtemplate_generation 1.0.0 [list source [file join $dir gen_tbtemplate.tcl]]
package ifneeded tbdeclaration_generation 1.0.0 [list source [file join $dir gen_tbdeclaration.tcl]]
package ifneeded ImportUsrDesign_Syn_Gen 1.0.0 [list source [file join $dir sbp_syn_gen.tcl]]
