#! /bin/bash


printrules () {
    /bin/echo "#lattice" >> $rulespath/10-local.rules 
    /bin/echo "BUS==\"usb\",ACTION==\"add\",SYSFS{idVendor}==\"1134\",SYSFS{idProduct}==\"8001\",MODE==\"0660\",OWNER==\"root\",SYMLINK+=\"lattice-%n\"" >> $rulespath/10-local.rules
    /bin/echo "#FTDI" >> $rulespath/10-local.rules 
    /bin/echo "BUS==\"usb\",ACTION==\"add\",SYSFS{idVendor}==\"0403\",SYSFS{idProduct}==\"6010\",MODE==\"0660\",OWNER==\"root\",SYMLINK+=\"ftdi-%n\"" >> $rulespath/10-local.rules
    /bin/echo "BUS==\"usb\",DRIVER==\"ftdi_sio\",SYSFS{bInterfaceNumber}==\"00\",RUN+=\"/bin/sh -c 'basename `dirname %p` >/sys/bus/usb/drivers/ftdi_sio/unbind'\"" >>$rulespath/10-local.rules
}

printperms () {
    /bin/echo "<lattice>=/dev/lattice*" >> $permspath/lattice.perms 
    /bin/echo "<console>0660 <lattice>0660 root"  >> $permspath/lattice.perms
    /bin/echo "<ftdi>=/dev/ftdi*" >> $permspath/lattice.perms 
    /bin/echo "<console>0660 <ftdi>0660 root"  >> $permspath/lattice.perms
}

rulespath=/etc/udev/rules.d
permspath=/etc/security/console.perms.d
if [ -e $rulespath/10-local.rules ]; then
    /bin/echo "File 10-local.rules already exists, write over file? (y/n)"
    read ans
    case "$ans" in
    y)
        /bin/cp -f $rulespath/10-local.rules $rulespath/10-local.bak
        /bin/rm -f $rulespath/10-local.rules
        /bin/touch  $rulespath/10-local.rules
        /bin/chmod 755 $rulespath/10-local.rules
        printrules
        ;;
        n)
            /bin/echo "Setup unsuccessful"
            exit
            ;;
        *)
            /bin/echo $"Usage: $0 foo"
            exit 1
    esac
else
    /bin/touch  $rulespath/10-local.rules
    /bin/chmod 755 $rulespath/10-local.rules
    printrules
fi

if [ -e $permspath/lattice.perms ]; then
    /bin/echo "File lattice.perms already exists, write over file? (y/n)"
    read ans
    case "$ans" in
        y)
            /bin/cp -f $permspath/lattice.perms $permspath/lattice.bak
            /bin/rm -f $permspath/lattice.perms
            /bin/touch  $permspath/lattice.perms
            /bin/chmod 755 $permspath/lattice.perms
            printperms
            ;;
        n)
            /bin/echo "Setup unsuccessful"
            exit
            ;;
    esac
else
    /bin/touch $permspath/lattice.perms
    /bin/chmod 755 $permspath/lattice.perms
    printperms
fi
/usr/bin/skill -HUP udevd
/bin/echo "Setup successful"

                        
                        
