var pairs =
{
"path":{"attributes":1,"selected":1,"elements":1,"line":1,"preference":1,"block":1,"maxdelay":1}
,"attributes":{"dialog":1,"open":1}
,"dialog":{"box":1,"adding":1}
,"box":{"path":1,"feature":1,"cancel":1,"apply":1,"help":1}
,"selected":{"clicking":1,"path":1,"indicates":1}
,"clicking":{"attribute":1}
,"attribute":{"button":1}
,"button":{"actions":1,"applies":1,"ignores":1}
,"actions":{"panel":1}
,"panel":{"choosing":1}
,"choosing":{"design":1}
,"design":{"attributes":1,"closes":1,"allowing":1}
,"open":{"dialog":1}
,"feature":{"description":1}
,"description":{"name":1}
,"name":{"name":1,"selected":1}
,"elements":{"indicates":1}
,"indicates":{"names":1,"block":1}
,"names":{"components":1}
,"components":{"nets":1}
,"nets":{"included":1}
,"included":{"path":1}
,"line":{"text":1}
,"text":{"field":1}
,"field":{"holds":1}
,"holds":{"characters":1}
,"characters":{"block":1}
,"block":{"selected":1,"path":1}
,"preference":{"applied":1,"blocks":1,"button":1}
,"applied":{"path":1}
,"blocks":{"timing":1}
,"timing":{"analysis":1}
,"analysis":{"path":1}
,"maxdelay":{"specifies":1,"preference":1}
,"specifies":{"maximum":1}
,"maximum":{"delay":1}
,"delay":{"path":1}
,"applies":{"given":1}
,"given":{"options":1}
,"options":{"current":1,"may":1,"commands":1}
,"current":{"design":1}
,"closes":{"dialog":1}
,"cancel":{"button":1}
,"ignores":{"options":1}
,"may":{"specified":1}
,"specified":{"closes":1}
,"apply":{"button":1}
,"allowing":{"perform":1}
,"perform":{"options":1}
,"commands":{"leaving":1}
,"leaving":{"dialog":1}
,"help":{"opens":1,"topic":1}
,"opens":{"online":1}
,"online":{"help":1}
,"topic":{"dialog":1}
,"adding":{"deleting":1}
,"deleting":{"paths":1}
}
;Search.control.loadWordPairs(pairs);
