var pairs =
{
"operating":{"macro":1}
,"macro":{"components":1,"instance":1,"macro":1,"instantiated":1,"whole":1,"completely":1,"definition":1,"library":1,"nets":1}
,"components":{"nets":1,"within":1,"placed":1,"pre-placed":1,"cannot":1}
,"nets":{"design":1,"macro":1,"predefined":1,"pins":1,"pre-routed":1,"routed":1,"external":1}
,"design":{"mode":1}
,"mode":{"normally":1}
,"normally":{"place":1}
,"place":{"route":1}
,"route":{"unplace":1,"individual":1}
,"unplace":{"unroute":1}
,"unroute":{"macro":1}
,"instance":{"whole":1,"cannot":1,"except":1,"components":1,"internal":1,"macro":1}
,"whole":{"object":1,"however":1}
,"object":{"instead":1}
,"instead":{"performing":1}
,"performing":{"operations":1}
,"operations":{"individual":1,"always":1}
,"individual":{"components":1}
,"instantiated":{"library":1}
,"library":{"file":1}
,"file":{"completely":1,"cannot":1}
,"completely":{"placed":1}
,"placed":{"routed":1,"macro":1,"unplaced":1}
,"routed":{"(often":1,"place":1,"macro":1,"unrouted":1}
,"(often":{"referred":1}
,"referred":{"hard":1}
,"hard":{"macro)":1}
,"macro)":{"operations":1}
,"always":{"performed":1}
,"performed":{"macro":1}
,"however":{"possible":1}
,"possible":{"define":1}
,"define":{"macro":1}
,"predefined":{"placement":1}
,"placement":{"routing":1}
,"routing":{"information":1}
,"information":{"rules":1}
,"rules":{"govern":1}
,"govern":{"macro\u0027s":1}
,"macro\u0027s":{"internal":1}
,"internal":{"components":1,"nets":1}
,"pins":{"components":1,"cannot":1,"macro":1,"connected":1}
,"within":{"macro":1}
,"cannot":{"added":1,"manually":1,"deleted":1,"used":1}
,"added":{"deleted":1,"pins":1}
,"deleted":{"reconfigured":1,"added":1,"internal":1}
,"reconfigured":{"renamed":1}
,"renamed":{"pre-placed":1}
,"pre-placed":{"components":1,"placed":1}
,"definition":{"cannot":1}
,"manually":{"automatically":1}
,"automatically":{"placed":1,"routed":1}
,"unplaced":{"swapped":1}
,"swapped":{"macro":1}
,"except":{"placing":1}
,"placing":{"unplacing":1}
,"unplacing":{"swapping":1}
,"swapping":{"entire":1}
,"entire":{"macro":1}
,"pre-routed":{"nets":1,"routed":1}
,"unrouted":{"macro":1,"unused":1}
,"unused":{"pins":1}
,"used":{"create":1}
,"create":{"non-macro":1}
,"non-macro":{"nets":1}
,"external":{"pins":1,"nets":1}
,"connected":{"external":1}
}
;Search.control.loadWordPairs(pairs);
