var pairs =
{
"macro":{"drc":1,"mode":1,"editing":1,"library":1}
,"drc":{"checks":1,"check":1,"drc":1,"click":1,"button":1,"along":1,"tests":1,"results":1}
,"checks":{"macro":1,"test":1}
,"mode":{"number":1}
,"number":{"physical":1}
,"physical":{"drc":1}
,"test":{"macro":1}
,"editing":{"execute":1,"area":1}
,"execute":{"tests":1}
,"tests":{"during":1,"run":1,"drc":1}
,"during":{"epic":1}
,"epic":{"session":1,"runs":1}
,"session":{"tests":1}
,"run":{"automatically":1,"macro":1}
,"automatically":{"whenever":1}
,"whenever":{"save":1}
,"save":{"macro":1}
,"library":{"file":1}
,"file":{"run":1}
,"check":{"sure":1}
,"sure":{"nothing":1}
,"nothing":{"selected":1}
,"selected":{"editing":1}
,"area":{"objects":1}
,"objects":{"dialog":1}
,"dialog":{"box":1}
,"box":{"choose":1}
,"choose":{"design":1}
,"design":{"drc":1}
,"click":{"drc":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"epic":1}
,"runs":{"macro":1}
,"along":{"drc":1}
,"results":{"displayed":1}
,"displayed":{"tcl":1}
,"tcl":{"console":1}
}
;Search.control.loadWordPairs(pairs);
