var pairs =
{
"moving":{"components":1}
,"components":{"order":1}
,"order":{"component":1}
,"component":{"moved":1,"site":1,"vacant":1,"want":1,"choose":1}
,"moved":{"placed":1,"vacant":1,"unused":1}
,"placed":{"component":1}
,"vacant":{"site":1}
,"site":{"component":1,"block":1,"select":1,"wish":1,"routed":1}
,"block":{"type":1}
,"type":{"move":1}
,"move":{"component":1,"holding":1}
,"select":{"component":1,"vacant":1}
,"want":{"move":1}
,"holding":{"ctrl":1}
,"ctrl":{"key":1}
,"key":{"select":1}
,"wish":{"move":1}
,"choose":{"edit":1}
,"edit":{"swap":1}
,"swap":{"click":1,"button":1}
,"click":{"swap":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"component":1}
,"unused":{"site":1}
}
;Search.control.loadWordPairs(pairs);
