var pairs =
{
"adding":{"deleting":1,"nets":1,"component":1}
,"deleting":{"nets":1,"objects":1}
,"nets":{"epic":1,"design":1,"adding":1,"selected":1,"add":1,"name":1,"named":1,"delete":1,"editing":1,"sure":1,"eliminated":1}
,"epic":{"enables":1}
,"enables":{"add":1}
,"add":{"nets":1,"component":1,"net":1,"button":1,"selected":1}
,"design":{"macro":1,"database":1,"select":1}
,"macro":{"add":1}
,"component":{"pins":1,"selected":1}
,"pins":{"existing":1,"placed":1,"belong":1,"included":1,"joined":1,"net":1,"adding":1}
,"existing":{"net":1}
,"net":{"delete":1,"design":1,"click":1,"confirmation":1,"shown":1,"$signal_4":1,"routed":1,"$signal_0":1,"net":1,"pins":1,"unrouted":1,"pin":1,"itself":1,"object":1,"want":1,"editing":1}
,"delete":{"nets":1,"net":1,"multiple":1,"alternatively":1,"select":1,"button":1}
,"database":{"adding":1,"finally":1,"delete":1}
,"selected":{"pins":1}
,"placed":{"component":1}
,"belong":{"nets":1}
,"select":{"component":1,"nets":1,"multiple":1,"pin":1}
,"included":{"new":1}
,"new":{"net":1}
,"click":{"add":1,"combination":1,"delete":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"choose":1}
,"choose":{"edit":1}
,"edit":{"add":1,"delete":1}
,"joined":{"net":1}
,"confirmation":{"along":1}
,"along":{"name":1}
,"name":{"new":1,"assigned":1,"net":1,"appears":1}
,"shown":{"tcl":1}
,"tcl":{"console":1}
,"console":{"example":1,"click":1}
,"example":{"net":1}
,"$signal_4":{"new":1}
,"routed":{"completely":1}
,"completely":{"possible":1}
,"possible":{"add":1}
,"assigned":{"first":1}
,"first":{"new":1}
,"$signal_0":{"subsequently":1}
,"subsequently":{"added":1}
,"added":{"nets":1}
,"named":{"$signal_1":1}
,"$signal_1":{"$signal_2":1}
,"$signal_2":{"deleting":1}
,"unrouted":{"net":1}
,"pin":{"removed":1,"ratsnest":1}
,"removed":{"design":1,"database":1}
,"finally":{"net":1}
,"itself":{"removed":1}
,"multiple":{"nets":1}
,"object":{"menu":1}
,"menu":{"select":1}
,"alternatively":{"select":1}
,"editing":{"area":1}
,"area":{"main":1,"signal":1}
,"main":{"view":1}
,"view":{"ctrl":1}
,"ctrl":{"click":1}
,"combination":{"select":1}
,"sure":{"name":1}
,"want":{"delete":1}
,"ratsnest":{"line":1}
,"line":{"route":1}
,"route":{"desired":1}
,"desired":{"net":1}
,"signal":{"name":1}
,"appears":{"tcl":1}
,"eliminated":{"database":1}
}
;Search.control.loadWordPairs(pairs);
