var pairs =
{
"saving":{"design":1,"copy":1}
,"design":{"files":1,"macro":1,"(.ncd)":1,"using":1,"file":1,"preferences":1}
,"files":{"time":1}
,"time":{"during":1}
,"during":{"epic":1}
,"epic":{"session":1}
,"session":{"save":1}
,"save":{"design":1,"physical":1,"changes":1,"save":1,"press":1,"macro":1}
,"macro":{"working":1,"(.nmc)":1,"choose":1,"using":1,"dialog":1,"different":1,"library":1,"type":1,"open":1,"mode":1}
,"working":{"save":1,"directory":1}
,"physical":{"design":1}
,"(.ncd)":{"file":1}
,"file":{"macro":1,"save":1,"text":1,"you\u2019re":1,"enter":1,"name":1,"saved":1,"choose":1,"click":1,"preference":1,"generated":1}
,"(.nmc)":{"file":1}
,"changes":{"design":1}
,"choose":{"file":1}
,"using":{"different":1}
,"different":{"name":1,"directory":1,"location":1}
,"name":{"location":1,".ncd":1,"necessary":1,".nmc":1}
,"location":{"choose":1,"desired":1,"click":1}
,"press":{"ctrl":1}
,"ctrl":{"shift":1}
,"shift":{"design":1}
,"text":{"box":1}
,"box":{"type":1}
,"type":{"new":1,"name":1}
,"new":{"name":1}
,".ncd":{"file":1}
,"you\u2019re":{"saving":1}
,"copy":{"current":1}
,"current":{"location":1,"working":1}
,"desired":{"click":1}
,"click":{"browse":1,"save":1,"able":1}
,"browse":{"button":1}
,"button":{"navigate":1,"save":1}
,"navigate":{"different":1}
,"directory":{".ncd":1,"click":1}
,"enter":{"preference":1,"full":1}
,"preference":{"file":1}
,"necessary":{"full":1}
,"full":{"path":1}
,"path":{"enter":1,"file":1}
,"saved":{"current":1}
,"dialog":{"box":1}
,".nmc":{"file":1}
,"library":{"file":1}
,"able":{"macro":1}
,"open":{"assign":1}
,"assign":{"external":1}
,"external":{"pins":1}
,"pins":{"adding":1,"macro":1}
,"adding":{"external":1}
,"mode":{"preferences":1}
,"preferences":{"retained":1,"defined":1}
,"retained":{"save":1}
,"generated":{"even":1}
,"even":{"design":1}
}
;Search.control.loadWordPairs(pairs);
