var pairs =
{
"external":{"pins":1,"macro":1,"pin":1}
,"pins":{"design":1,"treated":1,"macro":1}
,"design":{"mode":1,"means":1,"nets":1}
,"mode":{"design":1,"external":1,"cannot":1,"macro":1,"change":1}
,"macro":{"pins":1,"route":1,"mode":1}
,"treated":{"pins":1}
,"means":{"add":1}
,"add":{"nets":1,"delete":1}
,"nets":{"design":1,"external":1}
,"route":{"unroute":1}
,"unroute":{"find":1}
,"find":{"find":1,"command":1}
,"command":{"differences":1}
,"differences":{"external":1}
,"cannot":{"add":1,"change":1}
,"delete":{"external":1}
,"change":{"external":1,"pin\u0027s":1}
,"pin":{"name":1}
,"name":{"design":1}
,"pin\u0027s":{"name":1}
}
;Search.control.loadWordPairs(pairs);
