var pairs =
{
"bus":{"attributes":1,"selected":1,"feature":1,"elements":1,"lock":1,"applies":1,"preference":1,"prevents":1,"nets":1,"paths":1,"longline":1,"route":1,"along":1,"default":1,"maxdelay":1,"maxskew":1,"sets":1,"button":1}
,"attributes":{"dialog":1,"open":1}
,"dialog":{"box":1,"adding":1}
,"box":{"bus":1,"allows":1,"cancel":1,"apply":1,"help":1}
,"selected":{"clicking":1,"bus":1,"options":1}
,"clicking":{"attribute":1}
,"attribute":{"button":1}
,"button":{"actions":1,"applies":1,"ignores":1}
,"actions":{"panel":1}
,"panel":{"choosing":1}
,"choosing":{"design":1}
,"design":{"attributes":1,"closes":1,"without":1}
,"open":{"dialog":1}
,"allows":{"modify":1}
,"modify":{"settings":1}
,"settings":{"preferences":1}
,"preferences":{"selected":1}
,"feature":{"description":1}
,"description":{"name":1}
,"name":{"name":1,"bus":1}
,"elements":{"names":1}
,"names":{"components":1}
,"components":{"nets":1}
,"nets":{"included":1,"bus":1,"defined":1}
,"included":{"bus":1}
,"lock":{"bus":1}
,"applies":{"lock":1,"block":1,"longline":1,"prioritize":1,"maxdelay":1,"maxskew":1,"given":1,"selected":1}
,"preference":{"bus":1,"prevents":1,"assigns":1,"specifies":1}
,"prevents":{"unrouted":1,"timing":1}
,"unrouted":{"moved":1}
,"moved":{"deleted":1}
,"deleted":{"block":1}
,"block":{"applies":1,"bus":1}
,"timing":{"analysis":1}
,"analysis":{"selected":1}
,"paths":{"nets":1}
,"defined":{"bus":1}
,"longline":{"applies":1,"preference":1}
,"route":{"net":1}
,"net":{"bus":1}
,"along":{"long":1}
,"long":{"line":1}
,"line":{"prioritize":1}
,"prioritize":{"applies":1,"bus":1}
,"assigns":{"weighted":1}
,"weighted":{"importance":1}
,"importance":{"(0-100)":1}
,"(0-100)":{"bus":1}
,"default":{"priority":1}
,"priority":{"less":1}
,"less":{"considered":1}
,"considered":{"critical":1}
,"critical":{"maxdelay":1}
,"maxdelay":{"applies":1,"preference":1}
,"specifies":{"maximum":1}
,"maximum":{"total":1,"signal":1,"clock":1}
,"total":{"delay":1}
,"delay":{"driver-to-load":1}
,"driver-to-load":{"connections":1}
,"connections":{"nets":1}
,"maxskew":{"applies":1,"preference":1}
,"signal":{"skew":1,"applied":1}
,"skew":{"driver":1,"nets":1}
,"driver":{"driver\u2019s":1}
,"driver\u2019s":{"loads":1}
,"loads":{"specified":1}
,"specified":{"clock":1,"closes":1}
,"clock":{"signal":1,"skew":1}
,"applied":{"bus":1}
,"sets":{"maximum":1}
,"given":{"options":1}
,"options":{"current":1,"may":1}
,"current":{"design":1}
,"closes":{"dialog":1}
,"cancel":{"button":1}
,"ignores":{"options":1}
,"may":{"specified":1}
,"apply":{"button":1}
,"without":{"closing":1}
,"closing":{"dialog":1}
,"help":{"opens":1,"topic":1}
,"opens":{"online":1}
,"online":{"help":1}
,"topic":{"dialog":1}
,"adding":{"deleting":1}
,"deleting":{"buses":1}
}
;Search.control.loadWordPairs(pairs);
