var pairs =
{
"placing":{"unplacing":1,"unplaced":1}
,"unplacing":{"macros":1,"macro":1,"unplace":1}
,"macros":{"design":1,"placed":1,"system":1,"unplacing":1,"autoplace":1,"automatically":1,"epic":1,"select":1,"current":1,"list":1,"viewed":1,"cannot":1,"object":1,"want":1}
,"design":{"mode":1,"manual":1,"place":1}
,"mode":{"editing":1}
,"editing":{"area":1}
,"area":{"main":1,"adds":1,"macro":1,"place":1}
,"main":{"view":1}
,"view":{"macros":1}
,"placed":{"automatically":1,"macro":1,"separate":1,"vacant":1,"macro\u0027s":1,"non-prerouted":1,"manually":1,"selected":1,"sites":1,"macros":1}
,"automatically":{"manually":1,"autoplace":1,"place":1,"placed":1,"routed":1}
,"manually":{"automatic":1,"place":1,"placing":1}
,"automatic":{"placement":1}
,"placement":{"(autoplace":1,"select":1,"two":1,"procedures":1}
,"(autoplace":{"all)":1}
,"all)":{"system":1}
,"system":{"selects":1,"tries":1}
,"selects":{"appropriate":1}
,"appropriate":{"sites":1}
,"sites":{"remaining":1,"editing":1,"relative":1,"puts":1}
,"remaining":{"unplaced":1}
,"unplaced":{"components":1,"macros":1,"macro":1,"unplace":1}
,"components":{"macros":1,"components":1,"placed":1,"macro\u0027s":1,"whether":1,"(i.e":1,"pre-placed":1}
,"manual":{"placement":1,"place":1}
,"select":{"macro":1,"unplaced":1,"vacant":1,"placed":1}
,"macro":{"site":1,"place":1,"library":1,"components":1,"unroutes":1,"editing":1,"list":1,"connections":1,"placed":1,"nets":1,"manual":1,"vacant":1,"objects":1,"want":1,"software":1,"note":1}
,"site":{"place":1,"moving":1,"placed":1,"editing":1,"type":1,"macro\u0027s":1}
,"place":{"macro\u2019s":1,"macro":1,"pre-placed":1,"macros":1,"autoplace":1,"unplaced":1,"macro\u0027s":1,"manual":1,"enter":1,"epic":1,"unplace":1}
,"macro\u2019s":{"reference":1}
,"reference":{"component":1}
,"component":{"manually":1,"note":1,"selected":1,"i\u002Fo":1,"logic":1,"placed":1,"macro":1}
,"pre-placed":{"components":1,"unplace":1,"placed":1}
,"library":{"file":1,"file)":1}
,"file":{"unplaced":1,"placed":1,"routed":1}
,"macro\u0027s":{"library":1,"external":1,"reference":1,"pre-placed":1}
,"separate":{"operation":1}
,"operation":{"autoplace":1,"connections":1}
,"autoplace":{"components":1,"place":1,"command":1,"unplaced":1}
,"tries":{"place":1}
,"whether":{"pre-placed":1}
,"unplace":{"macros":1,"select":1,"command":1,"selected":1,"choose":1,"epic":1}
,"unroutes":{"macro\u0027s":1,"external":1}
,"external":{"pins":1,"pin":1}
,"pins":{"removes":1,"routed":1}
,"removes":{"macro":1,"selected":1}
,"adds":{"macro":1}
,"list":{"design\u0027s":1,"list":1,"unplaced":1}
,"design\u0027s":{"unplaced":1}
,"command":{"automatically":1,"line":1,"removes":1}
,"epic":{"choose":1,"command":1,"tcl":1}
,"choose":{"place":1,"design":1}
,"vacant":{"sites":1,"site":1}
,"connections":{"routed":1}
,"routed":{"macro\u0027s":1,"macro":1,"manual":1,"unplacing":1}
,"non-prerouted":{"macro":1}
,"nets":{"automatically":1,"pre-routed":1}
,"two":{"macro":1,"steps":1}
,"procedures":{"manually":1}
,"moving":{"macro":1}
,"objects":{"menu":1}
,"menu":{"select":1,"unplacing":1}
,"want":{"unplace":1}
,"note":{"macro\u0027s":1,"preceding":1,"locked":1}
,"selected":{"site":1,"macros":1}
,"type":{"block":1}
,"block":{"i\u002Fo":1}
,"i\u002Fo":{"component":1}
,"logic":{"component":1}
,"preceding":{"two":1}
,"steps":{"may":1}
,"may":{"performed":1}
,"performed":{"reverse":1}
,"reverse":{"order":1}
,"order":{"choose":1}
,"enter":{"place":1}
,"line":{"dialog":1}
,"dialog":{"box":1}
,"box":{"macro\u0027s":1}
,"(i.e":{"components":1}
,"file)":{"placed":1}
,"relative":{"reference":1}
,"pre-routed":{"automatically":1}
,"current":{"sites":1}
,"puts":{"unplaced":1}
,"viewed":{"objects":1}
,"software":{"unroutes":1}
,"pin":{"macro":1}
,"locked":{"macros":1}
,"cannot":{"unplaced":1}
,"object":{"menu":1}
,"tcl":{"commands":1}
}
;Search.control.loadWordPairs(pairs);
