var pairs =
{
"defining":{"reference":1}
,"reference":{"components":1,"component":1}
,"components":{"(macro":1}
,"(macro":{"mode)":1}
,"mode)":{"define":1}
,"define":{"reference":1}
,"component":{"select":1,"wish":1,"choose":1,"reference":1,"selected":1,"note":1,"time":1,"component":1,"lower":1,"macro":1}
,"select":{"component":1}
,"wish":{"reference":1}
,"choose":{"design":1}
,"design":{"macro":1}
,"macro":{"refcomp":1,"mode":1,"file":1,"terminology":1}
,"refcomp":{"indicate":1}
,"indicate":{"selected":1}
,"selected":{"component":1,"reference":1}
,"note":{"change":1}
,"change":{"reference":1}
,"time":{"epic":1}
,"epic":{"macro":1}
,"mode":{"designate":1}
,"designate":{"reference":1}
,"lower":{"left":1}
,"left":{"corner":1}
,"corner":{"selected":1}
,"file":{"saved":1}
,"saved":{"macro":1}
}
;Search.control.loadWordPairs(pairs);
