var pairs =
{
"unbinding":{"macros":1,"components":1}
,"macros":{"design":1,"included":1}
,"design":{"mode":1}
,"mode":{"unbind":1}
,"unbind":{"macro":1,"choose":1,"selected":1}
,"macro":{"disassociate":1,"macro":1,"name":1,"treated":1,"objects":1,"names":1,"list":1}
,"disassociate":{"macro\u0027s":1}
,"macro\u0027s":{"components":1,"library":1}
,"components":{"nets":1}
,"nets":{"macro":1,"formerly":1,"component":1,"longer":1}
,"name":{"disappears":1}
,"disappears":{"design\u0027s":1,"objects":1}
,"design\u0027s":{"database":1}
,"database":{"unbinding":1}
,"formerly":{"macro":1}
,"treated":{"separate":1}
,"separate":{"components":1}
,"component":{"names":1}
,"names":{"net":1,"changed":1,"click":1}
,"net":{"names":1}
,"changed":{"replacing":1}
,"replacing":{"forward":1}
,"forward":{"slash":1}
,"slash":{"(\u002F)":1}
,"(\u002F)":{"indicates":1}
,"indicates":{"macro\u0027s":1}
,"library":{"file":1}
,"file":{"underscore":1}
,"underscore":{"(_)":1}
,"(_)":{"unbind":1}
,"objects":{"dialog":1}
,"dialog":{"box":1}
,"box":{"display":1}
,"display":{"list":1}
,"list":{"macro":1,"items":1}
,"click":{"macro":1}
,"items":{"unbind":1}
,"choose":{"edit":1}
,"edit":{"unbind":1}
,"selected":{"macros":1}
,"included":{"components":1}
,"longer":{"associated":1}
,"associated":{"macro":1}
}
;Search.control.loadWordPairs(pairs);
