var pairs =
{
"renaming":{"objects":1,"object":1}
,"objects":{"renaming":1}
,"object":{"permanently":1,"select":1,"want":1,"menu":1,"highlighted":1,"choose":1,"click":1,"renamed":1}
,"permanently":{"changes":1}
,"changes":{"name":1}
,"name":{"design":1,"object":1,"appears":1}
,"design":{"database":1}
,"database":{"rename":1}
,"rename":{"components":1,"object":1,"either":1,"pop-up":1,"dialog":1}
,"components":{"nets":1}
,"nets":{"macros":1}
,"macros":{"paths":1}
,"paths":{"buses":1}
,"buses":{"rename":1}
,"select":{"object":1}
,"want":{"rename":1}
,"either":{"object":1}
,"menu":{"editing":1,"rename":1}
,"editing":{"area":1}
,"area":{"main":1,"editing":1}
,"main":{"view":1}
,"view":{"object":1,"right-click":1}
,"highlighted":{"editing":1}
,"right-click":{"selected":1}
,"selected":{"object":1}
,"choose":{"rename":1}
,"pop-up":{"menu":1}
,"dialog":{"box":1}
,"box":{"type":1}
,"type":{"new":1}
,"new":{"name":1}
,"click":{"tcl":1}
,"tcl":{"console":1}
,"console":{"shows":1}
,"shows":{"object":1}
,"renamed":{"object\u2019s":1}
,"object\u2019s":{"new":1}
,"appears":{"object":1}
}
;Search.control.loadWordPairs(pairs);
