var pairs =
{
"pin":{"types":1,"type":1,"defined":1,"specifies":1,"input":1,"used":1,"output":1,"synchronous":1,"treated":1,"pin":1,"internal":1}
,"types":{"pin":1,"listed":1}
,"type":{"determines":1,"input":1,"specified":1}
,"determines":{"paths":1}
,"paths":{"passing":1}
,"passing":{"pin":1}
,"defined":{"timing":1}
,"timing":{"analysis":1}
,"analysis":{"pin":1}
,"listed":{"following":1}
,"following":{"table":1}
,"table":{"pin":1}
,"input":{"\u002Foutput":1,"input":1,"pin":1,"combinational":1,"clocked":1}
,"\u002Foutput":{"description":1}
,"description":{"input":1}
,"specifies":{"pin":1}
,"combinational":{"logic":1}
,"logic":{"macro":1,"within":1}
,"macro":{"clocked":1,"srdirect":1,"enable":1,"(for":1,"setdirect":1,"rstdirect":1,"select":1,"output":1,"syncoutput":1,"pin":1,"clock":1}
,"clocked":{"clock":1,"within":1,"logic":1}
,"clock":{"input":1,"signal":1,"within":1,"directin":1}
,"used":{"clock":1,"asynchronous":1,"control":1,"select":1}
,"signal":{"within":1,"multiplexer":1}
,"within":{"macro":1}
,"srdirect":{"input":1}
,"asynchronous":{"reset":1,"control":1,"signal":1}
,"reset":{"signal":1}
,"enable":{"input":1}
,"control":{"line":1}
,"line":{"syncinput":1,"synchronous":1}
,"syncinput":{"input":1}
,"(for":{"example":1}
,"example":{"register":1}
,"register":{"input)":1}
,"input)":{"syncenable":1}
,"syncenable":{"input":1}
,"synchronous":{"clock":1,"respect":1}
,"setdirect":{"input":1}
,"rstdirect":{"input":1}
,"select":{"input":1,"signal":1}
,"multiplexer":{"within":1}
,"output":{"output":1,"pin":1,"combinational":1,"clocked":1}
,"syncoutput":{"output":1}
,"respect":{"macro":1}
,"directin":{"output":1}
,"treated":{"direct":1}
,"direct":{"input":1}
,"internal":{"delay":1}
,"delay":{"pin":1}
,"specified":{"external":1}
,"external":{"macro":1}
}
;Search.control.loadWordPairs(pairs);
