var pairs =
{
"reading":{"physical":1}
,"physical":{"macro":1,"macro\u0027s":1,"macro)":1}
,"macro":{"file":1,"library":1,"filename":1,"schematic":1,"following":1,".ngo":1,"appears":1}
,"file":{"design":1,"contain":1,"macro":1,".nmc":1,"include":1,"unexpanded":1,"resolves":1,"produced":1,"ngdbuild":1,"note":1,"(the":1,"defines":1,"filename.nmc":1}
,"design":{"schematic":1,"process":1,"primitives":1,"relative":1}
,"schematic":{"hardware":1,"reference":1,"hdl":1,"match":1,"symbol":1}
,"hardware":{"description":1}
,"description":{"language":1}
,"language":{"(hdl)":1}
,"(hdl)":{"source":1}
,"source":{"file":1}
,"contain":{"reference":1}
,"reference":{"physical":1,"appears":1}
,"library":{"file":1}
,".nmc":{"extension":1,"macro":1,"name":1,"file":1}
,"extension":{"included":1}
,"included":{"block":1}
,"block":{"design\u0027s":1,"representing":1,"information":1,"instance_name":1}
,"design\u0027s":{"schematic":1}
,"appears":{"file=filename":1,"file":1}
,"file=filename":{"property":1,"file":1}
,"property":{"attached":1}
,"attached":{"block":1}
,"representing":{"physical":1}
,"filename":{"pointing":1}
,"pointing":{".nmc":1}
,"include":{"physical":1}
,"hdl":{"isplever":1}
,"isplever":{"diamond":1}
,"diamond":{"processes":1}
,"processes":{"macro":1}
,"following":{"netlist":1}
,"netlist":{"reader":1}
,"reader":{"passes":1}
,"passes":{"macro":1}
,".ngo":{"file":1}
,"unexpanded":{"block":1}
,"information":{"block\u0027s":1,"becomes":1,"macro":1}
,"block\u0027s":{"internal":1,"input":1}
,"internal":{"logic":1}
,"logic":{"connectivity":1}
,"connectivity":{"transferred":1,"design":1}
,"transferred":{"applicable":1}
,"applicable":{".nmc":1}
,"name":{"build":1,".nmc":1}
,"build":{"database":1}
,"database":{"process":1}
,"process":{"translate":1,"ngdbuild":1}
,"translate":{"design":1}
,"ngdbuild":{"finds":1,"places":1}
,"finds":{"macro":1}
,"resolves":{"macro\u0027s":1}
,"macro\u0027s":{"logic":1,"library":1}
,"primitives":{"information":1}
,"becomes":{"part":1}
,"part":{".ngd":1}
,".ngd":{"file":1,"contains":1}
,"produced":{".ngd":1}
,"contains":{"logical":1}
,"logical":{"representation":1}
,"representation":{"design":1}
,"relative":{"placement":1}
,"placement":{"routing":1}
,"routing":{"information":1}
,"places":{"full":1}
,"full":{"path":1}
,"path":{"name":1}
,"note":{"names":1}
,"names":{"block\u0027s":1,"external":1,"match":1}
,"input":{"output":1}
,"output":{"pins":1}
,"pins":{"schematic":1,"specified":1}
,"match":{"names":1,"error":1}
,"external":{"pins":1}
,"specified":{"physical":1}
,"(the":{".nmc":1}
,"defines":{"physical":1}
,"macro)":{"pin":1}
,"pin":{"names":1,"mismatch":1,"pin_name":1,"found":1}
,"error":{"message":1}
,"message":{"generated":1}
,"generated":{"pin":1}
,"mismatch":{"block":1}
,"instance_name":{"file=filename":1}
,"filename.nmc":{"pin":1}
,"pin_name":{"pin_name":1,"identifies":1}
,"identifies":{"pin":1}
,"found":{"schematic":1}
,"symbol":{".nmc":1}
}
;Search.control.loadWordPairs(pairs);
