var pairs =
{
"main":{"window":1,"view":1}
,"window":{"epic":1,"provides":1,"provided":1}
,"epic":{"main":1,"commands":1,"tcl":1}
,"provides":{"graphical":1}
,"graphical":{"display":1,"layout":1}
,"display":{"fpga":1,"editing":1,"local":1}
,"fpga":{"device":1}
,"device":{"plus":1,"enables":1,"highlights":1,"layout":1}
,"plus":{"tools":1}
,"tools":{"selecting":1}
,"selecting":{"viewing":1,"object":1,"items":1}
,"viewing":{"editing":1,"attributes":1,"info":1}
,"editing":{"objects":1,"area":1}
,"objects":{"descriptions":1,"highlight":1,"adding":1,"displayed":1}
,"descriptions":{"section":1}
,"section":{"main":1}
,"provided":{"below":1}
,"below":{"following":1}
,"following":{"image":1}
,"image":{"editing":1}
,"area":{"editing":1,"large":1,"object":1,"labels":1,"selecting":1,"clicking":1,"enabling":1,"pan":1,"main":1,"layout":1,"display":1}
,"large":{"graphical":1}
,"layout":{"view":1,"hold":1,"zoomed":1,"dragging":1,"default":1}
,"view":{"fpga":1,"world":1,"miniaturized":1,"device":1,"zoom":1,"zooming":1,"layers":1}
,"enables":{"edit":1,"perform":1,"control":1}
,"edit":{"design":1}
,"design":{"shows":1,"sites":1,"allows":1,"rule":1}
,"shows":{"components":1,"object":1,"positioned":1}
,"components":{"interconnections":1,"nets":1}
,"interconnections":{"design":1}
,"sites":{"items":1,"components":1}
,"items":{"select":1,"selected":1,"layers":1}
,"select":{"editing":1,"individual":1}
,"object":{"menu":1,"name":1,"object":1,"returning":1,"definitions":1}
,"menu":{"highlighted":1,"object":1,"lists":1,"magnify":1}
,"highlighted":{"layout":1}
,"hold":{"mouse":1}
,"mouse":{"component":1}
,"component":{"site":1,"graphics":1,"positions":1,"net":1}
,"site":{"net":1}
,"net":{"tool":1,"selected":1}
,"tool":{"tip":1}
,"tip":{"displayed":1}
,"displayed":{"shows":1,"tcl":1,"editing":1}
,"name":{"note":1}
,"note":{"editing":1}
,"labels":{"next":1}
,"next":{"component":1}
,"graphics":{"shifted":1}
,"shifted":{"downward":1}
,"downward":{"relative":1}
,"relative":{"component":1}
,"positions":{"shift":1}
,"shift":{"apparent":1}
,"apparent":{"higher":1}
,"higher":{"magnification":1}
,"magnification":{"object":1}
,"lists":{"category":1,"hyperlink":1}
,"category":{"nets":1}
,"nets":{"comps":1,"ratsnests":1}
,"comps":{"macros":1}
,"macros":{"buses":1}
,"buses":{"paths":1}
,"paths":{"preferences":1}
,"preferences":{"design":1}
,"allows":{"select":1}
,"individual":{"objects":1}
,"highlight":{"editing":1}
,"magnify":{"editing":1}
,"clicking":{"zoom":1}
,"zoom":{"button":1,"toolbar":1}
,"button":{"zoom":1}
,"toolbar":{"actions":1,"zoom":1,"enables":1,"layers":1,"gives":1,"object":1}
,"actions":{"panel":1,"selected":1,"tcl":1,"epic":1}
,"panel":{"actions":1,"enables":1}
,"perform":{"actions":1}
,"selected":{"objects":1,"editing":1,"shows":1,"object":1}
,"adding":{"deleting":1}
,"deleting":{"routing":1}
,"routing":{"unrouting":1}
,"unrouting":{"highlighting":1}
,"highlighting":{"viewing":1}
,"attributes":{"pin":1}
,"pin":{"pair":1,"wires":1}
,"pair":{"delay":1}
,"delay":{"performing":1}
,"performing":{"design":1}
,"rule":{"check":1}
,"check":{"tcl":1}
,"tcl":{"console":1,"command":1,"commands":1}
,"console":{"tab":1,"lists":1,"automatically":1}
,"tab":{"tcl":1,"bottom":1,"viewing":1}
,"bottom":{"keeps":1}
,"keeps":{"track":1}
,"track":{"actions":1}
,"hyperlink":{"component":1}
,"enabling":{"immediately":1}
,"immediately":{"return":1}
,"return":{"previous":1}
,"previous":{"selections":1}
,"selections":{"tcl":1}
,"command":{"prompt":1}
,"prompt":{"enables":1}
,"commands":{"enter":1,"info":1}
,"enter":{"displayed":1}
,"automatically":{"saved":1}
,"saved":{"epic":1}
,"info":{"warning":1}
,"warning":{"error":1}
,"error":{"tab":1,"messages":1}
,"messages":{"world":1}
,"world":{"view":1}
,"miniaturized":{"global":1}
,"global":{"view":1}
,"highlights":{"items":1}
,"positioned":{"within":1}
,"within":{"device":1,"world":1}
,"zoomed":{"location":1}
,"location":{"editing":1}
,"pan":{"across":1}
,"across":{"layout":1}
,"dragging":{"inner":1}
,"inner":{"locater":1}
,"locater":{"box":1}
,"box":{"within":1}
,"control":{"display":1,"types":1}
,"zooming":{"zooming":1,"selected":1,"main":1}
,"returning":{"full":1}
,"full":{"layout":1}
,"layers":{"toolbar":1}
,"gives":{"control":1}
,"types":{"objects":1}
,"default":{"sites":1}
,"ratsnests":{"displayed":1}
,"local":{"wires":1}
,"wires":{"long":1,"pin":1,"switch":1}
,"long":{"wires":1}
,"switch":{"boxes":1}
,"boxes":{"switches":1}
,"switches":{"selecting":1}
}
;Search.control.loadWordPairs(pairs);
