var pairs =
{
"macro":{"attributes":1,"clicking":1,"bring":1,"macro":1,"preferences":1,"name":1,"instance":1,"added":1,"updated":1,"library":1,"files":1,"mode":1,"unplaced":1,"shown":1,"placed":1,"pre-placed":1,"least":1,"terminology":1,"pins":1,"components":1,"locked":1,"cannot":1,"preference":1}
,"attributes":{"dialog":1,"open":1,"explained":1,"feature":1}
,"dialog":{"box":1}
,"box":{"design":1,"adding":1,"macro":1,"allows":1,"hidden":1,"button":1,"cancel":1,"help":1}
,"design":{"mode":1,"attributes":1,"change":1,"(outside":1,"allowing":1,"closes":1,"lock":1}
,"mode":{"selected":1,"status":1}
,"selected":{"macro":1}
,"clicking":{"attribute":1,"show":1}
,"attribute":{"button":1}
,"button":{"actions":1,"replaced":1,"level":1,"applies":1,"ignores":1,"enabled":1,"macro":1}
,"actions":{"panel":1}
,"panel":{"choosing":1}
,"choosing":{"design":1}
,"open":{"dialog":1}
,"adding":{"macro":1,"apply":1}
,"bring":{"dialog":1}
,"allows":{"modify":1}
,"modify":{"settings":1}
,"settings":{"preference":1}
,"preference":{"selected":1,"applied":1,"currently":1,"places":1}
,"explained":{"first":1}
,"first":{"table":1}
,"table":{"macro":1,"preferences":1}
,"preferences":{"options":1,"section":1,"button":1,"displays":1,"applied":1,"feature":1}
,"options":{"listed":1,"current":1,"commands":1,"may":1}
,"listed":{"second":1}
,"second":{"table":1}
,"section":{"dialog":1}
,"hidden":{"default":1}
,"default":{"toggled":1}
,"toggled":{"clicking":1}
,"show":{"preferences":1}
,"replaced":{"corresponding":1}
,"corresponding":{"hide":1}
,"hide":{"preferences":1}
,"level":{"detail":1}
,"detail":{"displayed":1}
,"displayed":{"macro":1}
,"feature":{"description":1}
,"description":{"macro":1,"lock":1}
,"name":{"specifies":1,"macro":1,"name":1,"assigned":1,"names":1,"change":1}
,"specifies":{"name":1}
,"instance":{"enter":1}
,"enter":{"name":1}
,"assigned":{"automatically":1}
,"automatically":{"macro":1,"reflect":1}
,"added":{"design":1}
,"change":{"macro":1}
,"names":{"components":1}
,"components":{"nets":1,"macro":1,"reference":1,"instantiated":1,"design":1,"pre-placed":1,"placed":1,"(that":1,"sites":1}
,"nets":{"external":1}
,"external":{"pins":1}
,"pins":{"part":1,"external":1,"macro":1,"used":1}
,"part":{"macro":1}
,"updated":{"automatically":1}
,"reflect":{"name":1}
,"library":{"file":1,"files":1,"file)":1}
,"file":{"generally":1,"file":1,"containing":1}
,"generally":{"referred":1}
,"referred":{"macros":1}
,"macros":{"physical":1}
,"physical":{"macro":1}
,"files":{"macro":1,".nmc":1}
,"containing":{"definition":1}
,"definition":{"macro":1}
,".nmc":{"extension":1}
,"extension":{"created":1}
,"created":{"edited":1}
,"edited":{"epic":1}
,"epic":{"operating":1}
,"operating":{"macro":1}
,"status":{"indicates":1}
,"indicates":{"whether":1,"component":1,"lock":1,"locate":1,"defined":1}
,"whether":{"macro":1}
,"unplaced":{"placed":1,"unrouted":1,"locate":1}
,"placed":{"macro":1,"components":1,"reference":1,"macro\u0027s":1}
,"shown":{"placed":1}
,"reference":{"comp":1,"component":1}
,"comp":{"indicates":1,"macro)":1,"macro":1}
,"component":{"designated":1,"macro":1,"reference":1,"described":1,"cannot":1,"using":1,"specified":1,"site":1,"locks":1}
,"designated":{"reference":1}
,"pre-placed":{"components":1,"component":1,"(that":1}
,"least":{"pre-placed":1}
,"described":{"macro":1}
,"terminology":{"topic":1}
,"topic":{"field":1,"dialog":1}
,"field":{"holds":1}
,"holds":{"characters":1}
,"characters":{"non-modifiable":1}
,"non-modifiable":{"scrollable":1}
,"scrollable":{"external":1}
,"used":{"connect":1}
,"connect":{"components":1}
,"instantiated":{"macro":1}
,"(outside":{"macro)":1}
,"macro)":{"show":1,"locked":1,".the":1}
,"displays":{"preferences":1}
,"applied":{"type":1,"applicable":1}
,"type":{"object":1}
,"object":{"editing":1,"(i.e":1}
,"editing":{"adding":1}
,"apply":{"button":1}
,"applies":{"given":1,"design":1}
,"given":{"options":1}
,"current":{"design":1}
,"allowing":{"perform":1}
,"perform":{"options":1}
,"commands":{"leaving":1}
,"leaving":{"dialog":1}
,"closes":{"dialog":1}
,"cancel":{"button":1}
,"ignores":{"options":1}
,"may":{"specified":1}
,"specified":{"closes":1,"site":1}
,"help":{"opens":1,"topic":1}
,"opens":{"online":1}
,"online":{"help":1}
,"lock":{"enabled":1,"global":1,"placement":1,"toggle":1,"preference)":1}
,"enabled":{"indicates":1,"cannot":1}
,"global":{"lock":1}
,"placement":{"preference":1}
,"applicable":{"object":1}
,"(i.e":{"site":1,"paths":1}
,"site":{"comp":1,"locks":1,"(see":1,"places":1}
,"locked":{"component":1,"macro":1}
,"cannot":{"unplaced":1,"unlock":1}
,"unrouted":{"moved":1}
,"moved":{"swapped":1}
,"swapped":{"deleted":1}
,"deleted":{"lock":1}
,"currently":{"applies":1}
,"toggle":{"button":1}
,"unlock":{"component":1}
,"using":{"toggle":1}
,"(that":{"components":1}
,"macro\u0027s":{"library":1,"reference":1,"pre-placed":1}
,"file)":{"locked":1,"sites":1}
,"locate":{"enabled":1,"preference":1,"macro":1}
,".the":{"locate":1}
,"places":{"component":1,"macro\u0027s":1}
,"locks":{"component":1,"placed":1}
,"(see":{"lock":1}
,"preference)":{"locate":1}
,"sites":{"relative":1,"paths":1}
,"relative":{"reference":1}
,"paths":{"indicates":1,"(i.e":1,"defined":1}
,"defined":{"paths":1,"define":1}
,"define":{"path":1}
,"path":{"preferences)":1}
,"preferences)":{"include":1}
,"include":{"comp":1}
}
;Search.control.loadWordPairs(pairs);
