var pairs =
{
"signal":{"probing":1,"names":1,"column":1,"status":1,"probe":1,"main":1,"occupying":1}
,"probing":{"configuration":1,"feature":1,"changes":1,"list":1}
,"configuration":{"dialog":1}
,"dialog":{"box":1}
,"box":{"dialog":1,"appears":1,"available":1,"display":1,"cancel":1,"signal":1}
,"appears":{"choose":1}
,"choose":{"design":1}
,"design":{"signal":1,"probed":1,"click":1}
,"feature":{"description":1}
,"description":{"signals":1}
,"signals":{"list":1,"design":1,"beginning":1,"drag":1,"import":1}
,"list":{"list":1,"available":1,"right":1,"original":1,"pair":1,"simple":1,"reuse":1,"clicking":1}
,"available":{"signals":1,"list":1,"column":1,"i\u002Fo":1}
,"probed":{"paired":1,"signals":1}
,"paired":{"receiver":1,"list":1}
,"receiver":{"grid":1}
,"grid":{"cells":1}
,"cells":{"available":1,"paired":1,"populated":1}
,"right":{"wildcard":1}
,"wildcard":{"filter":1,"value":1}
,"filter":{"allows":1,"signal":1}
,"allows":{"filter":1}
,"names":{"using":1}
,"using":{"specific":1}
,"specific":{"name":1}
,"name":{"wildcard":1}
,"value":{"example":1}
,"example":{"typing":1}
,"typing":{"d*and":1}
,"d*and":{"pressing":1}
,"pressing":{"enter":1}
,"enter":{"key":1,"*in":1}
,"key":{"display":1}
,"display":{"signals":1,"changes":1}
,"beginning":{"letter":1}
,"letter":{"restore":1}
,"restore":{"list":1}
,"original":{"state":1}
,"state":{"enter":1}
,"*in":{"text":1}
,"text":{"box":1,"file":1}
,"column":{"available":1,"title":1,"column\u2019s":1,"shows":1}
,"i\u002Fo":{"grid":1,"click":1,"routing":1,"site":1}
,"click":{"column":1}
,"title":{"sort":1}
,"sort":{"rows":1}
,"rows":{"signal":1,"status":1}
,"column\u2019s":{"cells":1}
,"populated":{"signals":1}
,"drag":{"signals":1}
,"pair":{"available":1}
,"status":{"column":1,"signal":1,"refresh":1}
,"shows":{"availability":1}
,"availability":{"i\u002Fo":1}
,"routing":{"status":1}
,"probe":{"pairing":1}
,"pairing":{"click":1}
,"refresh":{"button":1}
,"button":{"refreshes":1,"closes":1,"imports":1,"saves":1,"manually":1}
,"refreshes":{"dialog":1}
,"changes":{"may":1,"made":1}
,"may":{"made":1}
,"made":{"signal":1,"import":1}
,"main":{"view":1}
,"view":{"deleting":1}
,"deleting":{"signal":1}
,"occupying":{"i\u002Fo":1}
,"site":{"dismiss":1}
,"dismiss":{"button":1}
,"closes":{"dialog":1}
,"cancel":{"signal":1}
,"import":{"button":1,"export":1,"again":1}
,"imports":{"signal":1}
,"simple":{"text":1}
,"file":{"lists":1,"regenerated":1,".ncd":1,"import":1}
,"lists":{"probed":1}
,"export":{"buttons":1,"button":1}
,"buttons":{"allow":1}
,"allow":{"save":1}
,"save":{"signal":1}
,"reuse":{".ncd":1,"list":1}
,".ncd":{"file":1}
,"regenerated":{"export":1,"reuse":1}
,"saves":{"current":1}
,"current":{"signal":1}
,"clicking":{"import":1}
,"manually":{"edit":1}
,"edit":{"text":1}
,"again":{"help":1}
,"help":{"opens":1,"topic":1}
,"opens":{"online":1}
,"online":{"help":1}
,"topic":{"dialog":1}
}
;Search.control.loadWordPairs(pairs);
