var pairs =
{
"equations":{"dialog":1,"button":1,"contains":1,"edited":1}
,"dialog":{"box":1}
,"box":{"equations":1,"opens":1,"left":1,"right":1}
,"opens":{"click":1}
,"click":{"equations":1}
,"button":{"logic":1,"applies":1}
,"logic":{"block":1,"equations":1,"program":1}
,"block":{"view":1,"ram":1}
,"view":{"valid":1,"feature":1}
,"valid":{"operators":1}
,"operators":{"*represents":1}
,"*represents":{"logical":1}
,"logical":{"represents":1,"@represents":1,"xor":1,"logic":1}
,"represents":{"logical":1}
,"@represents":{"logical":1}
,"xor":{"represents":1}
,"left":{"element":1}
,"element":{"block":1,"dialog":1}
,"ram":{"element":1}
,"right":{"appear":1}
,"appear":{"clicking":1}
,"clicking":{"properties":1}
,"properties":{"button":1}
,"feature":{"description":1}
,"description":{"equations":1}
,"contains":{"editable":1}
,"editable":{"logic":1,"memory":1}
,"edited":{"using":1}
,"using":{"capital":1}
,"capital":{"letters":1}
,"letters":{"address":1}
,"address":{"contains":1,"information":1}
,"memory":{"location":1,"info":1}
,"location":{"address":1}
,"information":{"memory":1,"button":1}
,"info":{"shows":1}
,"shows":{"uneditable":1}
,"uneditable":{"logic":1}
,"program":{"size":1}
,"size":{"information":1}
,"applies":{"given":1}
,"given":{"options":1}
,"options":{"closes":1}
,"closes":{"dialog":1}
}
;Search.control.loadWordPairs(pairs);
