var pairs =
{
"changing":{"i\u002Fo":1}
,"i\u002Fo":{"types":1,"type":1,"standards":1,"usage":1}
,"types":{"change":1,"select":1}
,"change":{"i\u002Fo":1}
,"type":{"select":1}
,"select":{"pio":1,"option":1,"options":1}
,"pio":{"component":1}
,"component":{"open":1,"logic":1}
,"open":{"logic":1}
,"logic":{"block":1,"logic":1}
,"block":{"view":1}
,"view":{"list":1,"different":1,"toolbar":1}
,"list":{"available":1}
,"available":{"i\u002Fo":1}
,"standards":{"upper-left":1}
,"upper-left":{"section":1}
,"section":{"view":1}
,"different":{"architectures":1,"schematic":1}
,"architectures":{"different":1}
,"schematic":{"layouts":1}
,"layouts":{"change":1}
,"option":{"next":1}
,"next":{"desired":1}
,"desired":{"i\u002Fo":1}
,"options":{"applicable":1}
,"applicable":{"slewrate":1}
,"slewrate":{"pciclamp":1}
,"pciclamp":{"pullmode":1}
,"pullmode":{"drive":1}
,"drive":{"vref":1}
,"vref":{"voltages":1}
,"voltages":{"details":1}
,"details":{"i\u002Fo":1}
,"usage":{"refer":1,"guide":1}
,"refer":{"following":1}
,"following":{"technical":1}
,"technical":{"notes":1}
,"notes":{"latticeecp2\u002Fm":1}
,"latticeecp2\u002Fm":{"sysio":1}
,"sysio":{"usage":1}
,"guide":{"(tn1102)":1,"(tn1177)":1,"(tn1088)":1,"(tn1056)":1,"(tn1091)":1,"(tn1202)":1}
,"(tn1102)":{"latticeecp3":1}
,"latticeecp3":{"sysio":1}
,"(tn1177)":{"purespeed":1}
,"purespeed":{"i\u002Fo":1}
,"(tn1088)":{"latticeecp\u002Fec":1}
,"latticeecp\u002Fec":{"latticexp":1}
,"latticexp":{"sysio":1}
,"(tn1056)":{"machxo":1}
,"machxo":{"sysio":1}
,"(tn1091)":{"machxo2":1}
,"machxo2":{"sysio":1}
,"(tn1202)":{"drc":1}
,"drc":{"check":1,"button":1,"results":1}
,"check":{"making":1}
,"making":{"changes":1}
,"changes":{"click":1}
,"click":{"drc":1}
,"button":{"logic":1}
,"toolbar":{"drc":1}
,"results":{"appear":1}
,"appear":{"tcl":1}
,"tcl":{"console":1}
,"console":{"editing":1}
,"editing":{"component":1}
}
;Search.control.loadWordPairs(pairs);
