var pairs =
{
"concepts":{"definitions":1,"engineering":1}
,"definitions":{"section":1}
,"section":{"includes":1}
,"includes":{"basic":1}
,"basic":{"concepts":1}
,"engineering":{"change":1}
,"change":{"management":1}
,"management":{"epic":1}
,"epic":{"device":1,"explains":1}
,"device":{"editor":1}
,"editor":{"defines":1}
,"defines":{"objects":1}
,"objects":{"technical":1}
,"technical":{"terms":1}
,"terms":{"encounter":1}
,"encounter":{"epic":1}
,"explains":{"physical":1}
,"physical":{"macros":1,"design":1}
,"macros":{"placement":1}
,"placement":{"routing":1}
,"routing":{"physical":1}
,"design":{"rule":1}
,"rule":{"check":1}
,"check":{"trace":1}
,"trace":{"timing":1}
,"timing":{"analysis":1}
}
;Search.control.loadWordPairs(pairs);
