var pairs =
{
"notes":{"adding":1}
,"adding":{"macros":1}
,"macros":{"macro":1,"name":1,"unique":1,"named":1}
,"macro":{"added":1,"format":1,"named":1,"library":1,"refer":1}
,"added":{"names":1,"design":1}
,"names":{"components":1,"within":1}
,"components":{"nets":1}
,"nets":{"external":1,"macros":1,"named":1}
,"external":{"pins":1,"macro":1}
,"pins":{"within":1}
,"within":{"macro":1,"name":1}
,"format":{"macro_name\u002Fobject_name":1}
,"macro_name\u002Fobject_name":{"(e.g":1}
,"(e.g":{"$adder_3\u002F$comp_0":1}
,"$adder_3\u002F$comp_0":{"$decoder_2\u002F$extpin_0)":1}
,"$decoder_2\u002F$extpin_0)":{"components":1}
,"name":{"space":1,"empty":1}
,"space":{"components":1,"example":1,"name":1}
,"unique":{"names":1}
,"example":{"component":1}
,"component":{"macro":1}
,"named":{"fred":1}
,"fred":{"cannot":1,"two":1,"epic":1}
,"cannot":{"two":1}
,"two":{"macros":1,"nets":1}
,"epic":{"prevents":1,"delete":1}
,"prevents":{"entering":1}
,"entering":{"non-unique":1}
,"non-unique":{"names":1}
,"empty":{"first":1}
,"first":{"instantiate":1}
,"instantiate":{"macro":1}
,"library":{"file":1}
,"file":{"design":1,"added":1,"thereafter":1,"original":1,"changed":1,"want":1,"following":1,"add":1,"place":1}
,"design":{"copy":1,"file":1,"change":1,"revised":1,"epic":1}
,"copy":{"macro":1,"original":1}
,"thereafter":{"subsequent":1}
,"subsequent":{"instantiations":1}
,"instantiations":{"macro":1}
,"refer":{"local":1}
,"local":{"copy":1}
,"original":{"library":1,"(external)":1}
,"(external)":{"macro":1}
,"changed":{"deleted":1}
,"deleted":{"effect":1}
,"effect":{"instances":1}
,"instances":{"library":1,"revised":1}
,"change":{"external":1}
,"want":{"update":1}
,"update":{"existing":1}
,"existing":{"design":1}
,"revised":{"library":1,"macro":1}
,"following":{"things":1}
,"things":{"re-map":1}
,"re-map":{"design":1}
,"delete":{"instances":1}
,"add":{"new":1}
,"new":{"instances":1}
,"place":{"old":1}
,"old":{"instances":1}
}
;Search.control.loadWordPairs(pairs);
