var pairs =
{
"deleting":{"external":1,"selected":1}
,"external":{"pins":1,"pin":1,"external":1}
,"pins":{"macro":1,"want":1,"choose":1,"longer":1,"display":1,"pins":1,"appear":1}
,"macro":{"mode":1}
,"mode":{"delete":1}
,"delete":{"external":1,"click":1,"button":1}
,"pin":{"longer":1,"external":1,"connected":1,"delete":1,"definitions":1}
,"longer":{"define":1,"external":1}
,"define":{"pin":1}
,"connected":{"net":1}
,"net":{"remain":1,"delete":1}
,"remain":{"connected":1}
,"definitions":{"select":1}
,"select":{"pins":1}
,"want":{"delete":1}
,"choose":{"edit":1}
,"edit":{"delete":1}
,"click":{"delete":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"deleting":1}
,"selected":{"pins":1}
,"display":{"list":1}
,"list":{"external":1}
,"appear":{"list":1}
}
;Search.control.loadWordPairs(pairs);
