var pairs =
{
"changing":{"pll":1}
,"pll":{"configuration":1,"(phase-locked":1,"element":1,"configured":1,"used":1,"pll":1,"utilizes":1,"source":1,"design":1,"attributes":1}
,"configuration":{"pll":1}
,"(phase-locked":{"loops)":1}
,"loops)":{"used":1}
,"used":{"modify":1,"distributing":1,"along":1}
,"modify":{"generate":1}
,"generate":{"clock":1}
,"clock":{"signals":1,"skew":1}
,"signals":{"meet":1,"different":1,"open":1,"pll":1}
,"meet":{"design":1}
,"design":{"requirements":1,"reducing":1,"example":1,"elements":1,"usage":1}
,"requirements":{"additionally":1}
,"additionally":{"plls":1}
,"plls":{"used":1}
,"distributing":{"clock":1}
,"different":{"devices":1}
,"devices":{"design":1,"improving":1}
,"reducing":{"clock":1}
,"skew":{"devices":1}
,"improving":{"i\u002Fo":1}
,"i\u002Fo":{"timing":1}
,"timing":{"generating":1}
,"generating":{"internal":1}
,"internal":{"clock":1}
,"open":{"logic":1}
,"logic":{"block":1,"logic":1}
,"block":{"view":1}
,"view":{"pll":1,"opens":1,"control":1,"fpga":1,"toolbar":1}
,"element":{"tabular":1}
,"tabular":{"view":1}
,"opens":{"enables":1}
,"enables":{"inspect":1}
,"inspect":{"pll":1}
,"configured":{"within":1}
,"within":{"design":1}
,"example":{"view":1}
,"control":{"signals":1}
,"along":{"settings":1}
,"settings":{"pll":1,"individual":1}
,"utilizes":{"several":1}
,"several":{"attributes":1}
,"attributes":{"allow":1,"logic":1,"usage":1}
,"allow":{"configuration":1}
,"source":{"constraints":1}
,"constraints":{"preference":1}
,"preference":{"files":1}
,"files":{"change":1}
,"change":{"attributes":1}
,"fpga":{"libraries":1}
,"libraries":{"manual":1}
,"manual":{"details":1}
,"details":{"attribute":1,"pll":1}
,"attribute":{"settings":1}
,"individual":{"pll":1}
,"elements":{"refer":1}
,"refer":{"following":1}
,"following":{"technical":1}
,"technical":{"notes":1}
,"notes":{"details":1}
,"usage":{"latticeecp2\u002Fm":1,"guide":1}
,"latticeecp2\u002Fm":{"sysclock":1}
,"sysclock":{"pll\u002Fdll":1,"pll":1}
,"pll\u002Fdll":{"design":1,"user\u2019s":1}
,"guide":{"(tn1103)":1,"(tn1178)":1,"(tn1098)":1,"(tn1049)":1,"(tn1089)":1,"(tn1199)":1}
,"(tn1103)":{"latticeecp3":1}
,"latticeecp3":{"sysclock":1}
,"(tn1178)":{"latticesc":1}
,"latticesc":{"sysclock":1}
,"user\u2019s":{"guide":1}
,"(tn1098)":{"latticeecp\u002Fec":1}
,"latticeecp\u002Fec":{"latticexp":1}
,"latticexp":{"sysclock":1}
,"(tn1049)":{"machxo":1}
,"machxo":{"sysclock":1}
,"(tn1089)":{"machxo2":1}
,"machxo2":{"sysclock":1}
,"(tn1199)":{"drc":1}
,"drc":{"check":1,"button":1,"results":1}
,"check":{"making":1}
,"making":{"changes":1}
,"changes":{"click":1}
,"click":{"drc":1}
,"button":{"logic":1}
,"toolbar":{"drc":1}
,"results":{"appear":1}
,"appear":{"tcl":1}
,"tcl":{"console":1}
,"console":{"editing":1}
,"editing":{"component":1}
,"component":{"logic":1}
}
;Search.control.loadWordPairs(pairs);
