var pairs =
{
"trace":{"timing":1,"(timing":1,"trace":1,"reports":1,"multiple":1,"currently":1}
,"timing":{"analysis":1,"errors":1,"violation":1,"error":1}
,"analysis":{"epic":1}
,"epic":{"run":1,"making":1,"trace":1,"used":1}
,"run":{"trace":1}
,"(timing":{"reporter":1}
,"reporter":{"circuit":1}
,"circuit":{"evaluator)":1}
,"evaluator)":{"within":1}
,"within":{"epic":1}
,"making":{"easy":1}
,"easy":{"visualize":1}
,"visualize":{"timing":1}
,"errors":{"modifications":1,"reported":1}
,"modifications":{"without":1}
,"without":{"going":1}
,"going":{"back":1}
,"back":{"forth":1}
,"forth":{"epic":1}
,"reports":{"slack":1,"(the":1}
,"slack":{"clock":1}
,"clock":{"period":1}
,"period":{"minus":1,"causing":1}
,"minus":{"propagation":1}
,"propagation":{"delay":1}
,"delay":{"port":1,"exceeds":1}
,"port":{"negative":1}
,"negative":{"values":1}
,"values":{"indicate":1}
,"indicate":{"propagation":1}
,"exceeds":{"clock":1}
,"causing":{"timing":1}
,"violation":{"epic":1}
,"used":{"specify":1}
,"specify":{"error":1}
,"error":{"verbose":1}
,"verbose":{"report":1,"reports":1}
,"report":{"types":1,"supported":1}
,"types":{"run":1}
,"multiple":{"preferences":1}
,"preferences":{"single":1}
,"single":{"preference":1}
,"preference":{"time":1,"timing":1,"file":1}
,"time":{"limit":1}
,"limit":{"number":1}
,"number":{"errors":1}
,"reported":{"per":1}
,"per":{"preference":1}
,"(the":{"summary":1}
,"summary":{"report":1}
,"supported":{"epic)":1}
,"epic)":{"input":1}
,"input":{"trace":1}
,"currently":{"loaded":1}
,"loaded":{"design":1}
,"design":{"preference":1}
,"file":{"running":1}
,"running":{"trace":1}
}
;Search.control.loadWordPairs(pairs);
