var pairs =
{
"external":{"pin":1,"name":1}
,"pin":{"attributes":1,"opens":1,"defined":1,"clicking":1,"name":1,"known":1,"site":1,"indicates":1,"placed":1,"function":1,"within":1,"types":1}
,"attributes":{"dialog":1,"opens":1}
,"dialog":{"box":1,"design":1,"options":1}
,"box":{"external":1,"called":1,"accessed":1,"button":1,"cancel":1,"help":1,"dialog":1}
,"called":{"macro":1}
,"macro":{"mode":1,"library":1,"pin":1,"inserted":1}
,"mode":{"design":1,"(see":1,"macro":1,"adding":1,"options":1}
,"design":{"mode":1,"modes)":1,"attribute":1,"component":1,"allowing":1,"closes":1,"attributes":1}
,"(see":{"design":1}
,"modes)":{"behaves":1}
,"behaves":{"differently":1}
,"differently":{"macro":1}
,"adding":{"external":1}
,"opens":{"dialog":1,"online":1}
,"defined":{"dialog":1}
,"accessed":{"selecting":1}
,"selecting":{"external":1}
,"clicking":{"attribute":1}
,"attribute":{"button":1,"feature":1}
,"button":{"actions":1,"applies":1,"ignores":1}
,"actions":{"panel":1}
,"panel":{"choosing":1}
,"choosing":{"design":1}
,"feature":{"description":1}
,"description":{"name":1}
,"name":{"pin":1,"external":1,"determines":1,"indicates":1,"component":1,"site":1}
,"determines":{"name":1}
,"known":{"macro":1}
,"library":{"file":1}
,"file":{"instantiated":1}
,"instantiated":{"design":1}
,"component":{"name":1,"containing":1}
,"indicates":{"name":1,"site":1}
,"containing":{"pin":1}
,"site":{"name":1,"component":1}
,"placed":{"type":1}
,"type":{"type":1,"pin":1}
,"function":{"specifies":1,"pin":1}
,"specifies":{"function":1}
,"within":{"macro":1}
,"types":{"apply":1}
,"apply":{"button":1}
,"applies":{"given":1}
,"given":{"options":1}
,"options":{"current":1,"commands":1,"may":1,"macro":1,"read-only":1}
,"current":{"design":1}
,"allowing":{"perform":1}
,"perform":{"options":1}
,"commands":{"leaving":1}
,"leaving":{"dialog":1}
,"closes":{"dialog":1}
,"cancel":{"button":1}
,"ignores":{"options":1}
,"may":{"specified":1}
,"specified":{"closes":1}
,"help":{"opens":1,"topic":1}
,"online":{"help":1}
,"topic":{"dialog":1}
,"inserted":{"selecting":1}
}
;Search.control.loadWordPairs(pairs);
