var pairs =
{
"locking":{"unlocking":1,"object":1}
,"unlocking":{"objects":1}
,"objects":{"lock":1,"prevent":1,"deleted":1}
,"lock":{"objects":1,"object":1,"preference":1,"option":1}
,"prevent":{"objects":1}
,"deleted":{"unplaced":1}
,"unplaced":{"(for":1}
,"(for":{"components)":1,"nets)":1}
,"components)":{"unrouted":1}
,"unrouted":{"(for":1}
,"nets)":{"preference":1}
,"preference":{"file":1,"already":1}
,"file":{"using":1}
,"using":{"attributes":1}
,"attributes":{"dialog":1}
,"dialog":{"boxes":1,"box":1}
,"boxes":{"epic":1}
,"epic":{"component":1}
,"component":{"locked":1,"first":1}
,"locked":{"cannot":1,"net":1}
,"cannot":{"unplace":1,"unroute":1}
,"unplace":{"unroute":1,"component":1}
,"unroute":{"unplace":1,"portion":1,"net":1}
,"first":{"unlock":1}
,"unlock":{"net":1,"however":1,"object":1}
,"net":{"locked":1,"(that":1,"net":1,"segment":1,"first":1,"lock":1,"preferences":1}
,"portion":{"net":1}
,"(that":{"entire":1}
,"entire":{"net":1}
,"segment":{"pin":1}
,"pin":{"wire)":1}
,"wire)":{"unroute":1}
,"however":{"add":1}
,"add":{"pins":1,"routing":1}
,"pins":{"add":1}
,"routing":{"locked":1}
,"object":{"select":1,"editing":1,"lock":1,"follow":1,"clear":1}
,"select":{"object":1,"lock":1}
,"editing":{"area":1}
,"area":{"main":1}
,"main":{"view":1}
,"view":{"click":1}
,"click":{"attribute":1,"apply":1,"confirm":1}
,"attribute":{"button":1,"lock":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"choose":1}
,"choose":{"design":1}
,"design":{"attribute":1}
,"already":{"exists":1}
,"exists":{"selected":1}
,"selected":{"object":1}
,"option":{"attributes":1,"click":1}
,"box":{"show":1,"select":1,"unlock":1}
,"show":{"check":1}
,"check":{"mark":1}
,"mark":{"attributes":1}
,"apply":{"click":1}
,"confirm":{"dismiss":1}
,"dismiss":{"net":1}
,"preferences":{"dialog":1}
,"follow":{"procedure":1}
,"procedure":{"locking":1}
,"clear":{"lock":1}
}
;Search.control.loadWordPairs(pairs);
