var pairs =
{
"changing":{"serdes":1}
,"serdes":{"configuration":1,"(serializer\u002Fdeserializer)":1,"element":1}
,"configuration":{"high-speed":1,"within":1}
,"high-speed":{"serdes":1}
,"(serializer\u002Fdeserializer)":{"block":1}
,"block":{"used":1,"view":1}
,"used":{"dedicated":1}
,"dedicated":{"pcs":1}
,"pcs":{"(physical":1}
,"(physical":{"coding":1}
,"coding":{"sublayer)":1}
,"sublayer)":{"functions":1}
,"functions":{"support":1}
,"support":{"data":1}
,"data":{"protocols":1}
,"protocols":{"pci":1}
,"pci":{"express":1}
,"express":{"gigabit":1}
,"gigabit":{"ethernet":1}
,"ethernet":{"xaui":1}
,"xaui":{"sonet":1}
,"sonet":{"multi-rate":1}
,"multi-rate":{"sdi":1}
,"sdi":{"open":1}
,"open":{"logic":1}
,"logic":{"block":1,"logic":1}
,"view":{"serdes":1,"opens":1,"toolbar":1}
,"element":{"tabular":1}
,"tabular":{"view":1}
,"opens":{"enables":1}
,"enables":{"modify":1}
,"modify":{"serdes":1}
,"within":{"design":1}
,"design":{"drc":1}
,"drc":{"check":1,"button":1,"results":1}
,"check":{"making":1}
,"making":{"changes":1}
,"changes":{"click":1}
,"click":{"drc":1}
,"button":{"logic":1}
,"toolbar":{"drc":1}
,"results":{"appear":1}
,"appear":{"tcl":1}
,"tcl":{"console":1}
,"console":{"editing":1}
,"editing":{"component":1}
,"component":{"logic":1}
}
;Search.control.loadWordPairs(pairs);
