var pairs =
{
"undoing":{"last":1}
,"last":{"change":1,"unroute":1}
,"change":{"undo":1}
,"undo":{"last":1,"button":1,"press":1}
,"unroute":{"unplace":1}
,"unplace":{"delete":1}
,"delete":{"operation":1}
,"operation":{"undo":1,"click":1}
,"click":{"undo":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"choose":1}
,"choose":{"edit":1}
,"edit":{"undo":1}
,"press":{"ctrl":1}
}
;Search.control.loadWordPairs(pairs);
