var pairs =
{
"timing":{"analysis":1,"errors":1,"paths":1,"violation":1}
,"analysis":{"error":1}
,"error":{"checking":1}
,"checking":{"trace":1,"epic":1}
,"trace":{"(timing":1,"within":1,"reports":1}
,"(timing":{"reporter":1}
,"reporter":{"circuit":1}
,"circuit":{"evaluator)":1}
,"evaluator)":{"tool":1}
,"tool":{"reports":1}
,"reports":{"timing":1,"slack":1}
,"errors":{"run":1,"configure":1,"design":1}
,"run":{"trace":1}
,"within":{"epic":1}
,"epic":{"makes":1}
,"makes":{"easy":1}
,"easy":{"visualize":1}
,"visualize":{"timing":1}
,"configure":{"options":1}
,"options":{"highlight":1}
,"highlight":{"timing":1}
,"paths":{"trace":1,"nets":1}
,"slack":{"clock":1}
,"clock":{"period":1}
,"period":{"minus":1,"causing":1}
,"minus":{"propagation":1}
,"propagation":{"delay":1}
,"delay":{"port":1,"exceeds":1}
,"port":{"negative":1}
,"negative":{"values":1}
,"values":{"indicate":1}
,"indicate":{"propagation":1}
,"exceeds":{"clock":1}
,"causing":{"timing":1}
,"violation":{"physical":1}
,"physical":{"design":1,"errors":1}
,"design":{"rule":1,"apart":1,"error":1}
,"rule":{"check":1}
,"check":{"(drc)":1}
,"(drc)":{"series":1}
,"series":{"tests":1}
,"tests":{"discover":1}
,"discover":{"logical":1}
,"logical":{"physical":1}
,"apart":{"performing":1}
,"performing":{"drc":1}
,"drc":{"calculate":1}
,"calculate":{"delays":1}
,"delays":{"paths":1}
,"nets":{"perform":1}
,"perform":{"signal":1}
,"signal":{"probing":1}
,"probing":{"design":1}
}
;Search.control.loadWordPairs(pairs);
