var pairs =
{
"manually":{"routing":1}
,"routing":{"switch":1,"matrices":1}
,"switch":{"box":1,"boxes":1}
,"box":{"switch":1,"chip":1,"click":1,"looks":1,"path":1,"paths":1,"select":1,"using":1,"pins":1}
,"boxes":{"located":1,"certain":1,"situated":1}
,"located":{"junctions":1,"inside":1}
,"junctions":{"horizontal":1}
,"horizontal":{"vertical":1}
,"vertical":{"local":1}
,"local":{"lines":1,"wires":1}
,"lines":{"used":1,"switch":1,"leading":1}
,"used":{"connect":1}
,"connect":{"local":1,"click":1,"route":1,"perform":1}
,"certain":{"allowable":1}
,"allowable":{"matrices":1,"routes":1}
,"matrices":{"pin":1,"different":1}
,"pin":{"connections":1,"given":1,"switch":1,"clear":1,"select":1}
,"connections":{"allowable":1}
,"routes":{"vary":1}
,"vary":{"depending":1}
,"depending":{"location":1}
,"location":{"switch":1}
,"chip":{"example":1,"(top":1}
,"example":{"switch":1}
,"situated":{"perimeter":1}
,"perimeter":{"chip":1,"permissible":1}
,"(top":{"bottom":1}
,"bottom":{"right":1}
,"right":{"left":1}
,"left":{"viewed":1}
,"viewed":{"epic)":1}
,"epic)":{"fewer":1}
,"fewer":{"pins":1}
,"pins":{"therefore":1,"want":1,"cannot":1,"order":1}
,"therefore":{"routing":1}
,"different":{"switch":1}
,"inside":{"perimeter":1}
,"permissible":{"paths":1}
,"paths":{"pin":1,"screen":1,"cleared":1}
,"given":{"switch":1}
,"click":{"mouse":1,"once":1,"route":1}
,"mouse":{"once":1}
,"once":{"pin":1,"again":1}
,"looks":{"similar":1}
,"similar":{"graphic":1}
,"graphic":{"below":1}
,"below":{"deselect":1,"illustrates":1}
,"deselect":{"pin":1}
,"clear":{"paths":1}
,"screen":{"click":1}
,"again":{"pin":1}
,"select":{"view":1,"local":1,"(in":1}
,"view":{"unhighlight":1}
,"unhighlight":{"switch":1}
,"path":{"displayed":1}
,"displayed":{"time":1}
,"time":{"within":1}
,"within":{"single":1}
,"single":{"switch":1}
,"cleared":{"new":1}
,"new":{"selected":1}
,"selected":{"route":1}
,"route":{"connection":1,"actions":1,"switch":1,"command":1,"bank":1}
,"connection":{"switch":1}
,"wires":{"leading":1}
,"leading":{"pins":1}
,"want":{"connect":1,"route":1}
,"actions":{"panel":1}
,"panel":{"figure":1}
,"figure":{"below":1}
,"illustrates":{"route":1}
,"using":{"route":1}
,"command":{"bank":1,"figure":1}
,"bank":{"shot":1}
,"shot":{"indirectly":1,"switch":1,"switchbox":1}
,"indirectly":{"connecting":1}
,"connecting":{"two":1}
,"two":{"switch":1}
,"cannot":{"connected":1}
,"connected":{"directly":1}
,"directly":{"want":1}
,"(in":{"correct":1}
,"correct":{"order)":1}
,"order)":{"local":1}
,"switchbox":{"select":1}
,"order":{"want":1}
,"perform":{"route":1}
}
;Search.control.loadWordPairs(pairs);
