var pairs =
{
"macro":{"drc":1}
,"drc":{"checks":1,"check":1,"drc":1,"click":1,"button":1,"performed":1,"tests)":1,"results":1}
,"checks":{"design":1,"test":1}
,"design":{"mode":1,"drc":1}
,"mode":{"number":1,"execute":1}
,"number":{"physical":1}
,"physical":{"drc":1}
,"test":{"macros":1}
,"macros":{"design":1}
,"execute":{"tests":1}
,"tests":{"during":1}
,"during":{"epic":1}
,"epic":{"session":1}
,"session":{"run":1}
,"run":{"macro":1}
,"check":{"sure":1}
,"sure":{"nothing":1}
,"nothing":{"selected":1}
,"selected":{"editing":1}
,"editing":{"area":1}
,"area":{"objects":1}
,"objects":{"menu":1}
,"menu":{"choose":1}
,"choose":{"design":1}
,"click":{"drc":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"macro":1}
,"performed":{"(along":1}
,"(along":{"drc":1}
,"tests)":{"drc":1}
,"results":{"appear":1}
,"appear":{"tcl":1}
,"tcl":{"console":1}
}
;Search.control.loadWordPairs(pairs);
