var pairs =
{
"cloning":{"macro":1}
,"macro":{"design":1,"instance":1,"target":1,"clone":1,"want":1,"copied":1,"format":1,"library":1,"number":1,"example":1,"called":1}
,"design":{"mode":1,"source":1}
,"mode":{"clone":1,"add":1,"object":1}
,"clone":{"macro":1,"select":1,"reference":1}
,"add":{"duplicate":1,"instantiation":1}
,"duplicate":{"macro":1}
,"instance":{"design":1}
,"source":{"placed":1,"macro\u0027s":1,"macro":1,"numbering":1}
,"placed":{"unplaced":1}
,"unplaced":{"macro":1}
,"target":{"vacant":1,"choose":1}
,"vacant":{"site":1}
,"site":{"place":1,"want":1,"components":1}
,"place":{"reference":1}
,"reference":{"component":1}
,"component":{"copied":1,"target":1,"source":1,"specify":1}
,"copied":{"macro":1,"selected":1,"positions":1}
,"object":{"menu":1}
,"menu":{"select":1}
,"select":{"name":1,"vacant":1}
,"name":{"macro":1,"copy":1,"assigned":1}
,"want":{"clone":1,"copy":1}
,"copy":{"source":1,"name":1,"macro":1,"named":1}
,"macro\u0027s":{"reference":1}
,"choose":{"edit":1}
,"edit":{"clone":1}
,"selected":{"site":1}
,"components":{"macro":1}
,"positions":{"relative":1}
,"relative":{"reference":1}
,"specify":{"name":1}
,"assigned":{"new":1}
,"new":{"macro":1,"copy":1}
,"format":{"$libfile_number":1}
,"$libfile_number":{"libfile":1}
,"libfile":{"name":1}
,"library":{"file":1}
,"file":{"source":1,"adder":1}
,"number":{"number":1,"assigned":1}
,"numbering":{"starts":1}
,"starts":{"increases":1}
,"increases":{"new":1}
,"example":{"multiple":1}
,"multiple":{"copies":1}
,"copies":{"macro":1}
,"called":{"add":1}
,"instantiation":{"macro":1}
,"adder":{"first":1}
,"first":{"copy":1}
,"named":{"$adder_0":1,"$adder_1":1}
,"$adder_0":{"second":1}
,"second":{"named":1}
,"$adder_1":{"epic":1}
,"epic":{"tcl":1}
,"tcl":{"commands":1}
}
;Search.control.loadWordPairs(pairs);
