var pairs =
{
"zooming":{"main":1,"area":1,"mouse":1,"keyboard":1}
,"main":{"view":1}
,"view":{"several":1,"menu":1,"entire":1}
,"several":{"tools":1}
,"tools":{"zoom":1}
,"zoom":{"epic":1,"toolbar":1,"commands":1,"enlarges":1,"reduces":1,"fit":1,"area":1,"control":1,"small":1,"backward":1,"zooming":1,"keyboard":1,"press":1}
,"epic":{"layout":1,"toolbar":1}
,"layout":{"including":1,"zoom":1,"fits":1,"fills":1,"holding":1}
,"including":{"zoom":1}
,"toolbar":{"mouse":1,"following":1,"view":1}
,"mouse":{"mouse":1,"wheel":1,"button":1}
,"wheel":{"keyboard":1,"mouse":1,"gives":1,"forward":1}
,"keyboard":{"combinations":1,"shortcuts":1,"zoom":1}
,"combinations":{"zoom":1}
,"following":{"zoom":1,"keyboard":1}
,"commands":{"available":1}
,"available":{"epic":1}
,"menu":{"zoom":1}
,"enlarges":{"view":1,"entire":1,"size":1}
,"entire":{"layout":1}
,"reduces":{"view":1,"enlarges":1}
,"fit":{"reduces":1}
,"fits":{"inside":1}
,"inside":{"window":1}
,"window":{"zoom":1,"selection":1}
,"size":{"selected":1}
,"selected":{"sites":1}
,"sites":{"components":1}
,"components":{"connections":1}
,"connections":{"layout":1}
,"fills":{"window":1}
,"selection":{"zooming":1}
,"area":{"enlarge":1,"layout":1,"dragging":1}
,"enlarge":{"area":1}
,"holding":{"left":1}
,"left":{"mouse":1,"zooming":1}
,"button":{"dragging":1}
,"dragging":{"right":1,"upward":1}
,"right":{"downward":1}
,"downward":{"afterwards":1}
,"afterwards":{"zoom":1}
,"upward":{"left":1}
,"gives":{"finer":1}
,"finer":{"zoom":1}
,"control":{"enabling":1}
,"enabling":{"zoom":1}
,"small":{"increments":1}
,"increments":{"pressing":1}
,"pressing":{"ctrl":1}
,"ctrl":{"key":1,"press":1,"+-or":1}
,"key":{"move":1}
,"move":{"mouse":1}
,"forward":{"zoom":1}
,"backward":{"zoom":1}
,"shortcuts":{"following":1,"enable":1}
,"enable":{"instantly":1}
,"instantly":{"zoom":1}
,"press":{"ctrl":1,"zoom":1}
,"+-or":{"press":1}
}
;Search.control.loadWordPairs(pairs);
