var pairs =
{
"calculating":{"delay":1}
,"delay":{"delay":1,"time":1,"associated":1,"information":1,"values":1,"paths":1,"click":1,"button":1,"calculation":1,"shown":1}
,"time":{"signal":1}
,"signal":{"takes":1}
,"takes":{"reach":1}
,"reach":{"load":1}
,"load":{"pin":1,"pins":1}
,"pin":{"driver":1,"calculate":1,"list":1,"name":1,"net":1,"unrouted":1,"listed":1}
,"driver":{"pin":1,"pins":1,"(which":1}
,"calculate":{"delay":1}
,"associated":{"load":1,"delays":1}
,"pins":{"driver":1,"given":1,"path":1,"appears":1}
,"given":{"net":1,"nanoseconds":1}
,"net":{"path":1,"two":1,"choose":1,"attributes":1,"driver":1,"fully":1}
,"path":{"epic":1,"net":1,"delay":1,"maximum":1}
,"epic":{"delay":1}
,"information":{"displayed":1}
,"displayed":{"tcl":1}
,"tcl":{"console":1,"console)":1}
,"console":{"otherwise":1,"along":1}
,"otherwise":{"indicated":1}
,"indicated":{"delay":1}
,"values":{"given":1}
,"nanoseconds":{"calculate":1}
,"paths":{"nets":1,"two":1}
,"nets":{"select":1}
,"select":{"net":1}
,"two":{"specific":1,"pins":1}
,"specific":{"pins":1}
,"choose":{"design":1}
,"design":{"delay":1}
,"click":{"delay":1,"attribute":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"path":1,"view":1}
,"calculation":{"multiple":1}
,"multiple":{"paths":1}
,"maximum":{"delay":1}
,"shown":{"click":1}
,"attribute":{"button":1}
,"view":{"pin":1}
,"list":{"associated":1,"tcl":1,"pins":1}
,"delays":{"net":1}
,"attributes":{"dialog":1}
,"dialog":{"box":1}
,"box":{"blank":1}
,"blank":{"next":1}
,"next":{"pin":1}
,"name":{"(either":1}
,"(either":{"pin":1}
,"console)":{"means":1}
,"means":{"either":1}
,"either":{"pin":1}
,"(which":{"delay)":1}
,"delay)":{"pin":1}
,"unrouted":{"net":1,"pin":1}
,"fully":{"partially":1,"unrouted":1}
,"partially":{"routed":1}
,"routed":{"list":1}
,"appears":{"tcl":1}
,"along":{"associated":1}
,"listed":{"unrouted":1}
}
;Search.control.loadWordPairs(pairs);
