var pairs =
{
"swapping":{"component":1,"components":1}
,"component":{"pins":1,"epic":1,"programmed":1,"logic":1,"changes":1}
,"pins":{"swap":1,"component":1,"permitted":1,"swapped":1,"select":1,"wish":1,"unrouted":1}
,"swap":{"command":1,"pins":1,"component":1,"choose":1,"click":1,"button":1,"locations":1,"swapping":1}
,"command":{"enables":1}
,"enables":{"swap":1}
,"epic":{"allows":1}
,"allows":{"swap":1}
,"permitted":{"mode":1}
,"mode":{"component":1}
,"programmed":{"pins":1}
,"swapped":{"internal":1}
,"internal":{"component":1}
,"logic":{"modified":1}
,"modified":{"match":1}
,"match":{"new":1}
,"new":{"pin":1}
,"pin":{"positions":1,"swap":1}
,"positions":{"swap":1}
,"select":{"two":1}
,"two":{"pins":1}
,"wish":{"swap":1}
,"choose":{"edit":1}
,"edit":{"swap":1}
,"click":{"swap":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"two":1}
,"unrouted":{"swap":1}
,"locations":{"rerouted":1}
,"rerouted":{"programming":1}
,"programming":{"component":1}
,"changes":{"reflect":1}
,"reflect":{"pin":1}
}
;Search.control.loadWordPairs(pairs);
