var pairs =
{
"editing":{"pfu":1,"connections":1,"operation":1,"component":1}
,"pfu":{"logic":1,"slice":1}
,"logic":{"logic":1,"block":1,"equations":1,"click":1}
,"block":{"view":1}
,"view":{"selected":1,"editing":1,"different":1,"enables":1,"edit":1,"click":1,"toolbar":1}
,"selected":{"pfu":1,"select":1,"state":1,"deselected":1,"programmed":1,"changing":1}
,"slice":{"enables":1,"lut":1,"component":1,"select":1}
,"enables":{"edit":1,"view":1}
,"edit":{"connections":1,"lut":1,"equations":1}
,"connections":{"within":1,"edit":1}
,"within":{"slice":1,"pfu":1,"schematic":1}
,"lut":{"equations":1,"possible":1}
,"equations":{"changes":1,"equations":1,"dialog":1,"change":1,"logic":1,"lut":1,"click":1}
,"changes":{"select":1}
,"select":{"pfu":1,"component":1,"input":1,"pin":1}
,"component":{"open":1,"pins":1,"logic":1}
,"open":{"logic":1}
,"pins":{"within":1,"different":1,"mutually":1,"triangle":1,"selected":1,"square":1,"rhombus":1,"programmed":1}
,"schematic":{"logic":1}
,"different":{"pins":1,"symbol":1}
,"symbol":{"shapes":1,"shape":1}
,"shapes":{"select":1,"description":1}
,"input":{"pin":1}
,"pin":{"symbolized":1,"symbol":1,"types":1,"using":1,"programmed":1}
,"symbolized":{"triangle":1}
,"triangle":{"square":1,"selectable":1}
,"square":{"group":1,"selectable":1}
,"group":{"pins":1}
,"mutually":{"exclusive":1}
,"exclusive":{"selected":1}
,"shape":{"filled":1}
,"filled":{"show":1}
,"show":{"selected":1}
,"state":{"following":1}
,"following":{"table":1}
,"table":{"lists":1}
,"lists":{"pin":1}
,"types":{"required":1}
,"required":{"editing":1}
,"operation":{"pin":1}
,"description":{"selectable":1}
,"selectable":{"pins":1,"programmable":1}
,"deselected":{"using":1}
,"using":{"left":1,"shift":1}
,"left":{"mouse":1}
,"mouse":{"button":1}
,"button":{"selectable":1,"cycle":1,"combination":1,"toolbar":1,"logic":1}
,"programmable":{"pins":1,"pin":1}
,"programmed":{"select":1,"four":1,"above":1}
,"cycle":{"valid":1}
,"valid":{"programming":1,"operators":1}
,"programming":{"using":1}
,"shift":{"left":1}
,"combination":{"programmable":1}
,"four":{"states":1}
,"states":{"signal":1}
,"signal":{"(symbolized":1}
,"(symbolized":{"signal":1,"power":1,"ground":1,"programmable":1}
,"power":{"(symbolized":1}
,"ground":{"(symbolized":1}
,"rhombus":{"programmable":1}
,"above":{"always":1}
,"always":{"selected":1}
,"changing":{"logic":1,"pfu":1}
,"dialog":{"box":1}
,"box":{"logic":1,"appears":1,"upper":1}
,"change":{"lut":1}
,"click":{"equation":1,"note":1,"drc":1}
,"equation":{"button":1}
,"toolbar":{"equations":1,"run":1}
,"appears":{"showing":1}
,"showing":{"logic":1}
,"possible":{"strings":1}
,"strings":{"shown":1,"meaning":1}
,"shown":{"even":1}
,"even":{"modes":1}
,"modes":{"certain":1}
,"certain":{"strings":1}
,"meaning":{"valid":1}
,"operators":{"*represents":1}
,"*represents":{"logical":1}
,"logical":{"represents":1,"@represents":1,"xor":1,"text":1}
,"represents":{"logical":1}
,"@represents":{"logical":1}
,"xor":{"represents":1}
,"text":{"boxes":1}
,"boxes":{"luts":1}
,"luts":{"edit":1}
,"note":{"entries":1}
,"entries":{"fields":1}
,"fields":{"dialog":1}
,"upper":{"case":1}
,"case":{"letters":1}
,"letters":{"example":1}
,"example":{"legal":1}
,"legal":{"checking":1}
,"checking":{"edits":1}
,"edits":{"changing":1}
,"drc":{"button":1,"results":1}
,"run":{"design":1}
,"design":{"rule":1}
,"rule":{"check":1}
,"check":{"drc":1}
,"results":{"appear":1}
,"appear":{"tcl":1}
,"tcl":{"console":1}
,"console":{"editing":1}
}
;Search.control.loadWordPairs(pairs);
