var pairs =
{
"trace":{"dialog":1,"report":1}
,"dialog":{"box":1,"running":1}
,"box":{"trace":1,"allows":1,"opens":1,"help":1}
,"allows":{"run":1,"select":1}
,"run":{"timing":1,"button":1}
,"timing":{"analysis":1,"related":1}
,"analysis":{"design":1,"type":1,"available":1,"report":1,"displays":1}
,"design":{"results":1,"trace":1,"selected":1}
,"results":{"displayed":1,"available":1}
,"displayed":{"immediately":1}
,"immediately":{"dialog":1}
,"opens":{"choose":1,"online":1}
,"choose":{"design":1}
,"report":{"feature":1,"select":1,"reports":1,"analysis":1,"without":1,"limits":1}
,"feature":{"description":1}
,"description":{"report":1}
,"select":{"type":1,"preferences":1}
,"type":{"report":1,"allows":1,"option":1}
,"reports":{"errors":1,"unlimited":1}
,"errors":{"verbose":1}
,"verbose":{"report":1,"timing":1}
,"preferences":{"analysis":1,"section":1,"displays":1,"design":1,"selected":1,"want":1}
,"available":{"timing":1}
,"related":{"preferences":1}
,"section":{"default":1,"cancel":1}
,"default":{"enumeration":1}
,"enumeration":{"default":1,"runs":1}
,"runs":{"verbose":1,"timing":1}
,"without":{"considering":1}
,"considering":{"effect":1}
,"effect":{"constraints":1}
,"constraints":{"number":1}
,"number":{"items":1,"available":1}
,"items":{"report":1,"reported":1}
,"limits":{"number":1}
,"reported":{"maximum":1}
,"maximum":{"specified":1}
,"specified":{"reports":1,"closes":1}
,"unlimited":{"number":1}
,"displays":{"list":1,"results":1}
,"list":{"timing-related":1,"run":1}
,"timing-related":{"preferences":1}
,"selected":{"preferences":1,"analysis":1}
,"option":{"select":1}
,"want":{"analyzed":1}
,"analyzed":{"list":1}
,"button":{"runs":1,"ignores":1}
,"cancel":{"button":1}
,"ignores":{"options":1}
,"options":{"may":1}
,"may":{"specified":1}
,"closes":{"dialog":1}
,"help":{"opens":1,"topic":1}
,"online":{"help":1}
,"topic":{"dialog":1}
,"running":{"trace":1}
}
;Search.control.loadWordPairs(pairs);
