var pairs =
{
"design":{"rule":1,"drc":1}
,"rule":{"check":1}
,"check":{"dialog":1,"(drc)":1,"chip":1,"options":1}
,"dialog":{"box":1,"physical":1}
,"box":{"design":1,"opens":1,"cancel":1,"help":1}
,"opens":{"choose":1,"online":1}
,"choose":{"design":1}
,"drc":{"configure":1,"refer":1,"select":1,"checks":1,"clicking":1,"run":1,"objects":1,"messages":1,"issue":1}
,"configure":{"drc":1}
,"refer":{"physical":1}
,"physical":{"design":1}
,"(drc)":{"information":1}
,"information":{"feature":1}
,"feature":{"description":1}
,"description":{"drc":1}
,"select":{"select":1,"drc":1,"nets":1}
,"checks":{"want":1}
,"want":{"run":1,"skip":1}
,"run":{"clear":1,"default":1,"objects":1,"drc":1}
,"clear":{"want":1,"options":1}
,"skip":{"default":1}
,"default":{"selected":1,"drc":1}
,"selected":{"clear":1,"option":1,"main":1,"options":1,"closes":1}
,"options":{"nets":1,"button":1,"closes":1,"selected":1}
,"nets":{"button":1,"runs":1,"unplaced":1}
,"button":{"changes":1,"clears":1,"applies":1,"ignores":1}
,"changes":{"select":1}
,"runs":{"net":1}
,"net":{"net":1,"sanity":1}
,"sanity":{"drc":1}
,"clicking":{"button":1}
,"clears":{"block":1}
,"block":{"check":1}
,"chip":{"check":1}
,"objects":{"selected":1}
,"option":{"run":1,"including":1}
,"main":{"view":1}
,"view":{"drc":1}
,"messages":{"default":1,"report":1,"button":1}
,"issue":{"warnings":1}
,"warnings":{"error":1,"errors":1}
,"error":{"messages":1}
,"report":{"unrouted":1}
,"unrouted":{"nets":1}
,"unplaced":{"components":1}
,"components":{"option":1}
,"including":{"warnings":1,"error":1}
,"errors":{"unrouted":1}
,"applies":{"selected":1}
,"closes":{"dialog":1}
,"cancel":{"button":1}
,"ignores":{"options":1}
,"help":{"opens":1,"topic":1}
,"online":{"help":1}
,"topic":{"dialog":1}
}
;Search.control.loadWordPairs(pairs);
