var pairs =
{
"running":{"design":1}
,"design":{"rule":1,"selected":1,"drc":1,"choose":1}
,"rule":{"checks":1,"check":1}
,"checks":{"(drc)":1}
,"(drc)":{"run":1}
,"run":{"drc":1}
,"drc":{"whole":1,"command":1,"menu":1,"specific":1,"current":1,"select":1,"nothing":1,"drc":1,"click":1,"button":1,"results":1,"specified":1,"configure":1,"dialog":1,"tests":1,"error":1}
,"whole":{"design":1}
,"selected":{"objects":1,"want":1,"tests":1,"nets":1,"associated":1,"net":1}
,"objects":{"quick":1,"run":1,"design":1,"want":1,"objects":1,"selected":1}
,"quick":{"select":1}
,"select":{"drc":1,"objects":1,"combination":1,"desired":1}
,"command":{"actions":1}
,"actions":{"panel":1}
,"panel":{"design":1,"drc":1}
,"menu":{"run":1}
,"specific":{"options":1}
,"options":{"specifying":1,"select":1,"click":1}
,"specifying":{"design":1}
,"check":{"configuration":1,"objects":1,"block":1,"performed":1,"along":1,"(drc)":1}
,"configuration":{"dialog":1}
,"dialog":{"box":1}
,"box":{"run":1,"select":1}
,"current":{"settings":1}
,"settings":{"select":1}
,"combination":{"components":1,"nets":1}
,"components":{"net":1,"selected":1}
,"net":{"pins":1,"check":1,"block":1}
,"pins":{"route":1}
,"route":{"segments":1}
,"segments":{"nets":1}
,"nets":{"run":1,"associated":1,"components":1}
,"nothing":{"selected":1}
,"want":{"check":1,"run":1}
,"choose":{"design":1}
,"click":{"drc":1}
,"button":{"actions":1}
,"results":{"shown":1}
,"shown":{"tcl":1}
,"tcl":{"console":1}
,"console":{"run":1,"appropriate":1}
,"specified":{"options":1}
,"configure":{"drc":1}
,"desired":{"options":1}
,"tests":{"performed":1,"follow":1}
,"performed":{"objects":1,"list":1}
,"follow":{"rules":1}
,"rules":{"component":1}
,"component":{"selected":1,"checked":1}
,"associated":{"checked":1,"component":1}
,"checked":{"pin":1,"combination":1}
,"pin":{"selected":1}
,"block":{"check":1}
,"list":{"individual":1}
,"individual":{"violations":1}
,"violations":{"net":1}
,"along":{"type":1}
,"type":{"message":1}
,"message":{"(error":1}
,"(error":{"warning)":1}
,"warning)":{"appears":1}
,"appears":{"tcl":1}
,"appropriate":{"documentation":1}
,"documentation":{"drc":1}
,"error":{"messages":1}
,"messages":{"warnings":1}
,"warnings":{"physical":1}
,"physical":{"design":1}
}
;Search.control.loadWordPairs(pairs);
