var pairs =
{
"adding":{"component":1}
,"component":{"pins":1,"placed":1,"selected":1}
,"pins":{"component":1,"added":1,"existing":1,"want":1,"placed":1,"belong":1,"editing":1,"routed":1}
,"added":{"nets":1}
,"nets":{"component":1}
,"placed":{"design":1,"component":1}
,"design":{"add":1}
,"add":{"component":1,"net":1,"pins":1,"new":1}
,"existing":{"net":1}
,"net":{"editing":1,"selected":1,"following":1,"add":1,"pin":1,"click":1,"pins":1,"automatic":1}
,"editing":{"area":1}
,"area":{"main":1}
,"main":{"view":1}
,"view":{"select":1}
,"select":{"component":1,"net":1}
,"want":{"add":1}
,"selected":{"pins":1}
,"belong":{"net":1}
,"following":{"object":1}
,"object":{"menu":1}
,"menu":{"select":1}
,"pin":{"ratsnest":1}
,"ratsnest":{"line":1}
,"line":{"routed":1}
,"routed":{"segment":1,"net":1}
,"segment":{"desired":1}
,"desired":{"net":1}
,"click":{"add":1}
,"new":{"net":1}
,"automatic":{"routing":1}
}
;Search.control.loadWordPairs(pairs);
