var pairs =
{
"setting":{"preferences":1}
,"preferences":{"within":1,"physical":1,"example":1,"preference":1,"however":1,"supported":1}
,"within":{"epic":1}
,"epic":{"add":1,"perform":1,"allows":1}
,"add":{"delete":1}
,"delete":{"certain":1}
,"certain":{"preferences":1,"object":1}
,"physical":{"preference":1}
,"preference":{"file":1,"changes":1}
,"file":{"(.prf)":1,"whenever":1,"tcl":1}
,"(.prf)":{"edit":1}
,"edit":{"preference":1}
,"whenever":{"preference":1}
,"changes":{"epic":1}
,"perform":{"save":1}
,"save":{"command":1}
,"command":{"attributes":1,"line":1}
,"attributes":{"dialog":1,"attributes":1}
,"dialog":{"boxes":1,"box":1}
,"boxes":{"enable":1}
,"enable":{"change":1}
,"change":{"certain":1,"attributes":1}
,"example":{"change":1}
,"box":{"add":1}
,"object":{"types":1}
,"types":{"paths":1}
,"paths":{"buses":1}
,"buses":{"writing":1}
,"writing":{"new":1}
,"new":{"preferences":1}
,"tcl":{"command":1}
,"line":{"epic":1}
,"allows":{"preferences":1}
,"however":{"preferences":1}
,"supported":{"epic":1}
}
;Search.control.loadWordPairs(pairs);
