var pairs =
{
"notes":{"selecting":1}
,"selecting":{"buses":1}
,"buses":{"paths":1}
,"paths":{"unplaced":1,"cleared":1}
,"unplaced":{"components":1}
,"components":{"macros":1}
,"macros":{"cannot":1}
,"cannot":{"selected":1,"perform":1}
,"selected":{"editing":1,"item":1,"multiple":1,"using":1,"items":1,"choose":1,"select":1,"pin":1,"switch":1,"within":1}
,"editing":{"area":1}
,"area":{"main":1,"becomes":1,"changes":1,"click":1}
,"main":{"view":1}
,"view":{"select":1,"unselect":1}
,"select":{"objects":1,"object":1,"component":1,"editing":1,"previously":1,"single":1,"switch":1,"ratsnest":1}
,"objects":{"using":1,"selected":1}
,"using":{"object":1,"ctrl":1}
,"object":{"menu":1,"type":1,"however":1,"select":1}
,"menu":{"select":1,"choose":1,"editing":1}
,"type":{"drop-down":1}
,"drop-down":{"menu":1}
,"choose":{"desired":1,"view":1}
,"desired":{"net":1}
,"net":{"component":1,"macro":1,"entire":1,"becomes":1,"containing":1,"selected":1}
,"component":{"macro":1,"net":1}
,"macro":{"bus":1,"name":1}
,"bus":{"path":1}
,"path":{"select":1}
,"name":{"object":1}
,"becomes":{"highlighted":1,"selected":1}
,"highlighted":{"editing":1,"net":1}
,"changes":{"object":1}
,"however":{"select":1}
,"click":{"object":1,"combination":1,"background":1,"net":1}
,"previously":{"selected":1}
,"item":{"longer":1}
,"longer":{"selected":1}
,"multiple":{"objects":1}
,"ctrl":{"click":1}
,"combination":{"click":1,"switch":1}
,"background":{"previously":1}
,"items":{"longer":1}
,"unselect":{"clear":1}
,"clear":{"selections":1}
,"selections":{"click":1}
,"entire":{"net":1}
,"single":{"wire":1,"switch":1}
,"wire":{"alt":1}
,"alt":{"click":1}
,"switch":{"box":1}
,"box":{"pins":1,"pin":1,"cannot":1,"select":1}
,"pins":{"selectable":1,"within":1}
,"selectable":{"select":1}
,"pin":{"display":1,"pins":1,"time":1,"selected":1}
,"display":{"highlight":1,"connections":1}
,"highlight":{"allowable":1}
,"allowable":{"connections":1}
,"connections":{"selected":1,"switch":1}
,"within":{"switch":1,"single":1}
,"perform":{"operations":1}
,"operations":{"selected":1}
,"time":{"paths":1}
,"cleared":{"new":1}
,"new":{"switch":1}
,"ratsnest":{"line":1}
,"line":{"entire":1,"highlighted":1}
,"containing":{"ratsnest":1}
}
;Search.control.loadWordPairs(pairs);
