var pairs =
{
"signal":{"probing":1,"probed":1,"connecting":1,"timing":1,"list":1,"status":1,"name":1,"probes":1}
,"probing":{"signal":1,"feature":1,"internal":1,"configuration":1,"epic":1}
,"feature":{"provides":1}
,"provides":{"reliable":1}
,"reliable":{"means":1}
,"means":{"routing":1}
,"routing":{"internal":1}
,"internal":{"signals":1,"fpga":1}
,"signals":{"otherwise":1,"clicking":1,"begin":1,"probe":1}
,"otherwise":{"unused":1}
,"unused":{"output":1}
,"output":{"pins":1,"pin":1}
,"pins":{"observed":1}
,"observed":{"test":1}
,"test":{"equipment":1}
,"equipment":{"logic":1}
,"logic":{"analyzer":1}
,"analyzer":{"signal":1,"fpga":1,"allow":1}
,"probed":{"designer":1,"signal":1}
,"designer":{"trace":1}
,"trace":{"signal":1}
,"connecting":{"logic":1}
,"fpga":{"output":1,"logic":1}
,"pin":{"note":1}
,"note":{"signal":1,"manually":1}
,"allow":{"accurate":1}
,"accurate":{"signal":1}
,"timing":{"analysis":1}
,"analysis":{"probed":1}
,"list":{"created":1,"reuse":1,"left":1,"signals":1,"original":1,"signal":1,"text":1,"open":1}
,"created":{"edited":1}
,"edited":{"signal":1}
,"configuration":{"dialog":1,"grid":1}
,"dialog":{"box":1}
,"box":{"save":1,"begin":1,"remove":1,"click":1,"notes":1}
,"save":{"probed":1,"current":1}
,"reuse":{".ncd":1,"creating":1,"probed":1}
,".ncd":{"file":1}
,"file":{"regenerated":1,"want":1,"saved":1,"importing":1}
,"regenerated":{"perform":1}
,"perform":{"signal":1}
,"epic":{"choose":1}
,"choose":{"design":1}
,"design":{"signal":1}
,"begin":{"pairing":1,"letter":1}
,"pairing":{"desired":1}
,"desired":{"signals":1}
,"clicking":{"dragging":1,"appropriate":1}
,"dragging":{"signal":1}
,"left":{"potential":1}
,"potential":{"receiver":1}
,"receiver":{"grid":1}
,"grid":{"cells":1,"select":1}
,"cells":{"(available":1}
,"(available":{"i\u002Fo)":1}
,"i\u002Fo)":{"right":1}
,"right":{"sort":1}
,"sort":{"columns":1}
,"columns":{"available":1}
,"available":{"signal":1}
,"status":{"clicking":1}
,"appropriate":{"column":1}
,"column":{"title":1}
,"title":{"wildcard":1}
,"wildcard":{"filter":1}
,"filter":{"option":1,"list":1,"text":1}
,"option":{"searching":1}
,"searching":{"particular":1}
,"particular":{"signal":1}
,"name":{"example":1}
,"example":{"type":1}
,"type":{"press":1}
,"press":{"enter":1}
,"enter":{"key":1,"*in":1}
,"key":{"filter":1}
,"letter":{"refresh":1}
,"refresh":{"list":1}
,"original":{"state":1}
,"state":{"enter":1}
,"*in":{"wildcard":1}
,"text":{"box":1,"file":1}
,"remove":{"signal":1,"probe":1,"selected":1,"probes":1}
,"probes":{"right-click":1,"remove":1,"popup":1}
,"right-click":{"signals":1}
,"probe":{"configuration":1,"remove":1}
,"select":{"remove":1}
,"selected":{"probes":1}
,"popup":{"menu":1}
,"menu":{"export":1}
,"export":{"probed":1,"save":1}
,"creating":{"probed":1}
,"click":{"export":1,"import":1}
,"current":{"list":1}
,"want":{"reuse":1}
,"open":{"signal":1}
,"import":{"import":1,"text":1}
,"saved":{"note":1}
,"manually":{"edit":1}
,"edit":{"probed":1}
,"importing":{"signal":1}
,"notes":{"signal":1}
}
;Search.control.loadWordPairs(pairs);
