var pairs =
{
"running":{"trace":1,"errors-only":1}
,"trace":{"trace":1,"dialog":1,"choose":1,"report":1,"run":1,"performs":1,"timing":1}
,"dialog":{"box":1}
,"box":{"available":1,"allows":1,"opens":1,"lists":1,"select":1}
,"available":{"design":1,"timing":1}
,"design":{"menu":1,"trace":1}
,"menu":{"enables":1,"epic":1}
,"enables":{"select":1}
,"select":{"preferences":1,"constrained":1,"type":1,"selected":1,"default":1,"preference":1}
,"preferences":{"options":1,"available":1,"section":1,"analyzed":1,"analysis":1,"select":1,"want":1,"displays":1}
,"options":{"timing":1,"top":1}
,"timing":{"analysis":1,"related":1,"engine":1}
,"analysis":{"run":1,"view":1,"type":1,"click":1,"preferences":1,"epic":1}
,"run":{"analysis":1,"trace":1,"verbose":1}
,"view":{"results":1,"run":1,"highlight":1,"right-click":1,"trace":1}
,"results":{"immediately":1,"highlight":1,"preference":1}
,"immediately":{"within":1}
,"within":{"trace":1}
,"allows":{"select":1}
,"constrained":{"path":1,"net":1}
,"path":{"results":1,"define":1,"preference":1,"editing":1}
,"highlight":{"editing":1,"constrained":1,"pop-up":1}
,"editing":{"area":1}
,"area":{"main":1}
,"main":{"view":1}
,"choose":{"design":1,"highlight":1}
,"report":{"trace":1,"analysis":1,"select":1,"verbose":1,"preferences":1}
,"opens":{"displays":1}
,"displays":{"timing-related":1,"results":1}
,"timing-related":{"preferences":1}
,"related":{"preferences":1}
,"section":{"trace":1}
,"lists":{"valid":1}
,"valid":{"preferences":1}
,"analyzed":{"delay":1,"selected":1}
,"delay":{"calculation":1}
,"calculation":{"timing":1}
,"engine":{"including":1}
,"including":{"define":1}
,"define":{"bus":1,"path":1,"startpoint":1,"endpoint":1}
,"bus":{"define":1}
,"startpoint":{"define":1}
,"endpoint":{"options":1}
,"top":{"dialog":1}
,"type":{"report":1,"number":1,"option":1,"step":1}
,"number":{"items":1}
,"items":{"trace":1}
,"selected":{"preferences":1,"default":1}
,"option":{"running":1}
,"errors-only":{"report":1}
,"verbose":{"report":1}
,"default":{"enumeration":1}
,"enumeration":{"trace":1,"analysis":1}
,"want":{"analyzed":1}
,"step":{"click":1}
,"click":{"preference":1,"run":1}
,"preference":{"trace":1,"tree":1,"select":1}
,"performs":{"timing":1}
,"tree":{"view":1}
,"net":{"path":1}
,"right-click":{"choose":1}
,"pop-up":{"menu":1}
,"epic":{"highlights":1,"calculating":1}
,"highlights":{"net":1}
,"calculating":{"delay":1}
}
;Search.control.loadWordPairs(pairs);
