var pairs =
{
"routing":{"connections":1,"turned":1,"software":1,"path":1,"specify":1}
,"connections":{"routed":1,"unrouting":1,"nets":1,"design":1}
,"routed":{"editing":1}
,"editing":{"area":1}
,"area":{"main":1}
,"main":{"view":1}
,"view":{"automatically":1}
,"automatically":{"manually":1}
,"manually":{"default":1}
,"default":{"automatic":1}
,"automatic":{"routing":1}
,"turned":{"automatic":1}
,"software":{"selects":1}
,"selects":{"routing":1}
,"path":{"additions":1,"used":1}
,"additions":{"changes":1}
,"changes":{"nets":1}
,"nets":{"components":1,"involved":1}
,"components":{"macros":1}
,"macros":{"manual":1}
,"manual":{"routing":1}
,"specify":{"routing":1}
,"used":{"unroute":1}
,"unroute":{"connections":1}
,"unrouting":{"rips":1}
,"rips":{"specified":1}
,"specified":{"routes":1}
,"routes":{"without":1}
,"without":{"eliminating":1}
,"eliminating":{"logical":1}
,"logical":{"connections":1}
,"involved":{"route":1}
,"route":{"unroute":1}
}
;Search.control.loadWordPairs(pairs);
