var pairs =
{
"opening":{"designs":1}
,"designs":{"macros":1}
,"macros":{"opened":1}
,"opened":{"epic":1,"design":1}
,"epic":{"software":1,"dialog":1,"automatically":1,"loads":1}
,"software":{"open":1}
,"open":{"existing":1,"open":1,"design":1,"different":1,"preference":1,"macro":1,"epic":1}
,"existing":{"design":1,"macro":1}
,"design":{"existing":1,"choose":1,"alternatively":1,"file":1,"dialog":1,"simply":1,"browse":1,"directory":1,"displays":1}
,"macro":{"open":1,"choose":1,"dialog":1,"file":1}
,"choose":{"file":1}
,"file":{"open":1,"file":1,"recent":1,".prf":1,"auto":1,"root":1,"epic":1,"click":1,"(.nmc)":1,"displays":1}
,"alternatively":{"select":1}
,"select":{"recently":1,"name":1,"click":1}
,"recently":{"opened":1}
,"recent":{"files":1}
,"files":{"menu":1,"last":1}
,"menu":{"open":1}
,"dialog":{"box":1}
,"box":{"appears":1,"display":1,"navigate":1}
,"appears":{"previously":1}
,"previously":{"used":1}
,"used":{"epic":1}
,"display":{"name":1}
,"name":{"location":1,".ncd":1,".prf":1}
,"location":{".ncd":1}
,".ncd":{"file":1}
,".prf":{"files":1,"file":1}
,"last":{"project":1}
,"project":{"open":1}
,"simply":{"click":1}
,"click":{"open":1,"browse":1,"epic":1}
,"different":{"design":1}
,"browse":{"button":1}
,"button":{"navigate":1,"select":1}
,"navigate":{"directory":1,"macro":1}
,"directory":{".ncd":1,"contains":1}
,"auto":{"lookup":1}
,"lookup":{"selected":1}
,"selected":{"design":1,"click":1}
,"contains":{"preference":1}
,"preference":{"file":1}
,"root":{"name":1}
,"automatically":{"open":1}
,"loads":{"design":1,"macro":1}
,"displays":{"layout":1}
,"layout":{"editing":1}
,"editing":{"area":1}
,"area":{"main":1}
,"main":{"view":1}
,"view":{"open":1}
,"(.nmc)":{"select":1}
}
;Search.control.loadWordPairs(pairs);
