var pairs =
{
"wire":{"attributes":1,"editing":1,"selected":1,"pinwire":1,"used":1,"wire":1,"unused":1}
,"attributes":{"dialog":1,"open":1}
,"dialog":{"box":1}
,"box":{"select":1,"feature":1,"help":1}
,"select":{"single":1}
,"single":{"wire":1}
,"editing":{"area":1}
,"area":{"alt":1}
,"alt":{"click":1}
,"click":{"combination":1}
,"combination":{"wire":1}
,"selected":{"clicking":1,"wire":1}
,"clicking":{"attribute":1}
,"attribute":{"button":1}
,"button":{"actions":1,"closes":1}
,"actions":{"panel":1}
,"panel":{"choosing":1}
,"choosing":{"design":1}
,"design":{"attributes":1}
,"open":{"dialog":1}
,"feature":{"description":1}
,"description":{"type":1}
,"type":{"indicates":1}
,"indicates":{"whether":1,"net":1}
,"whether":{"selected":1}
,"pinwire":{"localwire":1}
,"localwire":{"longwire":1}
,"longwire":{"net":1}
,"net":{"name":1,"routed":1,"appears":1}
,"name":{"wire":1}
,"used":{"indicates":1}
,"routed":{"along":1}
,"along":{"wire":1}
,"unused":{"net":1}
,"appears":{"field":1}
,"field":{"button":1}
,"closes":{"dialog":1}
,"help":{"opens":1,"topic":1}
,"opens":{"online":1}
,"online":{"help":1}
,"topic":{"dialog":1}
}
;Search.control.loadWordPairs(pairs);
