var pairs =
{
"exporting":{"main":1,"save":1}
,"main":{"view":1}
,"view":{"image":1,"time":1,"schematic":1}
,"image":{"epic":1,"main":1,"click":1,"file":1}
,"epic":{"allows":1,"toolbar":1}
,"allows":{"capture":1}
,"capture":{"schematic":1}
,"schematic":{"image":1}
,"time":{"export":1}
,"export":{"graphics":1,"main":1,"button":1,"image":1}
,"graphics":{"file":1}
,"file":{"bitmap":1,"(.png)":1,"dialog":1,"types":1,"name":1,"extension":1}
,"bitmap":{"(.bmp)":1}
,"(.bmp)":{"portable":1}
,"portable":{"network":1}
,"network":{"graphics":1}
,"(.png)":{"export":1}
,"click":{"export":1,"save":1}
,"button":{"epic":1}
,"toolbar":{"export":1}
,"dialog":{"box":1}
,"box":{"displays":1,"type":1,"click":1}
,"displays":{"image":1}
,"types":{"available":1}
,"available":{"exporting":1}
,"save":{"type":1}
,"type":{"box":1,"file":1}
,"name":{"appropriate":1,"text":1}
,"appropriate":{"image":1}
,"extension":{"file":1}
,"text":{"box":1}
}
;Search.control.loadWordPairs(pairs);
