var pairs =
{
"viewing":{"info":1}
,"info":{"warning":1}
,"warning":{"error":1,"messages":1}
,"error":{"messages":1,"warning":1,"windows":1}
,"messages":{"epic":1,"info":1,"following":1,"current":1,"help":1}
,"epic":{"generates":1}
,"generates":{"log":1}
,"log":{"files":1}
,"files":{"project":1,"contain":1}
,"project":{"activities":1}
,"activities":{"similar":1}
,"similar":{"diamond":1}
,"diamond":{"output":1}
,"output":{"panel":1}
,"panel":{"log":1}
,"contain":{"processing":1}
,"processing":{"information":1}
,"information":{"error":1}
,"following":{"actions":1}
,"actions":{"provided":1}
,"provided":{"info":1}
,"windows":{"copy":1}
,"copy":{"copy":1,"selected":1}
,"selected":{"content":1}
,"content":{"onto":1}
,"onto":{"clipboard":1}
,"clipboard":{"select":1}
,"select":{"select":1,"messages":1}
,"current":{"window":1}
,"window":{"clear":1,"find":1}
,"clear":{"clear":1,"messages":1}
,"find":{"text":1,"bar":1,"special":1}
,"text":{"show":1}
,"show":{"find":1}
,"bar":{"user":1}
,"user":{"find":1}
,"special":{"messages":1}
,"help":{"provide":1}
,"provide":{"message":1}
,"message":{"on-line":1}
,"on-line":{"function":1}
}
;Search.control.loadWordPairs(pairs);
