var pairs =
{
"adding":{"deleting":1,"paths":1}
,"deleting":{"paths":1}
,"paths":{"define":1,"add":1,"exist":1}
,"define":{"path":1}
,"path":{"epic":1,"preference":1,"select":1,"choose":1,"note":1,"selecting":1,"(that":1,"command":1,"attribute":1,"written":1,"remove":1,"delete":1,"object":1,"deleted":1,"commented":1,"definition":1}
,"epic":{"timing":1,"define":1,"defines":1,"enumerates":1}
,"timing":{"analysis":1,"wizard":1}
,"analysis":{"timing-driven":1}
,"timing-driven":{"operations":1}
,"operations":{"add":1}
,"add":{"path":1}
,"preference":{"applied":1,"create":1,"file":1,"defines":1,"example":1,"originally":1}
,"applied":{"design":1}
,"design":{"add":1,"saved":1,"define":1}
,"select":{"nets":1,"path":1}
,"nets":{"components":1,"endpoints":1,"implied":1}
,"components":{"included":1,"nets":1,"path":1}
,"included":{"path":1}
,"choose":{"edit":1}
,"edit":{"add":1,"delete":1}
,"note":{"following":1,"cannot":1}
,"following":{"adding":1}
,"selecting":{"two":1}
,"two":{"endpoints":1}
,"endpoints":{"path":1,"epic":1}
,"(that":{"source":1}
,"source":{"pin":1}
,"pin":{"destination":1}
,"destination":{"pin)":1}
,"pin)":{"choosing":1}
,"choosing":{"edit":1}
,"command":{"multiple":1}
,"multiple":{"paths":1}
,"exist":{"two":1}
,"defines":{"path":1}
,"enumerates":{"components":1}
,"attribute":{"timing":1}
,"wizard":{"however":1}
,"however":{"know":1}
,"know":{"intermediate":1}
,"intermediate":{"components":1}
,"implied":{"define":1}
,"create":{"add":1}
,"written":{"design\u0027s":1}
,"design\u0027s":{"preference":1}
,"file":{"next":1,"note":1}
,"next":{"time":1}
,"time":{"design":1,"save":1}
,"saved":{"delete":1}
,"delete":{"path":1,"choose":1,"click":1,"button":1,"individual":1}
,"remove":{"define":1,"preferences":1}
,"preferences":{"directly":1}
,"directly":{"depend":1}
,"depend":{"define":1}
,"example":{"maxdelay":1}
,"maxdelay":{"path":1}
,"object":{"menu":1}
,"menu":{"select":1}
,"click":{"delete":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"path":1}
,"deleted":{"next":1}
,"save":{"design":1}
,"originally":{"defined":1}
,"defined":{"path":1}
,"commented":{"preference":1}
,"cannot":{"delete":1}
,"individual":{"nets":1}
}
;Search.control.loadWordPairs(pairs);
