var pairs =
{
"object":{"definitions":1,"description":1}
,"definitions":{"following":1}
,"following":{"table":1}
,"table":{"describes":1}
,"describes":{"types":1}
,"types":{"objects":1}
,"objects":{"appear":1,"show":1,"object":1}
,"appear":{"editing":1}
,"editing":{"area":1}
,"area":{"main":1}
,"main":{"view":1}
,"view":{"preceded":1,"show":1}
,"preceded":{"icon":1}
,"icon":{"objects":1}
,"show":{"hide":1,"layers":1}
,"hide":{"layout":1,"display":1}
,"layout":{"using":1}
,"using":{"layers":1,"routing":1,"view":1}
,"layers":{"toolbar":1,"menu":1}
,"toolbar":{"view":1}
,"menu":{"view":1,"enables":1,"text":1}
,"enables":{"control":1}
,"control":{"display":1}
,"display":{"text":1,"macros":1,"labels":1}
,"text":{"labels":1,"text":1,"refers":1}
,"labels":{"highlighted":1,"identify":1,"using":1}
,"highlighted":{"objects":1}
,"description":{"net":1}
,"net":{"components":1,"(also":1,"normally":1,"pass":1,"pin":1,"pins":1}
,"components":{"connected":1,"logical":1,"components":1,"turn":1}
,"connected":{"nets":1,"finished":1}
,"nets":{"net":1}
,"(also":{"called":1}
,"called":{"signal":1}
,"signal":{"signal":1,"net)":1,"switching":1}
,"net)":{"two":1,"net":1}
,"two":{"component":1,"net":1}
,"component":{"pins":1,"placed":1}
,"pins":{"electrically":1,"(input)":1,"(those":1,"net)":1,"components":1,"associated":1,"switchboxes":1,"routing":1}
,"electrically":{"connected":1}
,"finished":{"design":1}
,"design":{"net":1,"routed":1}
,"normally":{"consists":1}
,"consists":{"driver":1}
,"driver":{"pin":1}
,"pin":{"(output":1,"certain":1,"component":1,"wires":1}
,"(output":{"tristate)":1}
,"tristate)":{"load":1}
,"load":{"pins":1}
,"(input)":{"may":1}
,"may":{"driver":1}
,"certain":{"cases":1}
,"cases":{"net":1}
,"pass":{"logic":1}
,"logic":{"block":1,"cells":1}
,"block":{"except":1}
,"except":{"case":1}
,"case":{"route-throughs":1}
,"route-throughs":{"net":1}
,"placed":{"routed":1,"components":1}
,"routed":{"connection":1,"ratsnests":1}
,"connection":{"component\u0027s":1,"local":1}
,"component\u0027s":{"net":1}
,"(those":{"pins":1}
,"logical":{"physical":1,"configurations":1,"connections":1,"elements":1,"function":1}
,"physical":{"pins":1,"connections":1}
,"associated":{"even":1,"net":1}
,"even":{"electrical":1}
,"electrical":{"connection":1}
,"local":{"wires":1,"lines":1}
,"wires":{"referred":1,"exist":1,"beyond":1,"pin":1,"short":1}
,"referred":{"local":1,"long":1}
,"lines":{"local":1,"wires":1,"used":1,"switches":1}
,"exist":{"within":1}
,"within":{"boundaries":1}
,"boundaries":{"tiles":1,"individual":1}
,"tiles":{"logic":1}
,"cells":{"typically":1}
,"typically":{"carry":1}
,"carry":{"signals":1}
,"signals":{"resources":1,"elsewhere":1,"carried":1}
,"resources":{"cell":1,"switchboxes":1,"located":1,"chip":1}
,"cell":{"employed":1,"enable":1}
,"employed":{"carry":1,"signal":1}
,"elsewhere":{"using":1}
,"routing":{"resources":1,"taken":1}
,"switchboxes":{"long":1,"switchboxes":1,"switching":1}
,"long":{"wires":1,"lines":1}
,"beyond":{"boundaries":1}
,"individual":{"cell":1}
,"enable":{"signals":1}
,"carried":{"across":1}
,"across":{"chip":1}
,"chip":{"pin":1,"site":1,"potential":1,"design":1}
,"short":{"lines":1}
,"used":{"connect":1}
,"connect":{"two":1}
,"switching":{"matrix":1,"resources":1}
,"matrix":{"resources":1}
,"located":{"junctions":1}
,"junctions":{"horizontal":1}
,"horizontal":{"vertical":1}
,"vertical":{"local":1}
,"switches":{"switches":1,"contact":1}
,"contact":{"points":1}
,"points":{"employed":1}
,"site":{"sites":1,"routes":1}
,"sites":{"vacant":1,"placed":1}
,"vacant":{"locations":1}
,"locations":{"chip":1}
,"potential":{"placement":1}
,"placement":{"components":1}
,"configurations":{"point":1}
,"point":{"site":1}
,"routes":{"routes":1,"physical":1}
,"connections":{"resources":1,"associated":1}
,"ratsnests":{"ratsnests":1,"represent":1}
,"represent":{"logical":1}
,"taken":{"place":1}
,"place":{"macros":1}
,"macros":{"macros":1,"define":1,"using":1}
,"define":{"interconnections":1}
,"interconnections":{"logical":1}
,"elements":{"designed":1}
,"designed":{"perform":1}
,"perform":{"specific":1}
,"specific":{"logical":1}
,"function":{"show":1}
,"refers":{"labels":1}
,"identify":{"sites":1}
,"turn":{"display":1}
}
;Search.control.loadWordPairs(pairs);
