var pairs =
{
"setting":{"preferences":1}
,"preferences":{"user":1,"using":1,"corresponding":1}
,"user":{"interface":1}
,"interface":{"certain":1,"following":1}
,"certain":{"net":1}
,"net":{"component":1,"net":1,"attributes":1}
,"component":{"preferences":1,"attributes":1}
,"using":{"appropriate":1}
,"appropriate":{"attribute":1}
,"attribute":{"dialog":1}
,"dialog":{"box":1,"boxes":1}
,"box":{"epic":1,"block":1,"define":1,"locate":1,"lock":1,"maxdelay":1,"maxskew":1,"prioritize":1,"prohibit":1,"longline":1}
,"epic":{"user":1}
,"following":{"table":1}
,"table":{"lists":1}
,"lists":{"preferences":1}
,"corresponding":{"attribute":1}
,"boxes":{"preference":1}
,"preference":{"accessed":1}
,"accessed":{"block":1}
,"block":{"bus":1,"net":1,"path":1}
,"bus":{"bus":1,"attributes":1,"created":1}
,"attributes":{"dialog":1}
,"path":{"path":1,"attributes":1,"created":1}
,"define":{"bus":1,"path":1}
,"created":{"edited":1}
,"edited":{"removed":1}
,"removed":{"add":1}
,"add":{"delete":1}
,"delete":{"viewed":1}
,"viewed":{"bus":1,"path":1}
,"locate":{"comp":1,"macro":1}
,"comp":{"component":1}
,"macro":{"macro":1,"attributes":1}
,"lock":{"bus":1,"comp":1,"macro":1,"net":1}
,"maxdelay":{"bus":1,"path":1}
,"maxskew":{"bus":1}
,"prioritize":{"bus":1}
,"prohibit":{"site":1}
,"site":{"site":1,"attributes":1}
,"longline":{"bus":1,"net":1}
}
;Search.control.loadWordPairs(pairs);
