var pairs =
{
"adding":{"deleting":1,"objects":1}
,"deleting":{"objects":1,"object":1}
,"objects":{"add":1,"using":1,"design":1,"become":1,"example":1,"deleting":1}
,"add":{"delete":1,"objects":1,"new":1,"component":1,"nets":1,"object":1,"define":1,"command":1,"button":1,"dialog":1}
,"delete":{"objects":1,"components":1,"object":1,"button":1}
,"using":{"actions":1}
,"actions":{"panel":1}
,"panel":{"edit":1,"add":1,"choose":1}
,"edit":{"menu":1,"delete":1}
,"menu":{"adding":1,"click":1}
,"design":{"new":1,"database":1,"need":1,"delete":1}
,"new":{"objects":1,"components":1}
,"become":{"part":1}
,"part":{"design":1}
,"database":{"add":1,"select":1}
,"components":{"nets":1}
,"nets":{"macros":1,"add":1,"existing":1,"net":1}
,"macros":{"add":1,"paths":1}
,"component":{"pins":1}
,"pins":{"existing":1,"selected":1,"macros":1}
,"existing":{"nets":1,"buses":1}
,"buses":{"define":1,"add":1,"delete":1}
,"define":{"paths":1,"certain":1,"path":1}
,"paths":{"buses":1}
,"object":{"database":1,"design":1,"add":1,"permanently":1,"select":1,"click":1}
,"select":{"appropriate":1,"object":1}
,"appropriate":{"vacant":1,"add":1}
,"vacant":{"site":1}
,"site":{"unplaced":1}
,"unplaced":{"object":1}
,"need":{"select":1}
,"certain":{"objects":1}
,"example":{"two":1}
,"two":{"pins":1}
,"selected":{"define":1}
,"path":{"choose":1}
,"choose":{"appropriate":1,"edit":1}
,"command":{"edit":1}
,"click":{"add":1,"deleting":1,"delete":1}
,"button":{"actions":1}
,"dialog":{"box":1}
,"box":{"appear":1}
,"appear":{"type":1}
,"type":{"selection":1}
,"selection":{"made":1}
,"made":{"enter":1}
,"enter":{"required":1}
,"required":{"information":1}
,"information":{"click":1}
,"permanently":{"removes":1}
,"removes":{"current":1}
,"current":{"design":1}
,"net":{"pins":1}
}
;Search.control.loadWordPairs(pairs);
