var pairs =
{
"changing":{"dsp":1,"module":1}
,"dsp":{"configuration":1,"(digital":1,"element":1,"configured":1,"design":1}
,"configuration":{"dsp":1,"port":1}
,"(digital":{"signal":1}
,"signal":{"processing)":1}
,"processing)":{"blocks":1}
,"blocks":{"used":1}
,"used":{"perform":1}
,"perform":{"high-speed":1}
,"high-speed":{"fixed-point":1}
,"fixed-point":{"functions":1}
,"functions":{"multiply":1}
,"multiply":{"sum":1}
,"sum":{"accumulate":1}
,"accumulate":{"open":1}
,"open":{"logic":1}
,"logic":{"block":1,"logic":1}
,"block":{"view":1}
,"view":{"dsp":1,"opens":1,"toolbar":1}
,"element":{"tabular":1}
,"tabular":{"view":1}
,"opens":{"enables":1}
,"enables":{"modify":1}
,"modify":{"dsp":1}
,"configured":{"within":1}
,"within":{"design":1}
,"design":{"changing":1,"elements":1}
,"module":{"configuration":1}
,"port":{"interface":1}
,"interface":{"fpga":1}
,"fpga":{"libraries":1}
,"libraries":{"manual":1}
,"manual":{"details":1}
,"details":{"attribute":1}
,"attribute":{"settings":1}
,"settings":{"individual":1}
,"individual":{"dsp":1}
,"elements":{"refer":1}
,"refer":{"following":1}
,"following":{"technical":1}
,"technical":{"notes":1}
,"notes":{"latticeecp-dsp":1}
,"latticeecp-dsp":{"sysdsp":1}
,"sysdsp":{"usage":1}
,"usage":{"(tn1057)":1,"guide":1}
,"(tn1057)":{"latticeecp2\u002Fm":1}
,"latticeecp2\u002Fm":{"sysdsp":1}
,"guide":{"(tn1107)":1,"(tn1182)":1,"(tn1140)":1}
,"(tn1107)":{"latticeecp3-dsp":1}
,"latticeecp3-dsp":{"sysdsp":1}
,"(tn1182)":{"latticexp2":1}
,"latticexp2":{"sysdsp":1}
,"(tn1140)":{"drc":1}
,"drc":{"check":1,"button":1,"results":1}
,"check":{"making":1}
,"making":{"changes":1}
,"changes":{"click":1}
,"click":{"drc":1}
,"button":{"logic":1}
,"toolbar":{"drc":1}
,"results":{"appear":1}
,"appear":{"tcl":1}
,"tcl":{"console":1}
,"console":{"editing":1}
,"editing":{"component":1}
,"component":{"logic":1}
}
;Search.control.loadWordPairs(pairs);
