var pairs =
{
"selecting":{"objects":1,"re-selecting":1}
,"objects":{"object":1,"grouped":1,"using":1,"tcl":1}
,"object":{"menu":1,"view":1,"category":1,"listed":1,"cause":1,"editing":1}
,"menu":{"object":1,"opens":1,"select":1,"click":1}
,"opens":{"default":1}
,"default":{"beginning":1}
,"beginning":{"epic":1}
,"epic":{"session":1}
,"session":{"open":1}
,"open":{"choose":1}
,"choose":{"view":1}
,"view":{"object":1,"objects":1}
,"grouped":{"lists":1}
,"lists":{"following":1}
,"following":{"types":1}
,"types":{"type":1}
,"type":{"description":1}
,"description":{"nets":1}
,"nets":{"nets":1,"design":1,"fully":1,"unrouted":1,"partially":1,"comps":1}
,"design":{"routed":1,"placed":1,"paths":1,"preferences":1,"select":1}
,"routed":{"nets":1}
,"fully":{"routed":1,"unrouted":1}
,"unrouted":{"nets":1}
,"partially":{"fully":1}
,"comps":{"components":1,"placed":1,"unplaced":1,"drop-down":1}
,"components":{"design":1,"unplaced":1,"macros":1}
,"placed":{"comps":1,"components":1,"macros":1}
,"unplaced":{"comps":1,"components":1,"macros":1}
,"macros":{"macros":1,"design":1,"placed":1,"unplaced":1,"buses":1}
,"buses":{"buses":1,"design":1}
,"paths":{"paths":1,"design":1}
,"preferences":{"associated":1,"design":1}
,"associated":{"preferences":1}
,"select":{"objects":1,"object":1}
,"using":{"object":1}
,"category":{"placed":1,"selected":1}
,"drop-down":{"menu":1}
,"click":{"name":1,"zoom":1,"object":1}
,"name":{"object":1,"example":1}
,"listed":{"within":1}
,"within":{"selected":1}
,"selected":{"category":1,"net":1,"comp":1}
,"net":{"highlighted":1,"layout":1}
,"highlighted":{"red":1}
,"red":{"main":1}
,"main":{"window":1}
,"window":{"needed":1,"wildcard":1}
,"needed":{"click":1}
,"zoom":{"fit":1,"button":1}
,"fit":{"button":1}
,"button":{"toolbar":1,"center":1,"visible":1}
,"toolbar":{"display":1}
,"display":{"complete":1}
,"complete":{"layout":1,"net":1}
,"layout":{"click":1,"selected":1}
,"center":{"complete":1}
,"comp":{"click":1}
,"visible":{"main":1}
,"wildcard":{"filter":1}
,"filter":{"option":1,"list":1}
,"option":{"bottom":1}
,"bottom":{"dialog":1}
,"dialog":{"searching":1}
,"searching":{"particular":1}
,"particular":{"element":1}
,"element":{"know":1}
,"know":{"name":1}
,"example":{"enter":1}
,"enter":{"d*and":1,"key":1}
,"d*and":{"press":1}
,"press":{"enter":1}
,"key":{"filter":1}
,"list":{"just":1}
,"just":{"elements":1}
,"elements":{"begin":1}
,"begin":{"letter":1}
,"letter":{"perform":1}
,"perform":{"action":1}
,"action":{"object":1}
,"cause":{"recorded":1}
,"recorded":{"tcl":1}
,"tcl":{"console":1}
,"console":{"hyperlink":1}
,"hyperlink":{"click":1}
,"editing":{"area":1}
,"area":{"notes":1}
,"notes":{"selecting":1}
,"re-selecting":{"objects":1}
}
;Search.control.loadWordPairs(pairs);
