var pairs =
{
"epic":{"device":1,"(editor":1,"include":1,"contains":1,"allows":1,"supports":1,"usage":1,"means":1,"manually":1,"necessary":1}
,"device":{"editor":1,"elements":1,"family":1,"programming":1}
,"editor":{"epic":1,"input":1,"interface":1,"import":1}
,"(editor":{"programmable":1}
,"programmable":{"integrated":1}
,"integrated":{"circuits)":1}
,"circuits)":{"graphical":1}
,"graphical":{"application":1}
,"application":{"viewing":1}
,"viewing":{"configuring":1}
,"configuring":{"fpgas":1}
,"fpgas":{"mapped":1,"used":1}
,"mapped":{"and\u002For":1,"physical":1}
,"and\u002For":{"placed":1,"par":1}
,"placed":{"routed":1}
,"routed":{"fpga":1}
,"fpga":{"design":1}
,"design":{"open":1,"file":1,"changes":1,"connections":1,"read":1,"quick":1,"flow":1,"translate":1,"map":1,"(.ncd)":1,"(_map.ncd)":1,"either":1,"completion":1,"preference":1}
,"open":{"design":1}
,"file":{"view":1,"run":1,"associated":1,"input":1,"placed-and-routed":1,"epic":1,"process":1}
,"view":{"edit":1,"schematic-like":1}
,"edit":{"graphically":1,"design":1}
,"graphically":{"epic":1}
,"input":{"files":1,"epic":1}
,"files":{"epic":1,"output":1,"include":1,"export":1}
,"include":{".ncd":1,"modified":1}
,".ncd":{"(native":1,".nmc":1}
,"(native":{"circuit":1}
,"circuit":{"description)":1,"macros":1}
,"description)":{".nmc":1}
,".nmc":{"(physical":1,"files":1}
,"(physical":{"macro)":1}
,"macro)":{"files":1}
,"output":{"files":1}
,"modified":{".ncd":1}
,"contains":{"advanced":1}
,"advanced":{"features":1}
,"features":{"enable":1}
,"enable":{"quickly":1}
,"quickly":{"efficiently":1}
,"efficiently":{"design":1}
,"changes":{"epic":1,"ncd":1,"made":1}
,"allows":{"apply":1}
,"apply":{"engineering":1}
,"engineering":{"change":1}
,"change":{"orders":1,"management)":1,"legal":1}
,"orders":{"(ecos)":1}
,"(ecos)":{"post-place":1}
,"post-place":{"ncd":1}
,"ncd":{"create":1,"physical":1}
,"create":{"custom":1}
,"custom":{"circuit":1}
,"macros":{"(see":1}
,"(see":{"engineering":1}
,"management)":{"gui":1}
,"gui":{"provides":1}
,"provides":{"manhattan-style":1}
,"manhattan-style":{"physical":1}
,"physical":{"floorplan":1,"connections":1,"drc":1,"preference":1,"design":1}
,"floorplan":{"view":1}
,"schematic-like":{"interface":1}
,"interface":{"modifying":1,"used":1,"main":1}
,"modifying":{"programming":1}
,"programming":{"device":1,"troubleshooting":1}
,"elements":{"simple":1}
,"simple":{"manual":1}
,"manual":{"route":1}
,"route":{"interface":1,"critical":1,"design":1}
,"used":{"add":1,"limited":1}
,"add":{"modify":1}
,"modify":{"physical":1,"design":1}
,"connections":{"editing":1,"pfu":1}
,"editing":{"actions":1}
,"actions":{"result":1}
,"result":{"legal":1}
,"legal":{"database":1,"epic":1}
,"database":{"highly":1}
,"highly":{"recommended":1}
,"recommended":{"seek":1}
,"seek":{"assistance":1}
,"assistance":{"technical":1}
,"technical":{"support":1}
,"support":{"attempting":1}
,"attempting":{"significant":1}
,"significant":{"changes":1}
,"drc":{"check":1,"(design":1}
,"check":{"available":1}
,"available":{"confirm":1}
,"confirm":{"whether":1}
,"whether":{"change":1}
,"supports":{"fpgas":1}
,"limited":{"following":1}
,"following":{"tasks":1,"steps":1}
,"tasks":{"visually":1}
,"visually":{"inspect":1}
,"inspect":{"modify":1}
,"pfu":{"logic":1}
,"logic":{"i\u002Fo":1}
,"i\u002Fo":{"types":1}
,"types":{"ebr":1}
,"ebr":{"(embedded":1}
,"(embedded":{"block":1}
,"block":{"ram)":1}
,"ram)":{"contents":1}
,"contents":{"pll":1}
,"pll":{"(phase-locked":1}
,"(phase-locked":{"loops)":1}
,"loops)":{"parameters":1}
,"parameters":{"automatically":1}
,"automatically":{"document":1}
,"document":{"changes":1}
,"made":{"manually":1}
,"manually":{"place":1,"route":1,"finish":1}
,"place":{"route":1}
,"critical":{"components":1,"component":1}
,"components":{"running":1}
,"running":{"automatic":1}
,"automatic":{"place-and-route":1}
,"place-and-route":{"tools":1}
,"tools":{"entire":1}
,"entire":{"design":1}
,"read":{"write":1}
,"write":{"undo":1}
,"undo":{"certain":1,"preferences":1}
,"certain":{"preferences":1}
,"preferences":{"physical":1,"preference":1}
,"preference":{"(.prf)":1,"files":1}
,"(.prf)":{"file":1}
,"run":{"timing":1,"hdl":1,"edited":1}
,"timing":{"analysis":1}
,"analysis":{"drc":1}
,"(design":{"rule":1}
,"rule":{"check)":1}
,"check)":{"design":1}
,"quick":{"overview":1}
,"overview":{"epic":1}
,"main":{"window":1}
,"window":{"following":1}
,"steps":{"illustrate":1}
,"illustrate":{"epic":1}
,"usage":{"diamond":1}
,"diamond":{"design":1}
,"flow":{"run":1}
,"hdl":{"design":1}
,"translate":{"design":1}
,"map":{"and\u002For":1}
,"par":{"processes":1,"epic":1,"routing":1}
,"processes":{"processes":1,"generate":1}
,"generate":{"required":1}
,"required":{"physical":1}
,"(.ncd)":{"file":1}
,"associated":{"preference":1}
,"import":{"either":1}
,"either":{"mapped":1,"placement":1}
,"(_map.ncd)":{"file":1}
,"placed-and-routed":{"physical":1}
,"means":{"edit":1}
,"placement":{"routing":1}
,"routing":{"(par)":1,"program":1}
,"(par)":{"example":1}
,"example":{"choose":1}
,"choose":{"manually":1}
,"component":{"par":1}
,"finish":{"par":1}
,"program":{"unable":1}
,"unable":{"route":1}
,"completion":{"read":1}
,"necessary":{"run":1}
,"edited":{"design":1}
,"export":{"file":1}
,"process":{"bitstream":1}
,"bitstream":{"jedec":1}
,"jedec":{"depending":1,"data":1}
,"depending":{"device":1}
,"family":{"bitstream":1}
,"data":{"device":1}
,"troubleshooting":{"design":1}
}
;Search.control.loadWordPairs(pairs);
