var pairs =
{
"net":{"attributes":1,"click":1,"name":1,"route":1,"unrouted":1,"lock":1,"cannot":1,"locks":1,"applying":1,"preference":1,"block":1,"paths":1,"bus":1,"pin":1,"source":1}
,"attributes":{"dialog":1,"button":1,"open":1}
,"dialog":{"box":1}
,"box":{"net":1,"allows":1,"feature":1,"cancel":1,"apply":1,"help":1}
,"allows":{"view":1}
,"view":{"select":1}
,"select":{"options":1}
,"options":{"selected":1,"closes":1,"without":1}
,"selected":{"net":1,"options":1,"closes":1}
,"click":{"attributes":1}
,"button":{"actions":1,"applies":1,"ignores":1}
,"actions":{"panel":1}
,"panel":{"choose":1}
,"choose":{"design":1}
,"design":{"attributes":1}
,"open":{"dialog":1}
,"feature":{"description":1}
,"description":{"net":1}
,"name":{"displays":1,"selected":1,"type":1}
,"displays":{"name":1}
,"route":{"status":1,"net":1}
,"status":{"indicates":1}
,"indicates":{"whether":1,"number":1}
,"whether":{"net":1,"object":1}
,"unrouted":{"partially":1,"deleted":1}
,"partially":{"routed":1}
,"routed":{"fully":1,"number":1}
,"fully":{"routed":1}
,"number":{"pins":1}
,"pins":{"indicates":1,"contained":1,"components":1}
,"contained":{"net":1}
,"lock":{"status":1,"net":1}
,"object":{"locked":1}
,"locked":{"unlocked":1,"net":1}
,"unlocked":{"locked":1}
,"cannot":{"unrouted":1,"unplaced":1}
,"deleted":{"pins":1,"lock":1,"block":1}
,"components":{"connected":1,"delay":1}
,"connected":{"net":1}
,"unplaced":{"swapped":1}
,"swapped":{"deleted":1}
,"locks":{"net":1}
,"applying":{"lock":1}
,"preference":{"net":1,"prevents":1,"longline":1,"applied":1,"tries":1}
,"block":{"applies":1,"net":1}
,"applies":{"block":1,"longline":1,"selected":1}
,"prevents":{"timing":1}
,"timing":{"analysis":1}
,"analysis":{"selected":1}
,"paths":{"longline":1}
,"longline":{"applies":1,"preference":1}
,"applied":{"wires":1,"bus":1}
,"wires":{"buses":1}
,"buses":{"nets":1}
,"nets":{"applied":1}
,"bus":{"longline":1,"along":1}
,"tries":{"route":1}
,"along":{"long":1}
,"long":{"line":1}
,"line":{"pin":1}
,"pin":{"list":1,"placed":1,"button":1}
,"list":{"displays":1}
,"type":{"net":1}
,"placed":{"components":1}
,"delay":{"time":1}
,"time":{"net":1}
,"source":{"pin":1}
,"closes":{"dialog":1}
,"cancel":{"button":1}
,"ignores":{"options":1}
,"apply":{"button":1}
,"without":{"closing":1}
,"closing":{"dialog":1}
,"help":{"opens":1,"topic":1}
,"opens":{"online":1}
,"online":{"help":1}
,"topic":{"dialog":1}
}
;Search.control.loadWordPairs(pairs);
