var pairs =
{
"engineering":{"change":1}
,"change":{"management":1,"orders":1,"verify":1,"design":1}
,"management":{"common":1}
,"common":{"user":1}
,"user":{"scenario":1}
,"scenario":{"minor":1}
,"minor":{"changes":1,"functional":1}
,"changes":{".ncd":1,"commonly":1,"usually":1,"netlist-level":1,"result":1,"changes":1,"affect":1,"epic":1,"pfu":1}
,".ncd":{"file":1}
,"file":{"produce":1}
,"produce":{"new":1}
,"new":{"bitstream":1}
,"bitstream":{"late":1,"generating":1,"data":1}
,"late":{"design":1}
,"design":{"cycle":1,"changes":1,"modular":1,"methods":1,"verification":1,"minimal":1,"design":1,"change":1,"performing":1}
,"cycle":{"last-minute":1}
,"last-minute":{"design":1}
,"commonly":{"referred":1}
,"referred":{"engineering":1}
,"orders":{"(ecos)":1}
,"(ecos)":{"changes":1}
,"usually":{"made":1}
,"made":{"synthesis":1}
,"synthesis":{"place-and-route":1}
,"place-and-route":{"completed":1}
,"completed":{"netlist":1}
,"netlist":{"level":1}
,"level":{"compared":1}
,"compared":{"hdl-level":1}
,"hdl-level":{"(design":1}
,"(design":{"entry)":1}
,"entry)":{"changes":1}
,"netlist-level":{"changes":1}
,"result":{"greatly":1}
,"greatly":{"reduced":1}
,"reduced":{"compilation":1}
,"compilation":{"time":1}
,"time":{"incremental":1,"invested":1}
,"incremental":{"design":1,"eco":1}
,"affect":{"few":1,"specific":1}
,"few":{"logic":1}
,"logic":{"groups":1,"editor":1,"i\u002Fo":1,"editing":1,"changing":1}
,"groups":{"design":1}
,"modular":{"fpga":1,"integration":1}
,"fpga":{"design":1}
,"methods":{"widely":1}
,"widely":{"adopted":1}
,"adopted":{"today":1}
,"today":{"significant":1}
,"significant":{"amount":1}
,"amount":{"time":1}
,"invested":{"modular":1}
,"integration":{"performance":1}
,"performance":{"maximization":1}
,"maximization":{"design":1}
,"verification":{"project":1}
,"project":{"nears":1}
,"nears":{"completion":1}
,"completion":{"vital":1}
,"vital":{"eco":1}
,"eco":{"changes":1,"editor":1}
,"specific":{"parts":1}
,"parts":{"design":1}
,"minimal":{"impact":1}
,"impact":{"unrelated":1,"change":1}
,"unrelated":{"parts":1}
,"verify":{"impact":1}
,"performing":{"timing":1}
,"timing":{"analysis":1,"simulation":1}
,"analysis":{"drc":1}
,"drc":{"check":1}
,"check":{"run":1}
,"run":{"generate":1}
,"generate":{"timing":1}
,"simulation":{"files":1}
,"files":{"bitstream":1,"two":1}
,"generating":{"processes":1}
,"processes":{"regenerate":1}
,"regenerate":{"existing":1}
,"existing":{"timing":1}
,"data":{"files":1}
,"two":{"primary":1}
,"primary":{"tools":1}
,"tools":{"making":1}
,"making":{"incremental":1}
,"epic":{"diamond":1,"exceptionally":1}
,"diamond":{"eco":1}
,"editor":{"block":1,"epic":1}
,"block":{"logic":1,"ram":1}
,"exceptionally":{"powerful":1}
,"powerful":{"tool":1}
,"tool":{"enables":1}
,"enables":{"minor":1}
,"functional":{"changes":1}
,"pfu":{"logic":1}
,"i\u002Fo":{"options":1,"types":1}
,"options":{"block":1}
,"ram":{"contents":1}
,"contents":{"pll":1,"changing":1}
,"pll":{"configuration":1}
,"configuration":{"editing":1,"changing":1}
,"editing":{"component":1,"pfu":1,"block":1}
,"component":{"logic":1}
,"changing":{"i\u002Fo":1,"pll":1,"dsp":1,"serdes":1}
,"types":{"editing":1}
,"dsp":{"configuration":1}
,"serdes":{"configuration":1}
}
;Search.control.loadWordPairs(pairs);
