var pairs =
{
"notes":{"automatically":1}
,"automatically":{"routing":1,"route":1}
,"routing":{"entire":1,"iterations":1,"ripped":1,"par":1,"done":1}
,"entire":{"design":1}
,"design":{"automatically":1,"epic":1,"routed":1,"completion":1,"within":1,"easily":1}
,"route":{"entire":1,"design":1}
,"epic":{"following":1,"existing":1,"par":1,"epic":1,"tcl":1}
,"following":{"operations":1,"true":1}
,"operations":{"performed":1}
,"performed":{"three":1}
,"three":{"iterations":1}
,"iterations":{"router":1,"perform":1,"until":1,"specified":1}
,"router":{"cost-based":1,"continues":1,"completes":1,"determines":1}
,"cost-based":{"cleanup":1}
,"cleanup":{"pass":1,"passes":1}
,"pass":{"delay-based":1}
,"delay-based":{"cleanup":1}
,"passes":{"want":1,"using":1}
,"want":{"specify":1}
,"specify":{"number":1}
,"number":{"routing":1,"passes":1,"iterations":1,"specified":1}
,"perform":{"instead":1,"iterations":1}
,"instead":{"accepting":1}
,"accepting":{"default":1}
,"default":{"value":1}
,"value":{"(three":1}
,"(three":{"iterations)":1}
,"iterations)":{"modify":1}
,"modify":{"number":1}
,"using":{"tcl":1}
,"tcl":{"command":1,"commands":1}
,"command":{"prompt":1}
,"prompt":{"router":1}
,"continues":{"perform":1}
,"until":{"following":1}
,"true":{"design":1}
,"routed":{"completion":1,"par":1}
,"completion":{"constraints":1,"meet":1}
,"constraints":{"met":1,"route":1}
,"met":{"router":1}
,"completes":{"number":1}
,"specified":{"router":1,"cannot":1}
,"determines":{"number":1}
,"cannot":{"route":1}
,"meet":{"constraints":1}
,"within":{"epic":1}
,"existing":{"routing":1}
,"ripped":{"(that":1}
,"(that":{"unrouted)":1}
,"unrouted)":{"rerouted":1}
,"rerouted":{"accommodate":1}
,"accommodate":{"new":1}
,"new":{"routing":1}
,"par":{"(place":1,"produce":1,"routes":1,"epic":1}
,"(place":{"route)":1}
,"route)":{"program":1}
,"program":{"rips":1}
,"rips":{"routes":1}
,"routes":{"necessary":1,"efficiently":1}
,"necessary":{"routing":1}
,"done":{"running":1,"epic":1}
,"running":{"par":1}
,"produce":{"different":1}
,"different":{"results":1}
,"results":{"routing":1}
,"efficiently":{"densely":1}
,"densely":{"packed":1}
,"packed":{"design":1}
,"easily":{"routed":1}
}
;Search.control.loadWordPairs(pairs);
