var pairs =
{
"adding":{"external":1}
,"external":{"pins":1,"pin":1,"nets":1,"circuitry":1,"net)":1,"multiple":1,"pin\u0027s":1}
,"pins":{"macro":1,"connect":1,"cannot":1,"want":1,"ctrl":1,"choose":1,"step":1,"click":1,"external":1,"names":1,"first":1,"type":1,"net":1,"declare":1,"symbol":1}
,"macro":{"mode":1,"components":1,"library":1,"instance":1,"add":1,"nets":1,"net":1,"schematic":1,"instantiated":1}
,"mode":{"external":1,"pins":1,"listing":1}
,"connect":{"instantiated":1}
,"instantiated":{"macro":1,"external":1}
,"components":{"design":1}
,"design":{"define":1,"macro":1}
,"define":{"external":1}
,"library":{"file":1}
,"file":{"macro":1,"editing":1,"schematic":1,"names":1,"deleting":1}
,"cannot":{"modified":1}
,"modified":{"macro":1}
,"instance":{"add":1}
,"add":{"external":1,"extpin":1,"multiple":1}
,"editing":{"area":1}
,"area":{"main":1}
,"main":{"view":1}
,"view":{"select":1}
,"select":{"component":1,"multiple":1,"type":1,"macro":1,"going":1}
,"component":{"pins":1}
,"want":{"define":1}
,"ctrl":{"click":1}
,"click":{"combination":1,"apply":1,"selected":1}
,"combination":{"select":1}
,"multiple":{"pins":1,"external":1,"output":1,"input":1}
,"choose":{"design":1}
,"extpin":{"external":1}
,"pin":{"attributes":1,"default":1,"name":1,"selected":1,"select":1,"types":1,"step":1,"proceed":1,"format":1,"numbering":1,"example":1,"external":1,"library":1}
,"attributes":{"dialog":1,"pin":1,"macro":1}
,"dialog":{"box":1}
,"box":{"opens":1,"displays":1,"external":1,"selected":1}
,"opens":{"displaying":1}
,"displaying":{"name":1}
,"name":{"location":1,"selected":1,"text":1,"assigned":1,"external":1}
,"location":{"pin":1}
,"default":{"external":1}
,"selected":{"multiple":1,"last":1,"pin":1,"pins":1}
,"step":{"dialog":1,"click":1}
,"displays":{"attributes":1}
,"last":{"desired":1}
,"desired":{"type":1}
,"type":{"new":1,"list":1,"attributes":1,"attribute":1}
,"new":{"name":1,"pin":1,"external":1,"added":1}
,"text":{"box":1}
,"list":{"pin":1}
,"types":{"selected":1}
,"apply":{"changes":1,"apply":1}
,"changes":{"close":1,"pin":1}
,"close":{"dialog":1}
,"proceed":{"next":1}
,"next":{"defined":1}
,"defined":{"external":1}
,"names":{"appear":1,"pins":1}
,"appear":{"tcl":1}
,"tcl":{"console":1}
,"console":{"add":1}
,"assigned":{"new":1}
,"format":{"$extpin_<number>":1}
,"$extpin_<number>":{"<number>":1}
,"<number>":{"number":1}
,"number":{"assigned":1}
,"numbering":{"starts":1}
,"starts":{"increases":1}
,"increases":{"new":1}
,"added":{"external":1}
,"example":{"add":1}
,"first":{"called":1}
,"called":{"$extpin_0":1,"$extpin_1":1}
,"$extpin_0":{"second":1}
,"second":{"called":1}
,"$extpin_1":{"macro":1}
,"nets":{"connected":1,"rules":1}
,"connected":{"external":1}
,"rules":{"declare":1}
,"declare":{"name":1,"output":1,"input":1}
,"net":{"output":1,"drivers":1,"input":1,"matter":1,"act":1}
,"output":{"external":1,"pins":1,"(driver)":1}
,"circuitry":{"(that":1}
,"(that":{"pins":1}
,"drivers":{"external":1}
,"net)":{"macro":1,"net":1}
,"input":{"output":1,"external":1,"pin":1,"pins":1}
,"(driver)":{"pin":1}
,"matter":{"select":1}
,"act":{"loads":1}
,"loads":{"external":1}
,"going":{"macro":1}
,"schematic":{"give":1,"ensure":1}
,"give":{"external":1}
,"symbol":{"instantiate":1}
,"instantiate":{"macro":1}
,"ensure":{"timing":1}
,"timing":{"analysis":1}
,"analysis":{"works":1}
,"works":{"correctly":1}
,"correctly":{"macro":1}
,"pin\u0027s":{"type":1}
,"attribute":{"add":1}
,"deleting":{"external":1}
,"listing":{"external":1}
}
;Search.control.loadWordPairs(pairs);
