var pairs =
{
"automatic":{"placement":1}
,"placement":{"default":1,"enabled":1,"automatically":1,"par":1,"done":1}
,"default":{"automatic":1}
,"enabled":{"epic":1}
,"epic":{"unplaced":1,"existing":1,"par":1}
,"unplaced":{"components":1}
,"components":{"place":1,"need":1,"choose":1,"macros":1,"within":1,"efficiently":1}
,"place":{"selected":1,"unplaced":1,"autoplace":1}
,"selected":{"unplaced":1}
,"need":{"manual":1}
,"manual":{"placement":1}
,"automatically":{"place":1,"placed":1}
,"choose":{"design":1}
,"design":{"place":1,"easily":1}
,"autoplace":{"design\u0027s":1,"remaining":1}
,"design\u0027s":{"unplaced":1}
,"macros":{"automatically":1}
,"placed":{"vacant":1,"routed":1}
,"vacant":{"sites":1}
,"sites":{"editing":1}
,"editing":{"area":1}
,"area":{"note":1}
,"note":{"autoplace":1}
,"remaining":{"components":1}
,"within":{"epic":1}
,"existing":{"routing":1}
,"routing":{"ripped":1}
,"ripped":{"rerouted":1}
,"rerouted":{"accommodate":1}
,"accommodate":{"new":1}
,"new":{"placement":1}
,"par":{"rips":1,"produce":1,"places":1,"epic":1}
,"rips":{"routes":1}
,"routes":{"necessary":1}
,"necessary":{"placement":1}
,"done":{"running":1,"epic":1}
,"running":{"par":1}
,"produce":{"different":1}
,"different":{"results":1}
,"results":{"placement":1}
,"places":{"components":1}
,"efficiently":{"densely":1}
,"densely":{"packed":1}
,"packed":{"design":1}
,"easily":{"placed":1}
,"routed":{"par":1}
}
;Search.control.loadWordPairs(pairs);
