var pairs =
{
"pin":{"attributes":1,"selected":1,"name":1,"resides":1,"within":1,"belongs":1,"types":1}
,"attributes":{"dialog":1,"open":1}
,"dialog":{"box":1}
,"box":{"pin":1,"feature":1,"help":1}
,"selected":{"clicking":1}
,"clicking":{"attribute":1}
,"attribute":{"button":1}
,"button":{"actions":1,"closes":1}
,"actions":{"panel":1}
,"panel":{"choosing":1}
,"choosing":{"design":1}
,"design":{"attributes":1}
,"open":{"dialog":1}
,"feature":{"description":1}
,"description":{"name":1}
,"name":{"pin":1,"site":1,"indicates":1,"typically":1,"indicate":1,"identifies":1,"component":1,"net":1}
,"site":{"name":1,"pin":1}
,"indicates":{"name":1}
,"resides":{"name":1,"type":1}
,"typically":{"appears":1}
,"appears":{"row\u002Fcolumn":1}
,"row\u002Fcolumn":{"format":1}
,"format":{"example":1}
,"example":{"r36c4":1}
,"r36c4":{"site":1}
,"indicate":{"located":1}
,"located":{"row":1}
,"row":{"column":1}
,"column":{"component":1}
,"component":{"name":1,"pin":1}
,"identifies":{"name":1}
,"type":{"specifies":1}
,"specifies":{"function":1}
,"function":{"pin":1}
,"within":{"macro":1}
,"macro":{"net":1}
,"net":{"name":1,"pin":1}
,"belongs":{"button":1}
,"closes":{"dialog":1}
,"help":{"opens":1,"topic":1}
,"opens":{"online":1}
,"online":{"help":1}
,"topic":{"dialog":1}
}
;Search.control.loadWordPairs(pairs);
