var pairs =
{
"highlighting":{"objects":1,"selecting":1}
,"objects":{"objects":1,"editing":1,"highlighted":1,"layer":1,"highlight":1,"want":1,"choose":1}
,"editing":{"area":1}
,"area":{"main":1}
,"main":{"view":1}
,"view":{"highlighted":1,"menu":1,"highlight\u002Funhighlight":1}
,"highlighted":{"using":1,"yellow":1,"color":1,"objects":1}
,"using":{"view":1}
,"menu":{"actions":1,"change":1}
,"actions":{"panel":1}
,"panel":{"default":1,"choose":1}
,"default":{"objects":1}
,"yellow":{"change":1}
,"change":{"highlight":1}
,"highlight":{"color":1,"show":1,"object":1,"select":1,"click":1,"command":1,"open":1}
,"color":{"color":1,"tab":1,"highlight":1,"changed":1,"choose":1,"box":1,"dialog":1,"basic":1,"click":1,"close":1}
,"tab":{"options":1,"click":1}
,"options":{"dialog":1}
,"dialog":{"box":1}
,"box":{"objects":1,"select":1,"highlight":1,"unhighlight":1}
,"layer":{"highlighted":1}
,"changed":{"previously":1}
,"previously":{"highlighted":1}
,"show":{"new":1}
,"new":{"color":1}
,"object":{"sure":1,"want":1,"choose":1}
,"sure":{"layers":1}
,"layers":{"displayed":1,"toolbar":1}
,"displayed":{"include":1}
,"include":{"objects":1}
,"want":{"highlight":1}
,"select":{"desired":1,"object":1,"color":1}
,"desired":{"layers":1}
,"toolbar":{"select":1}
,"click":{"hilite":1,"color":1,"click":1,"apply":1}
,"hilite":{"button":1}
,"button":{"actions":1}
,"choose":{"highlight":1,"edit":1,"view":1}
,"command":{"view":1}
,"highlight\u002Funhighlight":{"menu":1,"unhighlight":1}
,"edit":{"option":1}
,"option":{"open":1}
,"open":{"options":1,"select":1}
,"basic":{"colors":1}
,"colors":{"create":1}
,"create":{"custom":1}
,"custom":{"highlight":1}
,"apply":{"new":1}
,"close":{"options":1}
,"unhighlight":{"highlighted":1,"unhighlight":1,"select":1,"clear":1}
,"clear":{"highlighting":1}
,"selecting":{"objects":1}
}
;Search.control.loadWordPairs(pairs);
