var pairs =
{
"setting":{"preferences":1}
,"preferences":{"epic":1,"using":1,"include":1}
,"epic":{"tcl":1}
,"tcl":{"command":1,"command-line":1,"console":1,"commands":1}
,"command":{"line":1,"preferences":1,"immediately":1}
,"line":{"tcl":1}
,"command-line":{"tool":1}
,"tool":{"located":1}
,"located":{"bottom":1}
,"bottom":{"epic":1}
,"console":{"enables":1,"added":1}
,"enables":{"preferences":1}
,"using":{"eco_config":1}
,"eco_config":{"command":1}
,"include":{"attributes":1}
,"attributes":{"pll":1}
,"pll":{"memory":1}
,"memory":{"enter":1}
,"enter":{"command":1}
,"immediately":{"recorded":1}
,"recorded":{"tcl":1}
,"added":{".tcr":1}
,".tcr":{"file":1}
,"file":{"current":1}
,"current":{"session":1}
,"session":{"epic":1}
,"commands":{"section":1}
,"section":{"details":1}
,"details":{"setting":1}
}
;Search.control.loadWordPairs(pairs);
