var pairs =
{
"adding":{"deleting":1}
,"deleting":{"buses":1}
,"buses":{"bus":1,"within":1}
,"bus":{"group":1,"epic":1,"using":1,"preference":1,"remove":1,"add":1,"select":1,"choose":1,"delete":1,"object":1,"want":1,"deleted":1}
,"group":{"nets":1}
,"nets":{"define":1,"included":1}
,"define":{"buses":1,"bus":1}
,"within":{"epic":1}
,"epic":{"timing":1,"define":1}
,"timing":{"analysis":1}
,"analysis":{"timing-driven":1}
,"timing-driven":{"operations":1}
,"operations":{"add":1}
,"add":{"bus":1}
,"using":{"define":1}
,"preference":{"delete":1,"defines":1,"prioritize":1,"originally":1,"file":1}
,"delete":{"bus":1,"click":1,"button":1}
,"remove":{"define":1,"preferences":1}
,"defines":{"bus":1}
,"preferences":{"directly":1}
,"directly":{"depend":1}
,"depend":{"define":1}
,"prioritize":{"bus":1}
,"select":{"nets":1,"bus":1}
,"included":{"bus":1}
,"choose":{"edit":1}
,"edit":{"add":1,"delete":1}
,"object":{"menu":1}
,"menu":{"select":1}
,"want":{"delete":1}
,"click":{"delete":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"choose":1}
,"deleted":{"next":1}
,"next":{"time":1}
,"time":{"save":1}
,"save":{"design":1}
,"design":{"define":1}
,"originally":{"defined":1}
,"defined":{"path":1}
,"path":{"commented":1}
,"commented":{"preference":1}
}
;Search.control.loadWordPairs(pairs);
