var pairs =
{
"add":{"macro":1}
,"macro":{"dialog":1,"allows":1,"current":1,"name":1,"instance":1,"added":1,"updated":1,"library":1,"macro":1,"mode":1,"design":1}
,"dialog":{"box":1}
,"box":{"add":1,"accessed":1,"change":1,"cancel":1,"help":1,"adding":1}
,"accessed":{"choosing":1}
,"choosing":{"edit":1}
,"edit":{"add":1}
,"allows":{"add":1,"specify":1,"navigate":1}
,"current":{"design":1}
,"design":{"feature":1,"macro":1,"closes":1,"mode":1}
,"feature":{"description":1}
,"description":{"macro":1}
,"name":{"specifies":1,"macro":1,"name":1,"assigned":1,"appears":1,"names":1,"change":1}
,"specifies":{"name":1}
,"instance":{"enter":1}
,"enter":{"name":1}
,"assigned":{"automatically":1}
,"automatically":{"macro":1,"reflect":1}
,"added":{"design":1}
,"appears":{"attributes":1}
,"attributes":{"dialog":1}
,"change":{"macro":1}
,"names":{"components":1}
,"components":{"nets":1}
,"nets":{"external":1}
,"external":{"pins":1}
,"pins":{"part":1}
,"part":{"macro":1}
,"updated":{"automatically":1}
,"reflect":{"name":1}
,"library":{"file":1,"filename":1}
,"file":{"allows":1,"button":1}
,"specify":{"macro":1}
,"filename":{"associated":1}
,"associated":{"browse":1}
,"browse":{"button":1}
,"button":{"allows":1,"applies":1,"ignores":1}
,"navigate":{"existing":1}
,"existing":{".nmc":1}
,".nmc":{"file":1}
,"applies":{"given":1}
,"given":{"options":1}
,"options":{"current":1,"may":1}
,"closes":{"dialog":1}
,"cancel":{"button":1}
,"ignores":{"options":1}
,"may":{"specified":1}
,"specified":{"closes":1}
,"help":{"opens":1,"topic":1}
,"opens":{"online":1}
,"online":{"help":1}
,"topic":{"dialog":1}
,"adding":{"macro":1}
,"mode":{"adding":1}
}
;Search.control.loadWordPairs(pairs);
