var pairs =
{
"saving":{"macro":1}
,"macro":{"library":1,"save":1,"dialog":1,"filename":1,"files":1}
,"library":{"file":1}
,"file":{"time":1,"working":1,"cannot":1,"along":1,"even":1,"edited":1,"save":1,"choose":1,"written":1,"file":1,"name":1,"later":1,"saved":1,"original":1,"note":1,"placed":1}
,"time":{"during":1}
,"during":{"epic":1}
,"epic":{"session":1,"window":1}
,"session":{"save":1}
,"save":{"macro":1,"preference":1,".nmc":1,"current":1,"dialog":1,"design":1,"exit":1}
,"working":{"save":1,"directory":1}
,"cannot":{"save":1}
,"preference":{"file":1}
,"along":{".nmc":1}
,".nmc":{"file":1,"extension":1}
,"even":{"preferences":1}
,"preferences":{"created":1,"lost":1}
,"created":{"macro":1}
,"edited":{"preferences":1}
,"lost":{"save":1}
,"current":{"macro":1,"working":1}
,"choose":{"file":1}
,"written":{"disk":1}
,"disk":{"save":1}
,"name":{"choose":1,"specified":1,"new":1,"enter":1,"file":1}
,"dialog":{"box":1}
,"box":{"appears":1,"enter":1,"closes":1}
,"appears":{"save":1}
,"enter":{"macro":1,"full":1}
,"filename":{"save":1}
,"design":{"epic":1,"saved":1}
,"window":{"browse":1}
,"browse":{"button":1}
,"button":{"click":1}
,"click":{"dialog":1}
,"closes":{"design":1}
,"saved":{"macro":1,"new":1}
,"specified":{"title":1}
,"title":{"bar":1}
,"bar":{"changes":1}
,"changes":{"show":1}
,"show":{"name":1}
,"new":{"file":1,"macro":1}
,"later":{"save":1}
,"exit":{"file":1}
,"original":{"file":1}
,"note":{"macro":1}
,"files":{".nmc":1}
,"extension":{"add":1,".nmc":1,"automatically":1}
,"add":{"extension":1}
,"automatically":{"appended":1}
,"appended":{"file":1}
,"full":{"path":1}
,"path":{"name":1}
,"placed":{"current":1}
}
;Search.control.loadWordPairs(pairs);
