var pairs =
{
"manual":{"routing":1,"route":1}
,"routing":{"manual":1,"allows":1,"select":1,"resources":1}
,"allows":{"specify":1}
,"specify":{"path":1}
,"path":{"signal":1,"specified":1}
,"signal":{"routing":1}
,"select":{"net":1,"unused":1,"three":1}
,"net":{"pins":1,"route":1}
,"pins":{"pin":1,"placed":1,"together":1,"want":1}
,"pin":{"wires":1}
,"wires":{"connected":1,"local":1}
,"connected":{"routing":1}
,"resources":{"used":1}
,"used":{"(for":1}
,"(for":{"example":1}
,"example":{"long":1,"select":1}
,"long":{"lines":1}
,"lines":{"local":1,"long":1,"route":1}
,"local":{"lines)":1,"lines":1}
,"lines)":{"system":1}
,"system":{"routes":1}
,"routes":{"path":1}
,"specified":{"part":1,"order":1}
,"part":{"manual":1}
,"unused":{"pins":1,"component":1}
,"placed":{"components":1}
,"components":{"route":1}
,"route":{"pins":1,"existing":1,"manually":1,"segments":1,"objects":1,"route":1,"choose":1,"manual":1,"click":1,"button":1}
,"together":{"form":1}
,"form":{"new":1}
,"new":{"net":1}
,"existing":{"net":1}
,"manually":{"select":1}
,"segments":{"unused":1}
,"component":{"pins":1}
,"want":{"route":1,"routed":1}
,"objects":{"selected":1,"order":1,"routed":1}
,"selected":{"order":1,"object":1,"objects":1}
,"order":{"want":1,"indicating":1,"notes":1}
,"routed":{"keep":1,"one-by-one":1,"specified":1}
,"keep":{"mind":1}
,"mind":{"connections":1}
,"connections":{"routed":1}
,"one-by-one":{"selected":1}
,"object":{"next":1,"example":1}
,"next":{"selected":1}
,"three":{"objects":1}
,"indicating":{"want":1}
,"choose":{"design":1}
,"design":{"route":1}
,"click":{"route":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"selected":1}
,"notes":{"manual":1}
}
;Search.control.loadWordPairs(pairs);
