var pairs =
{
"adding":{"macro":1}
,"macro":{"macro":1,"mode":1,"instance":1,"library":1,"design":1,"epic":1,"elements":1}
,"mode":{"macro":1,"design":1,"topic":1,"procedural":1}
,"instance":{"added":1,"macro":1,"unbound":1}
,"added":{"macro":1,"separate":1}
,"library":{"file":1}
,"file":{"procedure":1}
,"procedure":{"adding":1}
,"design":{"mode":1}
,"topic":{"adding":1}
,"procedural":{"steps":1}
,"steps":{"add":1}
,"add":{"macro":1}
,"epic":{"macro":1}
,"unbound":{"components":1}
,"components":{"nets":1}
,"nets":{"instance":1,"macro":1,"added":1}
,"separate":{"components":1}
,"elements":{"instantiation":1}
,"instantiation":{"indication":1}
,"indication":{"components":1}
}
;Search.control.loadWordPairs(pairs);
