var pairs =
{
"components":{"attributes":1,"feature":1,"(that":1,"placed":1,"sites":1,"pre-placed":1}
,"attributes":{"dialog":1,"pfu":1}
,"dialog":{"box":1}
,"box":{"component":1,"modify":1,"cancel":1,"apply":1,"help":1}
,"component":{"selected":1,"logic":1,"locate":1,"specified":1,"site":1,"locks":1,"locked":1,"cannot":1,"clearing":1}
,"selected":{"clicking":1,"component":1,"applies":1,"cannot":1,"options":1}
,"clicking":{"attribute":1}
,"attribute":{"button":1,"open":1}
,"button":{"actions":1,"applies":1,"ignores":1}
,"actions":{"panel":1}
,"panel":{"choosing":1}
,"choosing":{"design":1}
,"design":{"attribute":1,"lock":1}
,"open":{"dialog":1}
,"modify":{"attributes":1}
,"pfu":{"pio":1}
,"pio":{"components":1}
,"feature":{"description":1}
,"description":{"name":1}
,"name":{"displays":1,"selected":1}
,"displays":{"name":1,"read-only":1}
,"logic":{"strings":1}
,"strings":{"displays":1,"selected":1}
,"read-only":{"list":1}
,"list":{"current":1}
,"current":{"logic":1}
,"locate":{"selected":1,"preference":1}
,"applies":{"locate":1,"lock":1,"design":1,"selected":1}
,"preference":{"selected":1,"places":1,"currently":1}
,"places":{"component":1,"macro\u0027s":1}
,"specified":{"site":1}
,"site":{"locks":1,"macro":1,"places":1}
,"locks":{"component":1,"placed":1}
,"macro":{"locate":1,"locked":1,"components":1,"cannot":1}
,"macro\u0027s":{"reference":1,"pre-placed":1,"library":1}
,"reference":{"component":1}
,"pre-placed":{"components":1,"(i.e":1}
,"(that":{"components":1}
,"placed":{"macro\u0027s":1,"components":1}
,"library":{"file)":1}
,"file)":{"sites":1,"locked":1}
,"sites":{"relative":1,"lock":1}
,"relative":{"reference":1}
,"lock":{"selected":1,"placement":1,"option":1}
,"placement":{"preference":1}
,"locked":{"component":1,"macro":1}
,"cannot":{"unplaced":1,"unlock":1}
,"unplaced":{"unrouted":1,"button":1}
,"unrouted":{"moved":1}
,"moved":{"swapped":1}
,"swapped":{"deleted":1}
,"deleted":{"lock":1}
,"currently":{"applies":1}
,"option":{"already":1}
,"already":{"selected":1}
,"unlock":{"component":1}
,"clearing":{"selection":1}
,"selection":{"macro":1}
,"(i.e":{"components":1}
,"options":{"closes":1,"without":1}
,"closes":{"dialog":1}
,"cancel":{"button":1}
,"ignores":{"selected":1}
,"apply":{"button":1}
,"without":{"closing":1}
,"closing":{"dialog":1}
,"help":{"opens":1,"topic":1}
,"opens":{"online":1}
,"online":{"help":1}
,"topic":{"dialog":1}
}
;Search.control.loadWordPairs(pairs);
