var pairs =
{
"unplacing":{"components":1}
,"components":{"macros":1,"viewed":1,"select":1,"object":1,"unplaced":1,"cannot":1}
,"macros":{"unplace":1,"current":1,"design":1}
,"unplace":{"command":1,"placed":1,"selected":1}
,"command":{"removes":1}
,"removes":{"selected":1}
,"selected":{"components":1}
,"current":{"sites":1}
,"sites":{"unplace":1}
,"placed":{"components":1}
,"design":{"list":1,"place":1,"choose":1,"except":1}
,"list":{"unplaced":1}
,"unplaced":{"components":1,"component":1,"comps":1,"unplace":1}
,"viewed":{"objects":1}
,"objects":{"menu":1}
,"menu":{"software":1,"editing":1,"note":1}
,"software":{"unplaces":1}
,"unplaces":{"component":1}
,"component":{"unroutes":1,"pin":1,"unplace":1,"names":1}
,"unroutes":{"component":1}
,"pin":{"component":1}
,"select":{"desired":1}
,"desired":{"components":1}
,"object":{"menu":1}
,"editing":{"area":1}
,"area":{"main":1}
,"main":{"view":1}
,"view":{"choose":1}
,"choose":{"design":1}
,"place":{"unplace":1}
,"names":{"displayed":1}
,"displayed":{"list":1}
,"comps":{"object":1}
,"note":{"locked":1}
,"locked":{"components":1,"ones":1}
,"cannot":{"unplaced":1}
,"except":{"locked":1}
,"ones":{"unplaced":1}
}
;Search.control.loadWordPairs(pairs);
