var pairs =
{
"routing":{"unrouting":1,"select":1,"guidelines":1,"notes":1,"selected":1}
,"unrouting":{"macros":1,"components":1,"notes":1}
,"macros":{"design":1,"similar":1,"section":1}
,"design":{"mode":1}
,"mode":{"routing":1,"select":1,"automatically":1}
,"similar":{"routing":1}
,"components":{"routing":1}
,"notes":{"routing":1,"automatically":1}
,"select":{"macro":1,"placed":1}
,"macro":{"automatic":1,"pre-routed":1,"placed":1,"external":1,"routing":1}
,"automatic":{"routing":1}
,"placed":{"macros":1,"cannot":1}
,"section":{"object":1}
,"object":{"menu":1}
,"menu":{"place":1}
,"place":{"macro":1}
,"pre-routed":{"connections":1,"automatically":1}
,"connections":{"exist":1,"design":1}
,"exist":{"macro\u0027s":1}
,"macro\u0027s":{"library":1}
,"library":{"file":1}
,"file":{"automatically":1}
,"automatically":{"routed":1,"route":1,"routing":1}
,"routed":{"macro":1,"nets":1}
,"cannot":{"unroute":1}
,"unroute":{"connections":1}
,"route":{"macro":1}
,"external":{"pin":1}
,"pin":{"connected":1}
,"connected":{"net":1}
,"net":{"routed":1}
,"nets":{"pre-routed":1}
,"guidelines":{"automatic":1}
,"selected":{"objects":1}
}
;Search.control.loadWordPairs(pairs);
