var pairs =
{
"notes":{"manual":1}
,"manual":{"routing":1}
,"routing":{"notes":1,"objects":1,"manual":1,"routes":1,"locked":1}
,"objects":{"selected":1,"specified":1,"routed":1,"route":1}
,"selected":{"part":1}
,"part":{"net":1}
,"net":{"example":1,"pin":1,"long":1,"connection":1,"routing":1,"remain":1,"unlocked":1,"manual":1}
,"example":{"cannot":1}
,"cannot":{"select":1,"mix":1}
,"select":{"net":1,"unused":1}
,"pin":{"part":1,"pin":1,"wire":1,"added":1}
,"long":{"line":1}
,"line":{"part":1}
,"connection":{"exists":1,"routed":1,"net":1}
,"exists":{"objects":1}
,"specified":{"connection":1}
,"routed":{"error":1,"together":1,"nets":1}
,"error":{"message":1}
,"message":{"appear":1}
,"appear":{"tcl":1}
,"tcl":{"console":1}
,"console":{"specify":1}
,"specify":{"objects":1,"unrouted":1}
,"together":{"account":1}
,"account":{"direction":1}
,"direction":{"current":1}
,"current":{"flow":1}
,"flow":{"switches":1}
,"switches":{"connecting":1}
,"connecting":{"two":1}
,"two":{"objects":1,"directions":1}
,"route":{"source":1,"command":1,"program)":1}
,"source":{"load":1,"cannot":1}
,"load":{"load":1,"source":1}
,"mix":{"two":1}
,"directions":{"route":1}
,"command":{"run":1,"used":1}
,"run":{"select":1,"par":1}
,"unused":{"net":1}
,"wire":{"connection":1}
,"added":{"net":1}
,"routes":{"connections":1}
,"connections":{"specify":1,"applicable":1}
,"unrouted":{"connections":1,"partially":1}
,"applicable":{"net":1}
,"remain":{"unrouted":1}
,"partially":{"routed":1}
,"nets":{"terminate":1}
,"terminate":{"pins":1}
,"pins":{"(antennas)":1}
,"(antennas)":{"ripped":1}
,"ripped":{"auto":1}
,"auto":{"route":1}
,"used":{"unless":1}
,"unless":{"lock":1}
,"lock":{"down":1,"status":1}
,"down":{"locking":1}
,"locking":{"net":1}
,"unlocked":{"antennas":1,"depending":1}
,"antennas":{"removed":1}
,"removed":{"run":1}
,"par":{"(the":1}
,"(the":{"place":1}
,"place":{"route":1}
,"program)":{"design":1}
,"design":{"file":1}
,"file":{"segment":1}
,"segment":{"added":1}
,"locked":{"unlocked":1}
,"depending":{"net\u0027s":1}
,"net\u0027s":{"lock":1}
}
;Search.control.loadWordPairs(pairs);
