var pairs =
{
"macro":{"routing":1,"support":1,"general":1,"library":1,"requires":1,"specific":1,"definition":1,"eventually":1,"less":1,"instance":1,"remain":1,"during":1,"instantiated":1,"device":1,"components":1,"connections":1,"includes":1,"instances":1,"macro":1,"uses":1}
,"routing":{"guidelines":1,"design":1,"macro":1,"however":1,"nets":1,"already":1,"placed":1,"i\u002Fo":1}
,"guidelines":{"epic":1,"using":1}
,"epic":{"supports":1,"macro":1}
,"supports":{"macros":1}
,"macros":{"size":1,"avoid":1}
,"size":{"amount":1}
,"amount":{"routing":1,"time":1}
,"design":{"improved":1,"add":1,"macro":1,"pre-routing":1,"routing":1}
,"improved":{"macro":1}
,"support":{"provides":1}
,"provides":{"power":1}
,"power":{"flexibility":1}
,"flexibility":{"adhere":1}
,"adhere":{"following":1}
,"following":{"guidelines":1}
,"using":{"routing":1,"locate":1,"hard":1,"prohibit":1}
,"general":{"preferable":1,"route":1}
,"preferable":{"route":1}
,"route":{"connections":1,"nets":1,"incur":1,"clock":1}
,"connections":{"macro":1,"wires":1}
,"library":{"files":1,"file":1}
,"files":{"reason":1,"unless":1,"locate":1}
,"reason":{"routing":1}
,"requires":{"extra":1,"routing":1}
,"extra":{"processing":1}
,"processing":{"during":1,"non-located":1}
,"during":{"placement":1,"place":1}
,"placement":{"stage":1,"routing":1,"general":1}
,"stage":{"design":1}
,"add":{"considerably":1}
,"considerably":{"amount":1}
,"time":{"required":1}
,"required":{"placement":1,"sites":1,"macro":1}
,"however":{"sense":1}
,"sense":{"include":1}
,"include":{"routing":1}
,"file":{"nets":1,"design":1,"route":1,"macro":1,"prohibits":1,"contains":1,"large":1,"instance":1,"attempting":1}
,"nets":{"critical":1,"macro":1,"hand-routed":1,"routed":1,"nets":1,"3-state":1,"external":1,"integrated":1,"build":1,"requires":1}
,"critical":{"timing":1}
,"timing":{"nets":1,"requirements":1,"demands":1}
,"specific":{"timing":1}
,"requirements":{"especially":1}
,"especially":{"nets":1,"important":1}
,"hand-routed":{"meet":1}
,"meet":{"tight":1}
,"tight":{"delay":1}
,"delay":{"constraints":1}
,"constraints":{"good":1}
,"good":{"candidate":1}
,"candidate":{"nets":1}
,"routed":{"macro":1,"efficiently":1,"nets":1}
,"definition":{"file":1}
,"eventually":{"instantiated":1}
,"instantiated":{"fast":1,"necessary":1}
,"fast":{"routing":1}
,"less":{"stringent":1}
,"stringent":{"timing":1}
,"demands":{"left":1}
,"left":{"unrouted":1}
,"unrouted":{"macro":1}
,"instance":{"located":1,"legally":1,"routing":1,"macro":1,"location":1,"placed":1}
,"located":{"using":1,"macro":1}
,"locate":{"preference":1,"macro":1,"preferences":1}
,"preference":{"located":1,"par":1}
,"remain":{"untouched":1,"unused":1}
,"untouched":{"placer":1}
,"placer":{"during":1}
,"place":{"route":1}
,"incur":{"extra":1}
,"non-located":{"routed":1}
,"clock":{"nets":1}
,"3-state":{"nets":1}
,"external":{"nets":1}
,"integrated":{"overall":1}
,"overall":{"structure":1}
,"structure":{"design":1}
,"pre-routing":{"nets":1}
,"prohibits":{"nets":1}
,"efficiently":{"design":1}
,"necessary":{"create":1}
,"create":{"macro":1}
,"contains":{"routed":1,"route-throughs":1,"i\u002Fo":1}
,"build":{"macro":1}
,"device":{"location":1,"even":1,"macro":1,"placed":1}
,"location":{"used":1,"device":1,"connection":1,"violate":1,"(s)":1}
,"used":{"especially":1,"net":1,"macro":1,"route-through":1}
,"important":{"macro":1}
,"large":{"contains":1}
,"route-throughs":{"slics":1,"sure":1}
,"slics":{"contains":1}
,"i\u002Fo":{"cells":1}
,"cells":{"several":1,"internal":1,"along":1}
,"several":{"situations":1}
,"situations":{"routed":1}
,"legally":{"placed":1}
,"placed":{"given":1,"location":1,"i\u002Fo":1,"macro":1,"summary":1}
,"given":{"location":1}
,"even":{"required":1}
,"sites":{"macro":1}
,"components":{"available":1}
,"available":{"wire":1}
,"wire":{"required":1}
,"already":{"used":1}
,"net":{"design":1}
,"wires":{"exist":1,"identical":1}
,"exist":{"area":1}
,"area":{"device":1}
,"connection":{"pattern":1}
,"pattern":{"wires":1,"used":1}
,"identical":{"connection":1}
,"includes":{"routing":1}
,"internal":{"logic":1}
,"logic":{"blocks":1}
,"blocks":{"placed":1}
,"along":{"edge":1}
,"edge":{"device":1}
,"attempting":{"hand-place":1}
,"hand-place":{"macro":1}
,"violate":{"rules":1}
,"rules":{"cause":1}
,"cause":{"error":1}
,"error":{"generated":1}
,"generated":{"epic":1}
,"summary":{"guidelines":1}
,"hard":{"macros":1}
,"avoid":{"routing":1}
,"unless":{"timing":1}
,"instances":{"locate":1}
,"preferences":{"known":1}
,"known":{"valid":1}
,"valid":{"locations":1}
,"locations":{"macro":1}
,"uses":{"slic":1}
,"slic":{"route-throughs":1,"location":1}
,"sure":{"slic":1}
,"(s)":{"used":1}
,"route-through":{"remain":1}
,"unused":{"top-level":1}
,"top-level":{"circuit":1}
,"circuit":{"using":1}
,"prohibit":{"preference":1}
}
;Search.control.loadWordPairs(pairs);
