var pairs =
{
"selecting":{"objects":1,"selecting":1}
,"objects":{"multiple":1,"object":1,"tcl":1,"unplaced":1,"selected":1,"using":1,"select":1}
,"multiple":{"ways":1,"objects":1}
,"ways":{"select":1}
,"select":{"object":1,"editing":1,"single":1,"category":1,"desired":1,"hyperlink":1,"used":1,"multiple":1,"appropriate":1}
,"object":{"epic":1,"editing":1,"menu":1,"name":1,"click":1,"previously":1,"perform":1,"changes":1,"used":1}
,"epic":{"order":1}
,"order":{"perform":1}
,"perform":{"actions":1,"action":1}
,"actions":{"however":1}
,"however":{"select":1}
,"editing":{"area":1}
,"area":{"main":1,"select":1,"click":1,"selecting":1,"searching":1}
,"main":{"view":1}
,"view":{"using":1,"selected":1,"object\u0027s":1}
,"using":{"left":1,"wire":1,"ctrl":1}
,"left":{"mouse":1}
,"mouse":{"button":1}
,"button":{"click":1,"perform":1}
,"click":{"desired":1,"combination":1,"zoom":1,"editing":1}
,"desired":{"object":1}
,"single":{"wire":1}
,"wire":{"net":1,"(pin":1,"long":1,"displayed":1}
,"net":{"alt":1,"using":1,"pin)":1,"pin":1,"source":1}
,"alt":{"click":1}
,"combination":{"object":1,"wildcard":1}
,"menu":{"select":1,"tcl":1,"types":1,"objects":1}
,"category":{"drop-down":1}
,"drop-down":{"menu":1}
,"name":{"enlarge":1,"displayed":1,"net":1,"name":1}
,"enlarge":{"object":1}
,"zoom":{"button":1}
,"action":{"object":1,"found":1,"performing":1}
,"tcl":{"console":1}
,"console":{"select":1,"find":1,"hyperlinked":1,"shows":1}
,"hyperlink":{"object":1}
,"previously":{"selected":1}
,"selected":{"re-selecting":1,"object":1,"include":1,"main":1}
,"re-selecting":{"objects":1}
,"find":{"dialog":1}
,"dialog":{"box":1}
,"box":{"search":1,"pins":1}
,"search":{"simultaneously":1}
,"simultaneously":{"select":1}
,"found":{"object":1}
,"searching":{"objects":1}
,"unplaced":{"components":1}
,"components":{"displayed":1,"component":1}
,"displayed":{"main":1,"tcl":1,"select":1}
,"types":{"objects":1}
,"include":{"sites":1}
,"sites":{"site":1}
,"site":{"pins":1}
,"pins":{"components":1,"nets":1,"wires":1}
,"component":{"pins":1,"pin":1}
,"nets":{"paths":1}
,"paths":{"buses":1}
,"buses":{"macros":1}
,"macros":{"switch":1}
,"switch":{"box":1}
,"wires":{"(pin":1,"long":1}
,"(pin":{"wires":1,"wire":1}
,"long":{"lines":1,"line":1}
,"lines":{"local":1,"select":1}
,"local":{"lines)":1,"line)":1}
,"lines)":{"route":1}
,"route":{"lines":1}
,"changes":{"color":1}
,"color":{"indicate":1}
,"indicate":{"selection":1}
,"selection":{"selected":1}
,"object\u0027s":{"type":1}
,"type":{"name":1}
,"hyperlinked":{"quickly":1}
,"quickly":{"return":1}
,"return":{"later":1}
,"later":{"object":1}
,"used":{"wire":1,"component":1}
,"line":{"local":1}
,"line)":{"name":1}
,"pin":{"(or":1,"name":1,"belongs":1,"select":1}
,"(or":{"net":1}
,"pin)":{"tcl":1}
,"shows":{"pin":1}
,"belongs":{"delay":1}
,"delay":{"time":1}
,"time":{"net":1}
,"source":{"pin":1}
,"ctrl":{"click":1}
,"wildcard":{"filter":1}
,"filter":{"option":1}
,"option":{"object":1}
,"appropriate":{"action":1}
,"performing":{"notes":1}
,"notes":{"selecting":1}
}
;Search.control.loadWordPairs(pairs);
