var pairs =
{
"notes":{"signal":1}
,"signal":{"probing":1,"once":1,"occupying":1,"probe":1}
,"probing":{"multiple":1,"epic":1,"configuration":1,"reopen":1}
,"multiple":{"signal":1}
,"epic":{"begins":1,"find":1,"runs":1,"bitstream":1}
,"begins":{"placing":1}
,"placing":{"signals":1}
,"signals":{"order":1,"slot":1}
,"order":{"received":1}
,"received":{"available":1}
,"available":{"sites":1,"i\u002Fo":1,"viewable":1}
,"sites":{"site":1,"epic":1,"spreadsheet":1,"elsewhere":1}
,"site":{"occupied":1,"continue":1,"reflected":1}
,"occupied":{"(e.g":1}
,"(e.g":{"dropping":1}
,"dropping":{"three":1}
,"three":{"signals":1}
,"slot":{"two":1}
,"two":{"existing":1}
,"existing":{"probes)":1,"probes":1}
,"probes)":{"epic":1}
,"find":{"next":1}
,"next":{"available":1}
,"i\u002Fo":{"site":1,"starting":1}
,"continue":{"long":1}
,"long":{"available":1}
,"runs":{"available":1}
,"viewable":{"sites":1}
,"spreadsheet":{"listing":1}
,"listing":{"dialog":1}
,"dialog":{"box":1}
,"box":{"despite":1,"appear":1,"changed":1,"until":1,"signal":1}
,"despite":{"available":1}
,"elsewhere":{"wrap":1}
,"wrap":{"around":1,"possible":1}
,"around":{"top":1}
,"top":{"next":1,"dialog":1}
,"starting":{"top":1}
,"appear":{"notifying":1}
,"notifying":{"wrap":1}
,"possible":{"probe":1}
,"probe":{"single":1,"components":1,"configuration":1}
,"single":{"signal":1}
,"once":{"route":1}
,"route":{"external":1}
,"external":{"pin":1}
,"pin":{"parameters":1}
,"parameters":{"changed":1}
,"changed":{"signal":1,"editing":1}
,"configuration":{"dialog":1}
,"editing":{"area":1}
,"area":{"main":1,"deleting":1}
,"main":{"view":1}
,"view":{"however":1}
,"however":{"actions":1}
,"actions":{"made":1}
,"made":{"editing":1}
,"deleting":{"signal":1}
,"occupying":{"i\u002Fo":1}
,"reflected":{"dialog":1}
,"until":{"click":1}
,"click":{"refresh":1}
,"refresh":{"button":1}
,"button":{"probes":1}
,"probes":{"stored":1,"created":1,"recognizable":1}
,"stored":{"design":1}
,"design":{"design":1,"saved":1,"delete":1,"existing":1}
,"saved":{"epic":1,"special":1}
,"bitstream":{"data":1}
,"data":{"file":1}
,"file":{"generated":1}
,"generated":{"probe":1}
,"components":{"saved":1}
,"special":{"attribute":1}
,"attribute":{"signalprobe":1}
,"signalprobe":{"finish":1}
,"finish":{"probing":1}
,"reopen":{"design":1}
,"delete":{"probes":1}
,"created":{"reopen":1}
,"recognizable":{"grid":1}
,"grid":{"display":1}
,"display":{"signal":1}
}
;Search.control.loadWordPairs(pairs);
