var pairs =
{
"editing":{"block":1,"component":1}
,"block":{"ram":1,"ram)":1,"view":1}
,"ram":{"contents":1,"cell":1,"rom":1}
,"contents":{"ebr":1}
,"ebr":{"(embedded":1,"elements":1,"port":1}
,"(embedded":{"block":1}
,"ram)":{"element":1}
,"element":{"ram":1}
,"cell":{"fpga":1}
,"fpga":{"configured":1,"libraries":1}
,"configured":{"ram":1}
,"rom":{"fifo":1}
,"fifo":{"cams":1}
,"cams":{"forth":1}
,"forth":{"open":1}
,"open":{"logic":1}
,"logic":{"block":1,"logic":1}
,"view":{"ebr":1,"displayed":1,"toolbar":1}
,"elements":{"tabular":1,"enable\u002Fdisable":1,"details":1}
,"tabular":{"view":1}
,"displayed":{"allows":1}
,"allows":{"change":1}
,"change":{"attributes":1,"memory":1}
,"attributes":{"data_width":1}
,"data_width":{"(data":1}
,"(data":{"word":1}
,"word":{"width)":1}
,"width)":{"regmode":1}
,"regmode":{"(register":1}
,"(register":{"mode":1}
,"mode":{"pipelining)":1}
,"pipelining)":{"resetmode":1}
,"resetmode":{"(reset":1}
,"(reset":{"type)":1}
,"type)":{"csdecode":1}
,"csdecode":{"values":1}
,"values":{"ebr":1,"(initval)":1,"format":1}
,"enable\u002Fdisable":{"global":1}
,"global":{"set\u002Freset":1}
,"set\u002Freset":{"(gsr)":1}
,"(gsr)":{"change":1}
,"memory":{"initialization":1,"usage":1,"ports":1}
,"initialization":{"values":1}
,"(initval)":{"content":1}
,"content":{"memory":1}
,"format":{"initval":1}
,"initval":{"constraint":1}
,"constraint":{".prf":1}
,".prf":{"file":1}
,"file":{"fpga":1}
,"libraries":{"manual":1}
,"manual":{"details":1}
,"details":{"attribute":1,"ebr":1}
,"attribute":{"settings":1,"definition":1}
,"settings":{"individual":1}
,"individual":{"ebr":1}
,"port":{"definition":1}
,"definition":{"attribute":1,"usage":1}
,"usage":{"refer":1,"guide":1}
,"refer":{"following":1}
,"following":{"technical":1}
,"technical":{"notes":1}
,"notes":{"latticeecp2\u002Fm":1}
,"latticeecp2\u002Fm":{"memory":1}
,"guide":{"(tn1104)":1,"(tn1179)":1,"latticesc":1,"latticeecp\u002Fec":1,"machxo":1,"machxo2":1}
,"(tn1104)":{"latticeecp3":1}
,"latticeecp3":{"memory":1}
,"(tn1179)":{"on-chip":1}
,"on-chip":{"memory":1}
,"latticesc":{"devices":1}
,"devices":{"(tn1094)":1,"(tn1051)":1,"(tn1092)":1,"(tn1201)":1}
,"(tn1094)":{"memory":1}
,"latticeecp\u002Fec":{"latticexp":1}
,"latticexp":{"devices":1}
,"(tn1051)":{"memory":1}
,"machxo":{"devices":1}
,"(tn1092)":{"memory":1}
,"machxo2":{"devices":1}
,"(tn1201)":{"memory":1}
,"ports":{"singal":1}
,"singal":{"invert":1}
,"invert":{"power":1}
,"power":{"ground":1}
,"ground":{"drc":1}
,"drc":{"check":1,"button":1,"results":1}
,"check":{"making":1}
,"making":{"changes":1}
,"changes":{"click":1}
,"click":{"drc":1}
,"button":{"logic":1}
,"toolbar":{"drc":1}
,"results":{"appear":1}
,"appear":{"tcl":1}
,"tcl":{"console":1}
,"console":{"editing":1}
,"component":{"logic":1}
}
;Search.control.loadWordPairs(pairs);
