var pairs =
{
"find":{"dialog":1,"pressing":1,"enter":1,"find":1,"type":1,"next":1,"pre":1,"previous":1}
,"dialog":{"box":1}
,"box":{"find":1,"accessed":1,"keeps":1}
,"accessed":{"choosing":1}
,"choosing":{"edit":1}
,"edit":{"find":1}
,"pressing":{"ctrl":1}
,"ctrl":{"allows":1}
,"allows":{"search":1}
,"search":{"object":1,"complete":1,"words":1}
,"object":{"specific":1,"want":1,"type":1,"highlights":1}
,"specific":{"type":1}
,"type":{"feature":1,"select":1,"site":1,"menu":1,"drop-down":1,"name":1}
,"feature":{"description":1}
,"description":{"find":1}
,"enter":{"name":1}
,"name":{"object":1,"match":1,"highlights":1}
,"want":{"find":1}
,"select":{"object":1,"site":1,"selects":1}
,"site":{"type":1,"selected":1}
,"menu":{"displayed":1,"match":1}
,"displayed":{"site":1}
,"selected":{"find":1}
,"drop-down":{"menu":1}
,"match":{"whole":1,"match":1,"case":1,"upper":1}
,"whole":{"word":1}
,"word":{"narrows":1}
,"narrows":{"search":1}
,"complete":{"name":1}
,"case":{"narrows":1}
,"words":{"match":1}
,"upper":{"lower":1}
,"lower":{"cases":1}
,"cases":{"find":1}
,"next":{"finds":1,"instance":1}
,"finds":{"first":1}
,"first":{"next":1}
,"instance":{"object":1,"highlights":1}
,"highlights":{"editing":1}
,"editing":{"area":1}
,"area":{"layout":1}
,"layout":{"find":1,"select":1,"close":1,"searching":1}
,"pre":{"searches":1}
,"searches":{"backward":1}
,"backward":{"find":1}
,"previous":{"instance":1}
,"selects":{"objects":1}
,"objects":{"specified":1,"highlighted":1,"notes":1}
,"specified":{"type":1}
,"close":{"button":1}
,"button":{"closes":1}
,"closes":{"dialog":1}
,"keeps":{"found":1}
,"found":{"objects":1}
,"highlighted":{"editing":1}
,"searching":{"objects":1}
,"notes":{"selecting":1}
}
;Search.control.loadWordPairs(pairs);
