var pairs =
{
"viewing":{"changing":1}
,"changing":{"attributes":1}
,"attributes":{"view":1,"preferences":1,"button":1,"following":1,"written":1,"attribute":1,"dialog":1}
,"view":{"change":1}
,"change":{"number":1}
,"number":{"attributes":1,"pins":1}
,"preferences":{"epic":1,"logic":1,"macro":1,"bus":1,"pin":1}
,"epic":{"objects":1}
,"objects":{"open":1,"associated":1}
,"open":{"attribute":1}
,"attribute":{"dialog":1}
,"dialog":{"box":1,"boxes":1}
,"box":{"selected":1,"components":1,"external":1,"macros":1,"buses":1,"paths":1,"nets":1,"wires":1,"sites":1,"pins":1}
,"selected":{"object":1}
,"object":{"click":1,"main":1}
,"click":{"attributes":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"choose":1}
,"choose":{"design":1}
,"design":{"attributes":1,"object":1}
,"following":{"table":1}
,"table":{"lists":1}
,"lists":{"objects":1}
,"associated":{"dialog":1,"net":1}
,"boxes":{"changes":1}
,"changes":{"attributes":1}
,"written":{"design\u0027s":1}
,"design\u0027s":{"preference":1}
,"preference":{"file":1}
,"file":{"save":1}
,"save":{"design":1}
,"main":{"attributes":1}
,"components":{"component":1,"attributes":1}
,"component":{"name":1}
,"name":{"preferences":1,"external":1,"component":1,"site":1,"type":1,"macro":1,"status":1,"elements":1,"route":1,"associated":1,"prohibit":1,"pin":1}
,"logic":{"strings":1}
,"strings":{"components":1}
,"external":{"pins":1,"name":1,"pin":1}
,"pins":{"pin":1,"preferences":1}
,"pin":{"name":1,"attributes":1,"list":1,"type":1}
,"site":{"name":1,"attributes":1}
,"type":{"external":1,"net":1}
,"macros":{"macro":1}
,"macro":{"name":1,"library":1,"attributes":1}
,"library":{"name":1}
,"status":{"reference":1,"number":1}
,"reference":{"comp":1}
,"comp":{"external":1}
,"buses":{"bus":1}
,"bus":{"name":1,"attributes":1}
,"elements":{"preferences":1,"maxdelay":1}
,"paths":{"path":1}
,"path":{"name":1,"attributes":1}
,"maxdelay":{"path":1}
,"nets":{"net":1}
,"net":{"name":1,"attributes":1,"wire":1}
,"route":{"status":1}
,"list":{"net":1}
,"wires":{"wire":1}
,"wire":{"name":1,"attributes":1}
,"sites":{"site":1}
,"prohibit":{"option":1}
,"option":{"site":1}
}
;Search.control.loadWordPairs(pairs);
