var pairs =
{
"setting":{"viewable":1}
,"viewable":{"layers":1}
,"layers":{"viewable":1,"displayed":1,"toolbar":1,"text":1,"highligted":1,"menu":1}
,"displayed":{"main":1}
,"main":{"view":1,"window":1}
,"view":{"epic":1,"show":1}
,"epic":{"include":1}
,"include":{"local":1}
,"local":{"wires":1}
,"wires":{"long":1,"pin":1,"sites":1}
,"long":{"wires":1}
,"pin":{"wires":1}
,"sites":{"switch":1,"components":1}
,"switch":{"boxes":1}
,"boxes":{"switches":1}
,"switches":{"sites":1}
,"components":{"routes":1}
,"routes":{"ratsnests":1}
,"ratsnests":{"text":1,"enabled":1}
,"text":{"highlighted":1,"layers":1}
,"highlighted":{"objects":1}
,"objects":{"layers":1,"controlled":1}
,"toolbar":{"toggle":1}
,"toggle":{"display":1}
,"display":{"layers":1}
,"highligted":{"objects":1}
,"controlled":{"view":1}
,"show":{"layers":1}
,"menu":{"default":1}
,"default":{"sites":1}
,"enabled":{"viewing":1}
,"viewing":{"main":1}
,"window":{"object":1}
,"object":{"definitions":1}
}
;Search.control.loadWordPairs(pairs);
