var pairs =
{
"notes":{"using":1}
,"using":{"logic":1,"following":1}
,"logic":{"block":1,"changing":1}
,"block":{"view":1,"views":1,"ram":1}
,"view":{"logic":1,"always":1,"allows":1,"clicking":1,"open":1,"remain":1,"using":1,"pressing":1}
,"always":{"opens":1}
,"opens":{"separate":1}
,"separate":{"view":1}
,"allows":{"return":1}
,"return":{"editing":1,"opened":1}
,"editing":{"area":1,"pfu":1,"block":1}
,"area":{"main":1}
,"main":{"view":1}
,"clicking":{"back":1}
,"back":{"button":1}
,"button":{"keeping":1,"top":1}
,"keeping":{"logic":1}
,"open":{"background":1,"until":1,"once":1}
,"background":{"logic":1}
,"remain":{"open":1}
,"until":{"click":1}
,"click":{"close":1,"symbol":1}
,"close":{"button":1}
,"top":{"right":1}
,"right":{"corner":1,"downward":1}
,"corner":{"multiple":1}
,"multiple":{"logic":1}
,"views":{"open":1,"select":1,"menu":1}
,"once":{"return":1}
,"opened":{"logic":1,"block":1}
,"select":{"window":1}
,"window":{"opened":1}
,"menu":{"zoom":1}
,"zoom":{"schematic":1,"drag":1,"keyboard":1,"ctrl":1,"pressing":1,"backward":1,"pan":1}
,"schematic":{"logic":1,"view":1,"display":1}
,"following":{"methods":1}
,"methods":{"drag":1}
,"drag":{"right":1,"upward":1}
,"downward":{"mouse":1}
,"mouse":{"zoom":1,"wheel":1}
,"upward":{"left":1}
,"left":{"zoom":1}
,"keyboard":{"combinations":1}
,"combinations":{"ctrl":1}
,"ctrl":{"zoom":1,"+-to":1,"key":1}
,"+-to":{"zoom":1}
,"pressing":{"ctrl":1,"mouse":1}
,"key":{"move":1}
,"move":{"mouse":1}
,"wheel":{"forward":1,"dragging":1}
,"forward":{"zoom":1}
,"backward":{"zoom":1}
,"pan":{"zooming":1}
,"zooming":{"schematic":1}
,"dragging":{"layout":1}
,"layout":{"direction":1}
,"direction":{"click":1}
,"symbol":{"schematic":1,"appears":1}
,"display":{"name":1,"indicate":1}
,"name":{"symbol":1}
,"appears":{"tcl":1}
,"tcl":{"console":1}
,"console":{"useful":1}
,"useful":{"understanding":1}
,"understanding":{"drc":1}
,"drc":{"warning":1}
,"warning":{"error":1}
,"error":{"messages":1}
,"messages":{"blue":1}
,"blue":{"(cyan)":1}
,"(cyan)":{"lines":1}
,"lines":{"schematic":1,"indicate":1}
,"indicate":{"connections":1,"available":1}
,"connections":{"programmed":1,"within":1}
,"programmed":{"magenta":1}
,"magenta":{"lines":1}
,"available":{"connections":1}
,"within":{"component":1}
,"component":{"editing":1}
,"pfu":{"logic":1}
,"changing":{"i\u002Fo":1,"pll":1,"dsp":1,"serdes":1}
,"i\u002Fo":{"types":1}
,"types":{"editing":1}
,"ram":{"contents":1}
,"contents":{"changing":1}
,"pll":{"configuration":1}
,"configuration":{"changing":1,"logic":1}
,"dsp":{"configuration":1}
,"serdes":{"configuration":1}
}
;Search.control.loadWordPairs(pairs);
