var pairs =
{
"epic":{"tcl":1,"session":1}
,"tcl":{"commands":1,"command":1,"console":1}
,"commands":{"epic":1,"perform":1,"automatically":1,"operation":1}
,"command":{"line":1}
,"line":{"located":1}
,"located":{"bottom":1}
,"bottom":{"tcl":1}
,"console":{"enables":1}
,"enables":{"commands":1}
,"perform":{"following":1}
,"following":{"basic":1,"options":1}
,"basic":{"actions":1}
,"actions":{"create":1}
,"create":{"tcl":1}
,"automatically":{"saved":1,"places":1}
,"saved":{".tcr":1}
,".tcr":{"file":1}
,"file":{"current":1,"name":1,"configure":1}
,"current":{"epic":1}
,"session":{"epic":1}
,"operation":{"syntax":1}
,"syntax":{"description":1}
,"description":{"new":1}
,"new":{"design":1,"-arch":1,"name":1}
,"design":{"macro":1,"eco_design":1,"rule":1,"specifies":1,"unroutes":1,"database":1,"swap":1,"unrouted":1}
,"macro":{"eco_design":1,"specifies":1,"save":1,"currently":1,"eco_add":1,"-macro":1,"design":1,"eco_delete":1,"<macro":1,"eco_swap":1,"empty":1,"eco_clone":1,"<macroname1>":1,"site":1,"additional":1,"nets":1,"name>":1}
,"eco_design":{"new":1,"open":1,"save":1,"close":1,"query":1,"drc":1}
,"-arch":{"<arch>":1}
,"<arch>":{"-device":1}
,"-device":{"<device>":1}
,"<device>":{"-package":1}
,"-package":{"<package>":1}
,"<package>":{"-speed":1}
,"-speed":{"<speed>":1}
,"<speed>":{"-ncd":1}
,"-ncd":{"<ncd":1}
,"<ncd":{"file>":1}
,"file>":{"[-macro]":1,"[-prf":1,"-prf":1,"[-site":1}
,"[-macro]":{"[-prf":1,"opens":1}
,"[-prf":{"<prf":1}
,"<prf":{"file>]":1}
,"file>]":{"creates":1,"[-macro]":1,"[-nmc":1,"saves":1,"configures":1}
,"creates":{"new":1}
,"specifies":{"targeted":1,"location":1,"placement":1,"cost":1}
,"targeted":{"device":1}
,"device":{"performance":1}
,"performance":{"grade":1}
,"grade":{".ncd":1}
,".ncd":{"file":1}
,"name":{"load":1,"close":1,"rename":1,"auto":1}
,"load":{"design":1}
,"open":{"-ncd":1,"saves":1,"query":1}
,"opens":{"existing":1}
,"existing":{"design":1,"net":1}
,"save":{"design":1,"[-ncd":1}
,"[-ncd":{"<ncd":1}
,"-prf":{"<prf":1}
,"[-nmc":{"<nmc":1}
,"<nmc":{"file>]":1,"file>":1}
,"saves":{"design":1,"different":1}
,"currently":{"open":1}
,"different":{"location":1,".ncd":1}
,"location":{"different":1,"delete":1}
,"close":{"design":1,"closes":1}
,"closes":{"design":1}
,"query":{"net\u002Fcomp\u002Fsite\u002Fpin":1,"[-a]":1}
,"net\u002Fcomp\u002Fsite\u002Fpin":{"eco_design":1}
,"[-a]":{"{-net":1}
,"{-net":{"<net":1}
,"<net":{"name>":1,"name>]":1}
,"name>":{"{-comp":1,"{-pin":1,"{-site":1,"searches":1,"{-netsanity":1,"{[-err]":1,"adds":1,"[-netpin":1,"-netpin":1,"-nmc":1,"removes":1,"unroutes":1,"{-macro":1,"{-netpin":1,"{{-netpin":1,"[-wire":1,"[-net":1,"[-macro":1,"-site":1,"places":1,"unplaces":1,"<logic":1,"displays":1,"[-bank_vccio":1,"-type":1,"-init_all_0":1,"-init_all":1,"-format":1,"-mode":1,"-mem":1}
,"{-comp":{"<comp":1,"<compname2>}":1,"<unplaced":1}
,"<comp":{"name>":1,"name>]":1}
,"{-pin":{"<pin":1}
,"<pin":{"name>":1,"name>]":1,"name>}":1}
,"{-site":{"<pin":1,"<sitename>":1}
,"searches":{"specific":1}
,"specific":{"net":1}
,"net":{"component":1,"sanity":1,"eco_add":1,"[-name":1,"connect":1,"add":1,"pin":1,"eco_delete":1,"<net":1,"design":1,"delete":1,"eco_rename":1,"<old":1,"new":1}
,"component":{"site":1,"eco_add":1,"specified":1,"eco_delete":1,"design":1,"delete":1,"eco_swap":1,"clone":1,"eco_clone":1,"eco_rename":1,"new":1,"eco_config":1,"program":1,"configure":1,"memory":1}
,"site":{"pin":1,"add":1,"move":1,"swap":1,"duplicates":1,"clone":1,"rename":1}
,"pin":{"drc":1,"component":1,"design":1,"eco_delete":1,"removes":1,"eco_swap":1,"<pinname1>":1,"locations":1}
,"drc":{"eco_design":1,"-chip":1}
,"-chip":{"{-net":1}
,"{-netsanity":{"<net":1}
,"{[-err]":{"{[-unrouted]":1}
,"{[-unrouted]":{"[-unplaced]}":1}
,"[-unplaced]}":{"performs":1}
,"performs":{"design":1,"specified":1}
,"rule":{"check":1}
,"check":{"objects":1,"net":1,"add":1}
,"objects":{"selected":1,"specified":1}
,"selected":{"nets":1}
,"nets":{"components":1,"comps":1,"auto":1}
,"components":{"options":1,"add":1,"following":1,"macros":1}
,"options":{"include":1,"-all":1,"disables":1}
,"include":{"chip":1}
,"chip":{"check":1}
,"sanity":{"check":1}
,"add":{"component":1,"net":1,"pins":1,"macro":1}
,"eco_add":{"comp":1,"net":1,"netpin":1,"macro":1}
,"comp":{"[-name":1,"<comp":1,"-comp1":1,"<compname1>":1,"<old":1,"name>":1,"comp":1}
,"[-name":{"<comp":1,"<net":1}
,"name>]":{"-site":1,"-netpin":1,"adds":1,"[-wire":1}
,"-site":{"<site":1,"<sitename>":1}
,"<site":{"name>":1,"name>]":1}
,"adds":{"component":1,"net":1,"pins":1,"macro":1}
,"specified":{"site":1,"pins":1,"nets":1,"number":1,"-all":1,"unplaced":1,"program":1,"component":1,"pll":1,"user":1,"embedded":1,"dynamic":1}
,"-netpin":{"<pin":1}
,"[-netpin":{"<pin":1}
,"connect":{"two":1}
,"two":{"specified":1}
,"pins":{"pins":1,"placed":1,"existing":1,"wires":1}
,"placed":{"components":1,"component":1}
,"netpin":{"-net":1,"<pin":1}
,"-net":{"<net":1}
,"-macro":{"<macro":1,"<macroname>":1}
,"<macro":{"name>":1}
,"-nmc":{"<nmc":1}
,"[-site":{"<site":1}
,"delete":{"component":1,"net":1,"macro":1}
,"eco_delete":{"comp":1,"net":1,"netpin":1,"macro":1}
,"removes":{"component":1,"net":1,"macro":1}
,"unroutes":{"net":1,"deletes":1,"signal":1,"connections":1}
,"deletes":{"net":1}
,"database":{"delete":1}
,"signal":{"pin":1}
,"swap":{"move":1,"pin":1}
,"move":{"component":1,"macro":1}
,"eco_swap":{"comp":1,"macro":1,"pin":1}
,"-comp1":{"<compname1>":1}
,"<compname1>":{"{-comp2":1,"{-comp":1}
,"{-comp2":{"<compname2>":1}
,"<compname2>":{"{-site":1}
,"<sitename>":{"swaps":1,"moves":1,"copies":1}
,"swaps":{"comp1":1,"pin":1}
,"comp1":{"comp2":1,"empty":1}
,"comp2":{"moves":1}
,"moves":{"comp1":1,"macro":1}
,"empty":{"site":1}
,"<macroname>":{"-site":1}
,"<pinname1>":{"<pinname2>":1}
,"<pinname2>":{"swaps":1}
,"locations":{"placed":1}
,"clone":{"component":1,"macro":1}
,"eco_clone":{"comp":1,"macro":1}
,"<compname2>}":{"{-site":1}
,"copies":{"component":1,"macro":1}
,"duplicates":{"site":1}
,"<macroname1>":{"{-macro":1}
,"{-macro":{"<macroname2>}":1,"<macro":1,"<unplaced":1}
,"<macroname2>}":{"{-site":1}
,"rename":{"component":1,"net":1}
,"eco_rename":{"comp":1,"net":1}
,"<old":{"compname>":1,"netname>":1}
,"compname>":{"<new":1,"gives":1}
,"<new":{"compname>":1,"netname>":1}
,"gives":{"component":1,"net":1}
,"netname>":{"<new":1,"gives":1}
,"auto":{"route":1,"{-all":1,"routes":1,"place":1,"[-x]":1}
,"route":{"eco_route":1}
,"eco_route":{"auto":1,"manual":1,"unroute":1}
,"{-all":{"[-i":1}
,"[-i":{"<iterations:-1,2000>]":1}
,"<iterations:-1,2000>]":{"[-cc":1}
,"[-cc":{"<costclean:0,20>]":1}
,"<costclean:0,20>]":{"[-dc":1}
,"[-dc":{"<delayclean:0,100>]":1}
,"<delayclean:0,100>]":{"[-ec":1}
,"[-ec":{"<delaycleanif:0,100>]":1}
,"<delaycleanif:0,100>]":{"[-x]":1}
,"[-x]":{"{-net":1,"[-l":1}
,"{-netpin":{"<pin":1}
,"{{-netpin":{"<pin":1}
,"name>}":{"{-wire":1,"{-netpin":1,"auto":1}
,"{-wire":{"<wire":1}
,"<wire":{"name>}":1,"name>]}":1,"name>":1}
,"routes":{"objects":1,"specified":1}
,"comps":{"macro":1}
,"additional":{"options":1}
,"-all":{"flag":1}
,"flag":{"performs":1,"used":1}
,"number":{"iterations":1,"cost-based":1,"delay-based":1}
,"iterations":{"-cc":1,"-dc":1,"-ec":1,"fully":1}
,"-cc":{"performs":1}
,"cost-based":{"cleanup":1}
,"cleanup":{"iterations":1}
,"-dc":{"performs":1}
,"delay-based":{"cleanup":1}
,"-ec":{"performs":1}
,"fully":{"routed":1}
,"routed":{"disables":1,"connections":1}
,"disables":{"timing-driven":1}
,"timing-driven":{"routing":1,"placement":1}
,"routing":{"manual":1}
,"manual":{"route":1,"{[-netpin":1,"place":1,"{-comp":1}
,"{[-netpin":{"<pin":1}
,"[-wire":{"<wire":1}
,"name>]}":{"routes":1}
,"wires":{"order":1}
,"order":{"given":1}
,"given":{"unroute":1}
,"unroute":{"eco_route":1,"[-all]":1}
,"[-all]":{"[-comp":1}
,"[-comp":{"<comp":1}
,"[-net":{"<net":1}
,"[-macro":{"<macro":1}
,"connections":{"specified":1,"design":1}
,"used":{"routed":1}
,"unrouted":{"except":1}
,"except":{"locked":1}
,"locked":{"signals":1}
,"signals":{"certain":1}
,"certain":{"macro":1}
,"place":{"eco_place":1}
,"eco_place":{"auto":1,"manual":1,"unplace":1}
,"[-l":{"<level:1,5>]":1}
,"<level:1,5>]":{"[-t":1}
,"[-t":{"<tableentry:1,100>]":1}
,"<tableentry:1,100>]":{"automatically":1}
,"places":{"components":1,"specified":1}
,"placement":{"specifies":1,"effort":1,"manual":1}
,"effort":{"level":1}
,"level":{"least":1}
,"least":{"difficult":1}
,"difficult":{"difficult":1,"specifies":1}
,"cost":{"table":1}
,"table":{"(from":1}
,"(from":{"100)":1}
,"100)":{"placement":1}
,"<unplaced":{"comp":1,"macro":1}
,"unplaced":{"components":1}
,"macros":{"sites":1,"ones":1}
,"sites":{"unplace":1}
,"unplace":{"eco_place":1,"[-all]":1}
,"unplaces":{"components":1}
,"ones":{"specified":1}
,"program":{"string":1}
,"string":{"component":1,"specified":1}
,"eco_config":{"comp":1,"sysio":1,"pll":1,"memufm":1,"memebr":1,"memdram":1}
,"<logic":{"string>":1}
,"string>":{"sets":1}
,"sets":{"program":1}
,"displays":{"program":1}
,"configure":{"sysio":1,"pll":1,"ufm":1,"ebr":1,"dram":1}
,"sysio":{"eco_config":1,"-comp":1}
,"-comp":{"<comp":1}
,"[-bank_vccio":{"<bank_vccio>]":1}
,"<bank_vccio>]":{"[-clamp":1}
,"[-clamp":{"<clamp>]":1}
,"<clamp>]":{"[-diffcurrent":1}
,"[-diffcurrent":{"<diffcurrent>]":1}
,"<diffcurrent>]":{"[-diffdrive":1}
,"[-diffdrive":{"<diffdrive>]":1}
,"<diffdrive>]":{"[-diffresistor":1}
,"[-diffresistor":{"<diffresistor>]":1}
,"<diffresistor>]":{"[-drive":1}
,"[-drive":{"<drive>]":1}
,"<drive>]":{"[-eq_call":1}
,"[-eq_call":{"<eq_call>]":1}
,"<eq_call>]":{"[-hysteresis":1}
,"[-hysteresis":{"<hysteresis>]":1}
,"<hysteresis>]":{"[-impedance":1}
,"[-impedance":{"<impedance>]":1}
,"<impedance>]":{"[-io_type":1}
,"[-io_type":{"<io_type>]":1}
,"<io_type>]":{"[-multdrive":1}
,"[-multdrive":{"<multdrive>]":1}
,"<multdrive>]":{"[-opendrain":1}
,"[-opendrain":{"<opendrain>]":1}
,"<opendrain>]":{"[-pciclamp":1}
,"[-pciclamp":{"<pciclamp>]":1}
,"<pciclamp>]":{"[-pullmode":1}
,"[-pullmode":{"<pullmode>]":1}
,"<pullmode>]":{"[-pwrsave":1}
,"[-pwrsave":{"<pwrsave>]":1}
,"<pwrsave>]":{"[-refcircuit":1}
,"[-refcircuit":{"<refcircuit>]":1}
,"<refcircuit>]":{"[-slewrate":1}
,"[-slewrate":{"<slewrate>]":1}
,"<slewrate>]":{"[-terminategnd":1}
,"[-terminategnd":{"<terminategnd>]":1}
,"<terminategnd>]":{"[-terminatevccio":1}
,"[-terminatevccio":{"<terminatevccio>]":1}
,"<terminatevccio>]":{"[-terminatevtt":1}
,"[-terminatevtt":{"<terminatevtt>]":1}
,"<terminatevtt>]":{"[-termination":1}
,"[-termination":{"<termination>]":1}
,"<termination>]":{"[-vcmt":1}
,"[-vcmt":{"<vcmt>]":1}
,"<vcmt>]":{"[-vref":1}
,"[-vref":{"<vref>]":1}
,"<vref>]":{"configures":1}
,"configures":{"i\u002Fo":1,"attributes":1,"settings":1}
,"i\u002Fo":{"attributes":1}
,"attributes":{"specified":1}
,"pll":{"eco_config":1,"-comp":1,"module":1}
,"-type":{"<type>":1}
,"<type>":{"[-phaseadj":1}
,"[-phaseadj":{"<phaseadj>]":1}
,"<phaseadj>]":{"[-delay_val":1}
,"[-delay_val":{"<delay>]":1}
,"<delay>]":{"[-fdel":1}
,"[-fdel":{"<fdel>]":1}
,"<fdel>]":{"[-clkos_fdel":1}
,"[-clkos_fdel":{"<clkos_fdel>]":1}
,"<clkos_fdel>]":{"configures":1}
,"module":{"configure":1}
,"ufm":{"eco_config":1}
,"memufm":{"-comp":1}
,"-init_all_0":{"<no":1}
,"<no":{"yes>":1}
,"yes>":{"[-format":1}
,"[-format":{"<hex":1}
,"<hex":{"bin>]":1,"bin":1}
,"bin>]":{"[-mem":1}
,"[-mem":{"<mem":1}
,"<mem":{"file>]":1}
,"settings":{"specified":1}
,"user":{"flash":1}
,"flash":{"memory":1}
,"memory":{"component":1,"initialization":1}
,"ebr":{"eco_config":1}
,"memebr":{"-instance":1}
,"-instance":{"<instance":1}
,"<instance":{"name>":1}
,"-init_all":{"no>":1}
,"no>":{"-mem":1}
,"-mem":{"<file":1}
,"<file":{"name>":1}
,"-format":{"<hex":1}
,"bin":{"add>":1}
,"add>":{"-init_data":1,"-depth":1}
,"-init_data":{"<dynamic":1}
,"<dynamic":{"static>":1}
,"static>":{"-module":1}
,"-module":{"<module":1}
,"<module":{"name>":1}
,"-mode":{"<mode":1}
,"<mode":{"value>":1}
,"value>":{"-depth":1,"-widtha":1,"-widthb":1,"[-area":1,"configures":1}
,"-depth":{"<depth":1}
,"<depth":{"value>":1}
,"-widtha":{"<widtha":1}
,"<widtha":{"value>":1}
,"-widthb":{"<widthb":1}
,"<widthb":{"value>":1}
,"[-area":{"<area":1}
,"<area":{"value>]":1}
,"value>]":{"[-ecc":1,"[-bytesize":1,"configures":1}
,"[-ecc":{"<ecc":1}
,"<ecc":{"value>]":1}
,"[-bytesize":{"<bytesize":1}
,"<bytesize":{"value>]":1}
,"embedded":{"block":1}
,"block":{"ram":1}
,"ram":{"component":1}
,"initialization":{"file":1}
,"dram":{"eco_config":1}
,"memdram":{"-instance":1}
,"dynamic":{"ram":1}
}
;Search.control.loadWordPairs(pairs);
