var pairs =
{
"swapping":{"components":1,"component":1}
,"components":{"components":1,"swapped":1,"type":1,"select":1,"want":1,"unrouted":1}
,"swapped":{"placed":1}
,"placed":{"components":1}
,"type":{"swap":1}
,"swap":{"locations":1,"choose":1,"click":1,"button":1}
,"locations":{"two":1,"rerouted":1}
,"two":{"components":1}
,"select":{"components":1}
,"want":{"swap":1}
,"choose":{"edit":1}
,"edit":{"swap":1}
,"click":{"swap":1,"two":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"click":1}
,"unrouted":{"swap":1}
,"rerouted":{"swapping":1}
,"component":{"pins":1}
}
;Search.control.loadWordPairs(pairs);
