var pairs =
{
"new":{"macro":1,"designs":1}
,"macro":{"dialog":1,"design":1,"file":1,"(.nmc)":1}
,"dialog":{"box":1}
,"box":{"new":1,"allows":1,"cancel":1,"help":1,"creating":1}
,"allows":{"create":1,"navigate":1}
,"create":{"macro":1}
,"design":{"file":1,"closes":1}
,"file":{"(.nmc)":1,"browse":1,"architecture":1}
,"(.nmc)":{"select":1,"file":1}
,"select":{"targeted":1,"package":1,"performance":1}
,"targeted":{"device":1,"architecture":1}
,"device":{"feature":1,"list":1,"family":1}
,"feature":{"description":1}
,"description":{"macro":1}
,"browse":{"button":1}
,"button":{"allows":1,"applies":1,"ignores":1}
,"navigate":{"desired":1}
,"desired":{"physical":1}
,"physical":{"macro":1}
,"architecture":{"list":1,"device":1,"package":1}
,"list":{"select":1}
,"family":{"within":1}
,"within":{"architecture":1}
,"package":{"list":1,"technology":1}
,"technology":{"performance":1}
,"performance":{"list":1,"grade":1}
,"grade":{"button":1}
,"applies":{"selected":1}
,"selected":{"options":1}
,"options":{"current":1,"may":1}
,"current":{"design":1}
,"closes":{"dialog":1}
,"cancel":{"button":1}
,"ignores":{"options":1}
,"may":{"specified":1}
,"specified":{"closes":1}
,"help":{"opens":1,"topic":1}
,"opens":{"online":1}
,"online":{"help":1}
,"topic":{"dialog":1}
,"creating":{"new":1}
,"designs":{"macros":1}
}
;Search.control.loadWordPairs(pairs);
