var pairs =
{
"working":{"macros":1}
,"macros":{"macro":1}
,"macro":{"mode":1,"menu":1,"instantiated":1,"library":1,"component":1,"least":1,"select":1}
,"mode":{"editing":1,"identical":1,"however":1,"operations":1,"available":1,"macro":1,"operation":1,"listing":1,"defining":1}
,"editing":{"operations":1}
,"operations":{"perform":1,"different":1,"unique":1}
,"perform":{"macro":1}
,"identical":{"performed":1}
,"performed":{"design":1,"macro":1}
,"design":{"mode":1,"macro":1,"file":1}
,"however":{"number":1}
,"number":{"operations":1}
,"different":{"performed":1}
,"unique":{"macro":1}
,"available":{"design":1}
,"menu":{"selections":1,"used":1}
,"selections":{"menu":1}
,"used":{"macro":1}
,"operation":{"function":1}
,"function":{"add":1}
,"add":{"external":1}
,"external":{"pin":1,"nets":1,"pins":1}
,"pin":{"designates":1,"external":1,"pin":1,"connected":1}
,"designates":{"selected":1}
,"selected":{"component":1,"macro":1,"reference":1}
,"component":{"pin":1,"macro\u0027s":1,"macro":1,"reference":1,"place":1,"components":1,"designate":1,"component":1,"lower":1,"tcl":1}
,"connected":{"external":1}
,"nets":{"macro":1}
,"instantiated":{"design":1}
,"file":{"list":1,"reference":1,"saved":1}
,"list":{"external":1}
,"pins":{"lists":1,"specified":1,"macro":1}
,"lists":{"external":1}
,"specified":{"macro":1}
,"library":{"file":1}
,"reference":{"comp":1,"component":1,"components":1}
,"comp":{"designates":1,"displays":1}
,"macro\u0027s":{"reference":1}
,"least":{"pre-placed":1}
,"pre-placed":{"component":1}
,"place":{"move":1}
,"move":{"copy":1}
,"copy":{"macro":1}
,"select":{"site":1}
,"site":{"reference":1}
,"components":{"located":1,"(macro":1}
,"located":{"relative":1}
,"relative":{"reference":1}
,"designate":{"reference":1}
,"lower":{"left":1}
,"left":{"corner":1}
,"corner":{"selected":1}
,"saved":{"reference":1}
,"displays":{"name":1}
,"name":{"reference":1}
,"tcl":{"console":1}
,"console":{"adding":1}
,"adding":{"external":1}
,"listing":{"external":1}
,"defining":{"reference":1}
,"(macro":{"mode)":1}
}
;Search.control.loadWordPairs(pairs);
