var pairs =
{
"adding":{"macro":1,"family":1,"macros":1}
,"macro":{"design":1,"bringing":1,"file":1,"library":1,"added":1,"add":1,"site":1,"unplaced":1,"dialog":1,"wish":1,"name":1,"format":1,"example":1}
,"design":{"mode":1,"instantiating":1,"design":1,"contain":1,"general":1,"file":1,"copy":1,"place":1,"note":1}
,"mode":{"add":1}
,"add":{"macro":1,"select":1,"type":1,"multiple":1}
,"instantiating":{"macro":1}
,"bringing":{"instance":1}
,"instance":{"library":1,"macro":1,"called":1}
,"library":{"macro":1,"file":1}
,"file":{"design":1,"unique":1,"macro":1,"adding":1,"placed":1,"subsequent":1,"refer":1,"used":1,"means":1,"specifies":1,"selected":1,"name":1,"defined":1,"numbering":1,"named":1,"added":1}
,"contain":{"multiple":1}
,"multiple":{"instances":1}
,"instances":{"macro":1}
,"unique":{"name":1}
,"name":{"within":1,"macro":1,"text":1,"add":1,"assigned":1}
,"within":{"design":1}
,"general":{"macro":1}
,"added":{"design":1,"number":1,"macro":1}
,"family":{"first":1}
,"first":{"time":1,"instance":1}
,"time":{"instantiate":1}
,"instantiate":{"macro":1}
,"copy":{"library":1,"affected":1}
,"placed":{"design":1,"specified":1,"components":1,"relative":1}
,"subsequent":{"instantiations":1}
,"instantiations":{"library":1}
,"refer":{"local":1}
,"local":{"copy":1}
,"affected":{"changes":1}
,"changes":{"external":1}
,"external":{"library":1}
,"used":{"original":1}
,"original":{"instantiation":1}
,"instantiation":{"add":1}
,"place":{"macro":1}
,"select":{"vacant":1,"site":1}
,"vacant":{"site":1}
,"site":{"place":1,"match":1,"i\u002Fo":1,"reference":1,"ignored":1,"macro":1,"step":1,"placed":1}
,"match":{"reference":1}
,"reference":{"component":1}
,"component":{"specified":1,"reference":1,"selected":1,"site":1,"macro":1,"placed":1,"notes":1}
,"specified":{"macro":1,"site":1}
,"means":{"macro":1}
,"specifies":{"i\u002Fo":1}
,"i\u002Fo":{"component":1}
,"selected":{"site":1,"vacant":1}
,"ignored":{"macro":1}
,"unplaced":{"instantiated":1}
,"instantiated":{"select":1,"choose":1}
,"choose":{"edit":1}
,"edit":{"add":1}
,"dialog":{"box":1}
,"box":{"appears":1,"specify":1}
,"appears":{"browse":1}
,"browse":{"button":1}
,"button":{"navigate":1}
,"navigate":{"macro":1}
,"wish":{"add":1}
,"type":{"name":1}
,"text":{"box":1}
,"specify":{"macro":1}
,"assigned":{"new":1}
,"new":{"macro":1,"instance":1,"added":1}
,"format":{"$libfile_number":1}
,"$libfile_number":{"libfile":1}
,"libfile":{"name":1}
,"defined":{"macro":1}
,"number":{"number":1,"assigned":1}
,"numbering":{"starts":1}
,"starts":{"increases":1}
,"increases":{"new":1}
,"example":{"add":1}
,"named":{"adder":1}
,"adder":{"first":1}
,"called":{"$adder_0":1,"$adder_1":1}
,"$adder_0":{"second":1}
,"second":{"called":1}
,"$adder_1":{"click":1}
,"click":{"instance":1}
,"note":{"selected":1}
,"step":{"macro\u0027s":1}
,"macro\u0027s":{"reference":1}
,"components":{"macro":1}
,"relative":{"reference":1}
,"notes":{"adding":1}
}
;Search.control.loadWordPairs(pairs);
