var pairs =
{
"placing":{"unplacing":1}
,"unplacing":{"components":1,"macros":1}
,"components":{"macros":1,"design":1}
,"macros":{"placed":1,"unplace":1,"selected":1,"main":1,"automatic":1,"design":1}
,"placed":{"editing":1}
,"editing":{"area":1}
,"area":{"main":1}
,"main":{"view":1}
,"view":{"automatically":1,"adds":1}
,"automatically":{"manually":1}
,"manually":{"placement":1}
,"placement":{"commands":1,"select":1,"(auto":1,"software":1,"placement":1,"routing":1}
,"commands":{"available":1}
,"available":{"design":1}
,"design":{"place":1,"automatic":1,"mode":1}
,"place":{"sub-menus":1,"component":1,"all)":1}
,"sub-menus":{"manual":1}
,"manual":{"placement":1}
,"select":{"source":1}
,"source":{"component":1}
,"component":{"macro":1}
,"macro":{"destination":1,"automatic":1,"mode":1}
,"destination":{"site":1}
,"site":{"place":1}
,"automatic":{"placement":1}
,"(auto":{"place":1}
,"all)":{"software":1}
,"software":{"selects":1}
,"selects":{"appropriate":1,"sites":1}
,"appropriate":{"sites":1}
,"sites":{"remaining":1,"intelligently":1}
,"remaining":{"unplaced":1}
,"unplaced":{"components":1}
,"intelligently":{"based":1}
,"based":{"routing":1}
,"routing":{"capability":1,"macro":1}
,"capability":{"unplace":1}
,"unplace":{"components":1,"command":1}
,"command":{"unroutes":1}
,"unroutes":{"net":1}
,"net":{"pin":1}
,"pin":{"components":1}
,"selected":{"removes":1}
,"removes":{"components":1}
,"adds":{"list":1}
,"list":{"design\u0027s":1}
,"design\u0027s":{"unplaced":1}
,"mode":{"placing":1}
}
;Search.control.loadWordPairs(pairs);
