var pairs =
{
"creating":{"new":1}
,"new":{"designs":1,"design":1,"new":1,"macro":1}
,"designs":{"macros":1}
,"macros":{"create":1}
,"create":{"new":1}
,"design":{"macro":1,"specify":1,"choose":1,"create":1,"dialog":1,"name":1,"file":1,"directory":1}
,"macro":{"epic":1,"choose":1,"create":1,"dialog":1,"name":1,"file":1,"directory":1}
,"epic":{"select":1}
,"select":{"targeted":1,"target":1,"desired":1}
,"targeted":{"device":1}
,"device":{"package":1}
,"package":{"performance":1}
,"performance":{"grade":1}
,"grade":{"design":1,"lists":1}
,"specify":{"required":1,"file":1,"directory":1}
,"required":{"file":1}
,"file":{"names":1,"new":1,"text":1,"created":1,"name":1}
,"names":{"create":1}
,"choose":{"file":1}
,"dialog":{"box":1}
,"box":{"appears":1,"enter":1,"browse":1}
,"appears":{"enter":1}
,"enter":{"design":1,".ncd":1,"preference":1,".prf":1,"macro":1,".nmc":1}
,"name":{"design":1,"enter":1,"preference":1,"select":1,"macro":1}
,"text":{"box":1}
,".ncd":{"extension":1}
,"extension":{"automatically":1}
,"automatically":{"added":1}
,"added":{"file":1}
,"created":{"place":1}
,"place":{"new":1}
,"directory":{"current":1,"browse":1,"specify":1,"file":1}
,"current":{"working":1}
,"working":{"directory":1}
,"browse":{"button":1}
,"button":{"select":1,"specify":1}
,"target":{"directory":1}
,"preference":{"file":1}
,".prf":{"extension":1}
,"desired":{"architecture":1}
,"architecture":{"device":1}
,"lists":{"click":1}
,"click":{"create":1}
,".nmc":{"extension":1}
}
;Search.control.loadWordPairs(pairs);
