var pairs =
{
"notes":{"automatically":1}
,"automatically":{"routing":1}
,"routing":{"selected":1,"performed":1,"ripped":1,"component":1,"par":1,"done":1}
,"selected":{"objects":1}
,"objects":{"notes":1,"autoroute":1,"within":1,"single":1,"combination":1,"used":1}
,"autoroute":{"net":1,"component":1,"selected":1,"command":1}
,"net":{"pin":1,"driver)":1,"load)":1,"driver":1,"ratsnest":1,"routed":1,"auto":1,"net":1}
,"pin":{"amount":1,"output":1,"net":1,"input":1,"auto":1,"component":1,"route":1,"wire":1}
,"amount":{"routing":1}
,"performed":{"depends":1}
,"depends":{"whether":1}
,"whether":{"net":1}
,"output":{"pin":1}
,"driver)":{"input":1}
,"input":{"pin":1}
,"load)":{"pin":1}
,"driver":{"auto":1,"autoroute":1}
,"auto":{"route":1}
,"route":{"routes":1,"allows":1,"objects":1,"segment":1,"path":1}
,"routes":{"entire":1,"connection":1,"swap":1}
,"entire":{"net":1}
,"connection":{"pin":1}
,"component":{"net":1,"routed":1,"pins":1}
,"routed":{"autoroute":1}
,"ratsnest":{"line":1}
,"line":{"entire":1,"long":1,"pin":1}
,"within":{"epic":1}
,"epic":{"existing":1,"optional":1}
,"existing":{"routing":1}
,"ripped":{"(that":1}
,"(that":{"unrouted)":1}
,"unrouted)":{"rerouted":1}
,"rerouted":{"accommodate":1}
,"accommodate":{"new":1}
,"new":{"routing":1}
,"pins":{"swapped":1,"necessary":1}
,"swapped":{"better":1}
,"better":{"routing":1}
,"par":{"(place":1,"efficient":1}
,"(place":{"route)":1}
,"route)":{"program":1}
,"program":{"rip":1}
,"rip":{"routes":1}
,"swap":{"pins":1}
,"necessary":{"routing":1}
,"done":{"par":1,"epic":1}
,"efficient":{"routing":1}
,"optional":{"auto":1}
,"allows":{"select":1}
,"select":{"two":1}
,"two":{"objects":1}
,"single":{"net":1}
,"combination":{"following":1}
,"following":{"objects":1}
,"used":{"net":1}
,"segment":{"local":1}
,"local":{"line":1}
,"long":{"line":1}
,"wire":{"perform":1}
,"perform":{"autoroute":1}
,"command":{"software":1}
,"software":{"attempts":1}
,"attempts":{"route":1}
,"path":{"two":1}
}
;Search.control.loadWordPairs(pairs);
