var pairs =
{
"adding":{"deleting":1}
,"deleting":{"components":1}
,"components":{"epic":1,"design":1,"select":1,"delete":1,"eliminated":1}
,"epic":{"enables":1}
,"enables":{"add":1}
,"add":{"components":1,"component":1,"button":1,"add":1}
,"design":{"delete":1,"database":1,"editing":1,"mode":1}
,"delete":{"add":1,"component":1,"components":1,"click":1,"button":1}
,"component":{"becomes":1,"net":1,"unrouted":1,"removed":1,"design":1,"click":1,"dialog":1,"component":1,"name":1,"part":1}
,"becomes":{"part":1}
,"part":{"design":1,"instantiated":1}
,"database":{"delete":1,"add":1,"note":1}
,"net":{"pin":1,"finally":1}
,"pin":{"component":1,"removed":1}
,"unrouted":{"net":1}
,"removed":{"net":1,"design":1}
,"finally":{"component":1}
,"editing":{"area":1}
,"area":{"select":1}
,"select":{"vacant":1,"components":1}
,"vacant":{"site":1}
,"site":{"place":1}
,"place":{"new":1}
,"new":{"component":1}
,"click":{"add":1,"delete":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"choose":1}
,"choose":{"edit":1}
,"edit":{"add":1,"delete":1}
,"dialog":{"box":1}
,"box":{"type":1,"empty":1}
,"type":{"unique":1}
,"unique":{"name":1}
,"name":{"new":1,"box":1}
,"empty":{"click":1}
,"eliminated":{"database":1}
,"note":{"possible":1}
,"possible":{"delete":1}
,"instantiated":{"macro":1}
,"macro":{"design":1}
}
;Search.control.loadWordPairs(pairs);
