var pairs =
{
"re-selecting":{"objects":1}
,"objects":{"tcl":1,"click":1}
,"tcl":{"console":1}
,"console":{"time":1,"hyperlink":1,"scroll":1}
,"time":{"select":1,"current":1}
,"select":{"object":1}
,"object":{"editing":1,"re-select":1,"tcl":1,"immediately":1}
,"editing":{"area":1}
,"area":{"recorded":1}
,"recorded":{"tcl":1}
,"hyperlink":{"enables":1}
,"enables":{"quickly":1}
,"quickly":{"return":1}
,"return":{"object":1}
,"re-select":{"time":1,"object":1}
,"current":{"session":1}
,"session":{"re-select":1}
,"scroll":{"list":1}
,"list":{"pre-selected":1}
,"pre-selected":{"objects":1}
,"click":{"hyperlinked":1}
,"hyperlinked":{"name":1}
,"name":{"want":1}
,"want":{"re-select":1}
,"immediately":{"selected":1}
,"selected":{"editing":1}
}
;Search.control.loadWordPairs(pairs);
