var pairs =
{
"save":{"dialog":1,"press":1}
,"dialog":{"box":1}
,"box":{"save":1,"appears":1,"cancel":1,"help":1,"saving":1}
,"appears":{"select":1}
,"select":{"menu":1}
,"menu":{"item":1}
,"item":{"file":1}
,"file":{"save":1,"browse":1,"preference":1}
,"press":{"ctrl":1}
,"ctrl":{"shift":1}
,"shift":{"feature":1}
,"feature":{"description":1}
,"description":{"design":1}
,"design":{"file":1,"(.ncd)":1,"files":1}
,"browse":{"button":1}
,"button":{"allows":1,"saves":1,"ignores":1}
,"allows":{"navigate":1}
,"navigate":{"directory":1}
,"directory":{"location":1}
,"location":{"physical":1}
,"physical":{"design":1,"preference":1}
,"(.ncd)":{"file":1}
,"preference":{"file":1,"(.prf)":1}
,"(.prf)":{"button":1}
,"saves":{"files":1}
,"files":{"closes":1}
,"closes":{"dialog":1}
,"cancel":{"button":1}
,"ignores":{"changes":1}
,"changes":{"specified":1}
,"specified":{"closes":1}
,"help":{"opens":1,"topic":1}
,"opens":{"online":1}
,"online":{"help":1}
,"topic":{"dialog":1}
,"saving":{"design":1}
}
;Search.control.loadWordPairs(pairs);
