var pairs =
{
"save":{"macro":1,"dialog":1}
,"macro":{"dialog":1,"feature":1,"file":1,"(.nmc)":1}
,"dialog":{"box":1}
,"box":{"save":1,"appears":1,"cancel":1,"help":1,"saving":1}
,"appears":{"select":1}
,"select":{"menu":1}
,"menu":{"item":1}
,"item":{"file":1}
,"file":{"save":1,"allows":1,"browse":1,"button":1}
,"feature":{"description":1}
,"description":{"macro":1}
,"allows":{"specify":1}
,"specify":{"physical":1}
,"physical":{"macro":1}
,"(.nmc)":{"file":1}
,"browse":{"existing":1}
,"existing":{"file":1}
,"button":{"saves":1,"ignores":1}
,"saves":{"specified":1}
,"specified":{"files":1,"closes":1}
,"files":{"closes":1}
,"closes":{"dialog":1}
,"cancel":{"button":1}
,"ignores":{"changes":1}
,"changes":{"specified":1}
,"help":{"opens":1,"topic":1}
,"opens":{"online":1}
,"online":{"help":1}
,"topic":{"dialog":1}
,"saving":{"design":1}
,"design":{"files":1}
}
;Search.control.loadWordPairs(pairs);
