var pairs =
{
"macro":{"terminology":1,"instance":1,"macro":1,"library":1,"pin":1,"components":1,"mode":1,"design":1,"change":1,"instantiated":1,"reference":1,"located":1,"unbind":1,"name":1,"treated":1}
,"terminology":{"following":1,"description":1}
,"following":{"list":1}
,"list":{"terms":1}
,"terms":{"important":1}
,"important":{"concepts":1}
,"concepts":{"understanding":1}
,"understanding":{"macros":1}
,"macros":{"used":1}
,"used":{"designs":1,"connect":1,"reference":1}
,"designs":{"terminology":1}
,"description":{"external":1}
,"external":{"net":1,"pins":1,"pin":1}
,"net":{"net":1,"outside":1,"may":1,"connected":1,"within":1,"completely":1}
,"outside":{"macro":1}
,"instance":{"connected":1,"copy":1,"design":1,"placed":1,"select":1}
,"connected":{"macro\u0027s":1,"external":1}
,"macro\u0027s":{"external":1,"components":1,"reference":1}
,"pins":{"part":1,"macro":1}
,"part":{"external":1}
,"may":{"lie":1}
,"lie":{"within":1}
,"within":{"macro":1}
,"library":{"file":1,"files":1}
,"file":{"contained":1,"connection":1,"file":1,"containing":1,"inserted":1,"add":1,"receive":1,"copied":1,"instantiate":1,"changes":1,"pre-placed":1,"pre-routed":1,"used":1,"least":1,"created":1}
,"contained":{"net":1}
,"pin":{"external":1,"macro":1,"used":1,"types":1}
,"connect":{"components":1}
,"components":{"instantiated":1,"design":1,"determined":1,"pre-placed":1,"(macro":1,"macro":1,"nets":1}
,"instantiated":{"macro":1,"design":1}
,"design":{"(outside":1,"file":1,"instantiate":1,"contain":1,"design":1,"require":1}
,"(outside":{"macro)":1}
,"macro)":{"pin":1}
,"types":{"internal":1}
,"internal":{"net":1}
,"connection":{"macro\u0027s":1}
,"containing":{"definition":1}
,"definition":{"macro":1}
,"files":{".nmc":1}
,".nmc":{"extension":1}
,"extension":{"created":1}
,"created":{"edited":1}
,"edited":{"epic":1,"specify":1}
,"epic":{"operating":1}
,"operating":{"macro":1}
,"mode":{"macro":1}
,"copy":{"macro":1}
,"inserted":{"design":1}
,"add":{"macro":1}
,"instantiate":{"macro":1,"pre-routed":1}
,"contain":{"multiple":1}
,"multiple":{"instances":1}
,"instances":{"library":1}
,"receive":{"unique":1}
,"unique":{"name":1}
,"name":{"library":1,"disappears":1}
,"copied":{"design":1,"placement":1}
,"change":{"library":1}
,"changes":{"reflected":1}
,"reflected":{"macro":1}
,"pre-placed":{"component":1,"macro":1}
,"component":{"component":1,"placed":1,"macro":1,"least":1,"none":1,"specify":1,"system":1,"place":1,"unbind":1}
,"placed":{"macro":1,"moved":1,"site":1,"components":1}
,"pre-routed":{"net":1,"macro":1}
,"completely":{"routed":1}
,"routed":{"macro":1}
,"require":{"substantially":1}
,"substantially":{"longer":1}
,"longer":{"time":1}
,"time":{"place":1}
,"place":{"route":1,"move":1}
,"route":{"depending":1,"complexity":1}
,"depending":{"route":1}
,"complexity":{"reference":1}
,"reference":{"component":1,"macro":1,"components":1}
,"moved":{"copied":1}
,"placement":{"routing":1}
,"routing":{"pre-placed":1}
,"determined":{"relative":1}
,"relative":{"component":1,"reference":1}
,"least":{"macro\u0027s":1,"pre-placed":1}
,"none":{"macro":1}
,"specify":{"macro":1,"reference":1}
,"system":{"assigns":1}
,"assigns":{"automatically":1}
,"automatically":{"defining":1}
,"defining":{"reference":1}
,"(macro":{"mode)":1}
,"mode)":{"instruction":1}
,"instruction":{"defining":1}
,"move":{"copy":1}
,"select":{"site":1}
,"site":{"execute":1,"designated":1}
,"execute":{"appropriate":1}
,"appropriate":{"command":1}
,"command":{"macro\u0027s":1}
,"designated":{"placed":1}
,"located":{"sites":1}
,"sites":{"relative":1}
,"unbind":{"action":1,"macro":1}
,"action":{"disassociates":1}
,"disassociates":{"macro\u0027s":1}
,"nets":{"macro":1,"formerly":1}
,"disappears":{"design\u0027s":1}
,"design\u0027s":{"database":1}
,"database":{"components":1}
,"formerly":{"macro":1}
,"treated":{"separate":1}
,"separate":{"components":1}
}
;Search.control.loadWordPairs(pairs);
