var pairs =
{
"unrouting":{"unrouting":1,"rips":1,"ratsnests":1}
,"rips":{"routed":1}
,"routed":{"connections":1}
,"connections":{"specified":1,"remain":1,"displayed":1,"design":1,"net":1}
,"specified":{"objects":1}
,"objects":{"logical":1,"unroute":1,"components":1,"select":1,"selected":1}
,"logical":{"connections":1}
,"remain":{"unrouting":1,"unroute":1}
,"ratsnests":{"layer":1}
,"layer":{"enabled":1}
,"enabled":{"layers":1,"previously":1}
,"layers":{"toolbar":1}
,"toolbar":{"ripped-up":1}
,"ripped-up":{"routes":1}
,"routes":{"displayed":1}
,"displayed":{"ratsnest":1}
,"ratsnest":{"lines":1}
,"lines":{"unroute":1,"long":1,"pin":1}
,"unroute":{"selected":1,"entire":1,"following":1,"select":1,"click":1,"button":1,"routed":1,"net":1,"component":1}
,"selected":{"objects":1,"editing":1,"object":1,"unrouted":1}
,"entire":{"design":1,"net":1}
,"design":{"note":1,"route":1,"choose":1,"unrouted":1}
,"note":{"locked":1}
,"locked":{"nets":1,"signals":1}
,"nets":{"cannot":1,"net":1,"macros":1,"unroute":1}
,"cannot":{"unrouted":1}
,"unrouted":{"unroute":1,"ratsnests":1,"except":1,"routed":1}
,"following":{"objects":1}
,"components":{"nets":1,"net":1}
,"net":{"pins":1,"pin":1,"remain":1,"unroute":1}
,"pins":{"route":1}
,"route":{"segments":1,"unroute":1}
,"segments":{"macros":1}
,"macros":{"used":1,"selected":1}
,"used":{"local":1,"wires":1}
,"local":{"lines":1}
,"long":{"lines":1}
,"pin":{"wires":1,"connection":1,"unrouted":1,"component":1}
,"wires":{"unroute":1,"components":1,"selected":1}
,"select":{"objects":1,"combination":1}
,"combination":{"components":1}
,"editing":{"area":1}
,"area":{"main":1}
,"main":{"view":1}
,"view":{"nets":1}
,"object":{"menu":1}
,"menu":{"choose":1}
,"choose":{"design":1}
,"click":{"unroute":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"objects":1}
,"previously":{"routed":1}
,"except":{"locked":1}
,"signals":{"certain":1}
,"certain":{"macro":1}
,"macro":{"nets":1}
,"connection":{"net":1}
,"component":{"unroute":1}
}
;Search.control.loadWordPairs(pairs);
