var pairs =
{
"automatic":{"routing":1}
,"routing":{"auto":1,"route":1,"selected":1,"entire":1}
,"auto":{"route":1}
,"route":{"option":1,"performed":1,"selected":1,"enabled":1,"manual":1,"auto":1,"used":1,"entire":1,"segments":1,"select":1,"click":1,"unrouted":1}
,"option":{"automatically":1}
,"automatically":{"routes":1,"routed":1,"route":1,"routing":1}
,"routes":{"unrouted":1}
,"unrouted":{"nets":1,"connections":1}
,"nets":{"created":1,"net":1,"selected":1}
,"created":{"result":1}
,"result":{"editing":1}
,"editing":{"action":1}
,"action":{"placing":1}
,"placing":{"component":1}
,"component":{"creating":1,"pins":1}
,"creating":{"new":1}
,"new":{"net":1}
,"net":{"swapping":1,"pins":1,"route":1,"display":1,"cannot":1}
,"swapping":{"components":1}
,"components":{"auto":1,"macros":1}
,"performed":{"end":1}
,"end":{"add":1}
,"add":{"copy":1}
,"copy":{"swap":1}
,"swap":{"place":1}
,"place":{"command":1}
,"command":{"select":1}
,"select":{"auto":1,"objects":1,"combination":1}
,"selected":{"objects":1,"object":1,"routed":1}
,"objects":{"auto":1,"choosing":1,"automatically":1,"select":1,"want":1,"selected":1,"notes":1}
,"enabled":{"default":1}
,"default":{"manual":1}
,"manual":{"routing":1,"route":1}
,"choosing":{"design":1}
,"design":{"route":1,"following":1,"choose":1}
,"used":{"route":1,"two":1,"net":1,"wires":1,"unused":1}
,"entire":{"design":1}
,"following":{"objects":1}
,"routed":{"nets":1,"(if":1,"connection":1,"net":1,"completely":1,"completion":1}
,"pins":{"ratsnest":1,"automatically":1}
,"ratsnest":{"lines":1,"display":1}
,"lines":{"components":1}
,"macros":{"auto":1,"unrouted":1}
,"two":{"resources":1}
,"resources":{"resources":1,"used":1}
,"segments":{"used":1}
,"wires":{"used":1}
,"unused":{"component":1}
,"want":{"automatically":1}
,"combination":{"nets":1}
,"object":{"menu":1,"routed":1}
,"menu":{"choose":1}
,"choose":{"design":1}
,"click":{"autoroute":1}
,"autoroute":{"button":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"objects":1}
,"(if":{"possible)":1}
,"possible)":{"display":1}
,"display":{"routed":1,"object":1,"remain":1,"net":1}
,"connection":{"changes":1}
,"changes":{"ratsnest":1}
,"completely":{"error":1}
,"error":{"message":1}
,"message":{"appear":1}
,"appear":{"tcl":1}
,"tcl":{"console":1}
,"console":{"ratsnest":1,"notes":1}
,"remain":{"automatically":1}
,"connections":{"routed":1}
,"cannot":{"routed":1}
,"completion":{"error":1}
,"notes":{"automatically":1}
}
;Search.control.loadWordPairs(pairs);
