var pairs =
{
"routing":{"unrouting":1,"(auto":1,"path":1,"turned":1,"objects":1,"specify":1,"notes":1}
,"unrouting":{"connections":1,"rips":1}
,"connections":{"routed":1,"unrouting":1,"nets":1,"design":1}
,"routed":{"editing":1,"add":1}
,"editing":{"area":1}
,"area":{"main":1}
,"main":{"view":1}
,"view":{"automatically":1}
,"automatically":{"manually":1,"routed":1}
,"manually":{"select":1}
,"select":{"automatic":1,"default":1}
,"automatic":{"routing":1}
,"(auto":{"route)":1}
,"route)":{"software":1}
,"software":{"selects":1}
,"selects":{"routing":1}
,"path":{"connection":1,"used":1}
,"connection":{"select":1}
,"default":{"automatic":1}
,"turned":{"automatic":1}
,"objects":{"automatically":1}
,"add":{"place":1}
,"place":{"copy":1}
,"copy":{"swap":1}
,"swap":{"clone":1}
,"clone":{"manual":1}
,"manual":{"routing":1}
,"specify":{"routing":1}
,"used":{"unroute":1}
,"unroute":{"connections":1,"manual":1}
,"rips":{"specified":1}
,"specified":{"routes":1}
,"routes":{"without":1}
,"without":{"eliminating":1}
,"eliminating":{"logical":1}
,"logical":{"connections":1}
,"nets":{"involved":1}
,"involved":{"route":1}
,"route":{"unroute":1}
,"design":{"selecting":1}
,"selecting":{"auto":1}
,"auto":{"route":1}
,"notes":{"manual":1}
}
;Search.control.loadWordPairs(pairs);
