var pairs =
{
"using":{"tcl":1}
,"tcl":{"console":1,"commands":1}
,"console":{"tab":1,"keeps":1,"window":1,"displays":1}
,"tab":{"epic":1}
,"epic":{"tcl":1,"session":1}
,"keeps":{"track":1}
,"track":{"actions":1}
,"actions":{"executed":1}
,"executed":{"current":1}
,"current":{"session":1}
,"session":{"info":1,"automatically":1,"exit":1,"available":1}
,"info":{"warning":1}
,"warning":{"error":1}
,"error":{"messages":1,"causes":1}
,"messages":{"displays":1}
,"displays":{"select":1,"commands":1}
,"select":{"object":1}
,"object":{"net":1,"moving":1}
,"net":{"wire":1}
,"wire":{"component":1}
,"component":{"records":1}
,"records":{"selections":1}
,"selections":{"hyperlinks":1}
,"hyperlinks":{"quickly":1}
,"quickly":{"return":1}
,"return":{"clicking":1}
,"clicking":{"hyperlinked":1}
,"hyperlinked":{"name":1}
,"name":{"console":1}
,"window":{"automatic":1}
,"automatic":{"recording":1}
,"recording":{"commands":1}
,"commands":{"tcl":1,"perform":1,"epic":1,"used":1}
,"perform":{"design":1}
,"design":{"adding":1}
,"adding":{"object":1}
,"moving":{"swapping":1}
,"swapping":{"components":1}
,"components":{"performing":1}
,"performing":{"drc":1}
,"drc":{"commands":1}
,"automatically":{"saved":1}
,"saved":{".tcr":1}
,".tcr":{"file":1,"files":1}
,"file":{"project":1,".tcr":1}
,"project":{"directory":1}
,"directory":{"loss":1}
,"loss":{"power":1}
,"power":{"software":1}
,"software":{"error":1}
,"causes":{"epic":1}
,"exit":{"abnormally":1}
,"abnormally":{"commands":1}
,"used":{"session":1}
,"available":{".tcr":1}
,"files":{"located":1}
,"located":{"following":1}
,"following":{"directories":1}
,"directories":{".\u005C<project_name>":1}
,".\u005C<project_name>":{".ncd_tcr.dir":1,".nmc_tcr.dir":1}
,".ncd_tcr.dir":{".\u005C<project_name>":1}
,".nmc_tcr.dir":{"epic":1}
}
;Search.control.loadWordPairs(pairs);
