var pairs =
{
"placement":{"components":1,"select":1,"(autoplace":1,"software":1,"enabled":1}
,"components":{"macros":1,"design":1}
,"macros":{"placed":1,"unplace":1,"select":1,"editing":1,"default":1}
,"placed":{"editing":1}
,"editing":{"area":1}
,"area":{"main":1,"adds":1}
,"main":{"view":1}
,"view":{"either":1}
,"either":{"automatically":1}
,"automatically":{"manually":1}
,"manually":{"manual":1}
,"manual":{"placement":1}
,"select":{"source":1,"removes":1}
,"source":{"component":1}
,"component":{"macro":1}
,"macro":{"destination":1,"automatic":1}
,"destination":{"site":1}
,"site":{"place":1}
,"place":{"component":1}
,"automatic":{"placement":1}
,"(autoplace":{"all)":1}
,"all)":{"system":1}
,"system":{"selects":1}
,"selects":{"appropriate":1,"sites":1}
,"appropriate":{"sites":1}
,"sites":{"remaining":1,"intelligently":1}
,"remaining":{"unplaced":1}
,"unplaced":{"components":1}
,"design":{"automatic":1}
,"software":{"selects":1}
,"intelligently":{"based":1}
,"based":{"routability":1}
,"routability":{"unplace":1}
,"unplace":{"components":1,"command":1}
,"command":{"unroutes":1}
,"unroutes":{"net":1}
,"net":{"pin":1}
,"pin":{"components":1}
,"removes":{"components":1}
,"adds":{"list":1}
,"list":{"design\u0027s":1}
,"design\u0027s":{"unplaced":1}
,"default":{"automatic":1}
,"enabled":{"epic":1}
}
;Search.control.loadWordPairs(pairs);
