var pairs =
{
"design":{"modes":1,"mode":1,"(.ncd)":1,"file":1,"macro":1}
,"modes":{"two":1,"epic":1}
,"two":{"design":1}
,"epic":{"design":1,"either":1,"sets":1}
,"mode":{"macro":1,"design":1,"refers":1,"physical":1,"cannot":1,"file":1}
,"macro":{"mode":1,"file":1,"modes":1}
,"refers":{"options":1}
,"options":{"functionality":1}
,"functionality":{"available":1}
,"available":{"epic":1}
,"either":{"viewing":1,"opening":1}
,"viewing":{"editing":1}
,"editing":{"physical":1}
,"physical":{"design":1,"macro":1}
,"(.ncd)":{"file":1,"loaded":1,"design":1}
,"file":{"macro":1,"(.nmc)":1,"(.ncd)":1,"physical":1,"type":1}
,"(.nmc)":{"loaded":1}
,"loaded":{"either":1}
,"opening":{"creating":1}
,"creating":{"design":1,"instantiate":1}
,"instantiate":{"macro":1}
,"cannot":{"toggle":1}
,"toggle":{"back":1}
,"back":{"forth":1}
,"forth":{"design":1}
,"sets":{"mode":1}
,"type":{"loaded":1}
}
;Search.control.loadWordPairs(pairs);
