var pairs =
{
"physical":{"macros":1,"macro":1}
,"macros":{"design":1,"using":1,"contain":1,"particularly":1,"schematics":1}
,"design":{"physical":1,"editor":1,"even":1,"schematic":1,"macro":1,"mode":1,"epic":1,"copy":1,"file":1}
,"using":{"epic":1}
,"epic":{"design":1,"macro":1,"instantiate":1}
,"editor":{"physical":1}
,"macro":{"(often":1,"macro":1,"library":1,"unplaced":1,"created":1,"mode":1,"adding":1,"design":1,"lost":1,"schematic":1,"terminology":1,"file":1}
,"(often":{"referred":1}
,"referred":{"macro":1}
,"library":{"file":1}
,"file":{"stored":1,".nmc":1,"instantiate":1,"design":1,"macro":1,"change":1,"changes":1,"schematic":1}
,"stored":{"file":1}
,".nmc":{"extension":1,"file":1}
,"extension":{"describes":1}
,"describes":{"function":1}
,"function":{"terms":1,"mapped":1,"macro":1}
,"terms":{"logic":1}
,"logic":{"connectivity":1}
,"connectivity":{"function":1}
,"mapped":{"components":1}
,"components":{"particular":1}
,"particular":{"fpga":1}
,"fpga":{"device":1}
,"device":{"architecture":1,"map":1}
,"architecture":{"physical":1,"compatibility":1}
,"contain":{"placement":1}
,"placement":{"routing":1}
,"routing":{"information":1}
,"information":{"function":1,"adding":1}
,"unplaced":{"partially":1}
,"partially":{"placed":1,"routed":1}
,"placed":{"fully":1,"unrouted":1}
,"fully":{"placed":1,"routed":1}
,"unrouted":{"partially":1}
,"routed":{"fully":1,"physical":1}
,"particularly":{"helpful":1}
,"helpful":{"know":1}
,"know":{"type":1}
,"type":{"device":1}
,"map":{"design":1}
,"even":{"design":1}
,"schematic":{"physical":1,"drawing":1,"configuring":1,"information":1}
,"created":{"epic":1}
,"mode":{"save":1,"create":1}
,"save":{"design":1}
,"adding":{"macro":1,"macros":1}
,"create":{"macro":1}
,"instantiate":{"macro":1}
,"copy":{"contents":1}
,"contents":{"library":1}
,"lost":{"link":1}
,"link":{"library":1}
,"change":{"library":1}
,"changes":{"reflected":1}
,"reflected":{"instantiated":1}
,"instantiated":{"macro":1}
,"drawing":{"entering":1}
,"entering":{"block":1}
,"block":{"schematic":1,"appropriately":1}
,"configuring":{"block":1}
,"appropriately":{"placing":1}
,"placing":{"reference":1}
,"reference":{".nmc":1}
,"schematics":{"appropriate":1}
,"appropriate":{"cae":1}
,"cae":{"vendor":1}
,"vendor":{"documentation":1}
,"documentation":{"contact":1}
,"contact":{"customer":1}
,"customer":{"support":1}
,"support":{"check":1,"cross":1}
,"check":{"technical":1}
,"technical":{"support":1}
,"cross":{"architecture":1}
,"compatibility":{"macro":1}
,"terminology":{"reading":1}
,"reading":{"physical":1}
}
;Search.control.loadWordPairs(pairs);
