var pairs =
{
"manual":{"placement":1,"place":1}
,"placement":{"three":1,"procedures":1}
,"three":{"manual":1}
,"procedures":{"manually":1}
,"manually":{"placing":1,"place":1}
,"placing":{"unplaced":1}
,"unplaced":{"component":1,"comps":1}
,"component":{"macro":1,"editing":1,"site":1,"placed":1,"routed":1}
,"macro":{"vacant":1,"site":1}
,"vacant":{"site":1}
,"site":{"moving":1,"placed":1,"note":1,"type":1,"choose":1,"component":1}
,"moving":{"component":1}
,"placed":{"swapping":1,"components":1,"selected":1,"site":1}
,"swapping":{"sites":1}
,"sites":{"two":1}
,"two":{"placed":1}
,"components":{"manually":1}
,"place":{"unplaced":1,"manual":1,"component":1}
,"editing":{"area":1}
,"area":{"main":1}
,"main":{"view":1}
,"view":{"select":1}
,"select":{"desired":1,"unplaced":1,"component":1}
,"desired":{"vacant":1}
,"note":{"component":1,"steps":1}
,"type":{"block":1}
,"block":{"(pic":1}
,"(pic":{"pic":1}
,"pic":{"pfu":1}
,"pfu":{"pfu)":1}
,"pfu)":{"note":1}
,"steps":{"performed":1}
,"performed":{"reverse":1}
,"reverse":{"order":1}
,"order":{"object":1}
,"object":{"menu":1}
,"menu":{"select":1}
,"comps":{"drop-down":1}
,"drop-down":{"list":1}
,"list":{"select":1}
,"selected":{"site":1}
,"choose":{"design":1}
,"design":{"place":1}
,"routed":{"placed":1}
}
;Search.control.loadWordPairs(pairs);
