var pairs =
{
"new":{"design":1,"designs":1}
,"design":{"dialog":1,"file":1,"(.ncd)":1,"closes":1}
,"dialog":{"box":1}
,"box":{"new":1,"allows":1,"preference":1,"auto":1,"cancel":1,"help":1,"creating":1}
,"allows":{"create":1,"navigate":1}
,"create":{"design":1}
,"file":{"associated":1,"select":1,"browse":1,"alternatively":1,"input":1,"specified":1,"filename":1,"architecture":1}
,"associated":{"preference":1}
,"preference":{"file":1,"(.prf)":1}
,"select":{"targeted":1,"specific":1,"package":1,"performance":1}
,"targeted":{"device":1,"architecture":1}
,"device":{"feature":1,"list":1,"family":1}
,"feature":{"description":1}
,"description":{"design":1}
,"browse":{"button":1}
,"button":{"allows":1,"applies":1,"ignores":1,"opens":1}
,"navigate":{"desired":1}
,"desired":{"physical":1,"preference":1}
,"physical":{"design":1}
,"(.ncd)":{"file":1}
,"alternatively":{"specify":1}
,"specify":{"full":1}
,"full":{"path":1}
,"path":{"file":1}
,"input":{"box":1}
,"(.prf)":{"file":1}
,"auto":{"lookup":1}
,"lookup":{"option":1}
,"option":{"selected":1}
,"selected":{"preference":1}
,"specified":{"epic":1,"closes":1}
,"epic":{"assumes":1}
,"assumes":{"preference":1}
,"filename":{"(but":1}
,"(but":{"different":1}
,"different":{"extension)":1}
,"extension)":{"design":1}
,"architecture":{"list":1,"device":1,"package":1}
,"list":{"select":1}
,"specific":{"device":1}
,"family":{"within":1}
,"within":{"architecture":1}
,"package":{"list":1,"technology":1}
,"technology":{"performance":1}
,"performance":{"select":1,"grade":1}
,"grade":{"button":1}
,"applies":{"given":1}
,"given":{"options":1}
,"options":{"current":1,"may":1}
,"current":{"design":1}
,"closes":{"dialog":1}
,"cancel":{"button":1}
,"ignores":{"options":1}
,"may":{"specified":1}
,"help":{"button":1,"topic":1}
,"opens":{"online":1}
,"online":{"help":1}
,"topic":{"dialog":1}
,"creating":{"new":1}
,"designs":{"macros":1}
}
;Search.control.loadWordPairs(pairs);
