var pairs =
{
"searching":{"objects":1}
,"objects":{"find":1,"schematic":1,"design":1}
,"find":{"dialog":1,"objects":1,"click":1,"button":1,"text":1,"type":1,"next":1,"pre":1}
,"dialog":{"box":1}
,"box":{"enables":1,"appears":1,"wild":1}
,"enables":{"locate":1}
,"locate":{"select":1,"first":1,"instances":1}
,"select":{"objects":1,"object":1,"site":1,"match":1,"click":1}
,"schematic":{"layout":1}
,"layout":{"find":1}
,"design":{"choose":1}
,"choose":{"edit":1}
,"edit":{"find":1,"perhaps":1}
,"click":{"find":1,"select":1,"close":1,"object":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"find":1}
,"appears":{"type":1,"select":1}
,"type":{"object":1,"find":1,"drop-down":1}
,"object":{"name":1,"type":1,"object":1,"highlighted":1,"want":1,"editing":1}
,"name":{"find":1,"select":1,"match":1}
,"text":{"box":1}
,"wild":{"cards":1}
,"cards":{"object":1}
,"drop-down":{"list":1}
,"list":{"select":1,"appears":1}
,"site":{"select":1,"type":1}
,"match":{"whole":1,"case":1,"upper":1}
,"whole":{"word":1}
,"word":{"match":1}
,"case":{"desired":1,"letters":1}
,"desired":{"narrow":1}
,"narrow":{"search":1}
,"search":{"complete":1}
,"complete":{"name":1}
,"upper":{"lower":1}
,"lower":{"case":1}
,"letters":{"click":1}
,"next":{"locate":1,"find":1}
,"first":{"instance":1}
,"instance":{"object":1,"highlighted":1}
,"highlighted":{"red":1}
,"red":{"main":1,"located":1}
,"main":{"view":1}
,"view":{"find":1,"highlight":1,"shows":1}
,"pre":{"buttons":1}
,"buttons":{"locate":1}
,"instances":{"main":1,"click":1}
,"highlight":{"instances":1}
,"close":{"main":1}
,"shows":{"last":1}
,"last":{"found":1}
,"found":{"instance":1}
,"located":{"object":1}
,"want":{"edit":1}
,"perhaps":{"back":1}
,"back":{"later":1}
,"later":{"sure":1}
,"sure":{"click":1}
,"editing":{"area":1,"record":1}
,"area":{"available":1}
,"available":{"editing":1}
,"record":{"location":1}
,"location":{"tcl":1}
,"tcl":{"console":1}
,"console":{"hyperlink":1}
}
;Search.control.loadWordPairs(pairs);
