var pairs =
{
"determining":{"reference":1}
,"reference":{"components":1,"component":1}
,"components":{"determine":1,"unrouted":1,"(macro":1}
,"determine":{"component":1}
,"component":{"reference":1,"select":1,"appears":1,"possible":1,"individually":1}
,"select":{"design":1}
,"design":{"macro":1}
,"macro":{"refcomp":1,"unplaced":1,"component":1,"terminology":1}
,"refcomp":{"name":1}
,"name":{"reference":1}
,"appears":{"tcl":1}
,"tcl":{"console":1}
,"console":{"note":1}
,"note":{"possible":1}
,"possible":{"define":1,"place":1}
,"define":{"macro":1}
,"unplaced":{"components":1}
,"unrouted":{"nets":1}
,"nets":{"case":1}
,"case":{"reference":1}
,"place":{"instance":1}
,"instance":{"library":1}
,"library":{"file":1}
,"file":{"except":1}
,"except":{"placing":1}
,"placing":{"macro":1}
,"individually":{"macro":1}
,"terminology":{"defining":1}
,"defining":{"reference":1}
,"(macro":{"mode)":1}
}
;Search.control.loadWordPairs(pairs);
