var pairs =
{
"cloning":{"components":1}
,"components":{"clone":1,"programmable":1}
,"clone":{"component":1,"source":1,"logical":1}
,"component":{"duplicate":1,"target":1,"programming":1,"copied":1,"source":1,"created":1,"select":1,"want":1,"holding":1,"site":1,"choose":1}
,"duplicate":{"logical":1}
,"logical":{"contents":1}
,"contents":{"pic":1,"source":1}
,"pic":{"pfu":1}
,"pfu":{"(the":1}
,"(the":{"source)":1,"target)":1}
,"source)":{"pic":1}
,"target)":{"components":1}
,"programmable":{"source":1}
,"source":{"placed":1,"component":1,"process":1,"component\u0027s":1}
,"placed":{"unplaced":1,"component":1}
,"unplaced":{"component":1}
,"target":{"vacant":1,"type":1,"site":1,"placed":1,"component":1}
,"vacant":{"site":1}
,"site":{"placed":1,"programmed":1,"want":1}
,"programming":{"component":1,"overwritten":1}
,"copied":{"connections":1,"target":1}
,"connections":{"copied":1}
,"type":{"component":1}
,"programmed":{"copy":1}
,"copy":{"source":1}
,"process":{"new":1}
,"new":{"component":1}
,"created":{"target":1}
,"overwritten":{"source":1}
,"component\u0027s":{"logic":1}
,"logic":{"clone":1,"target":1}
,"select":{"component":1}
,"want":{"clone":1,"copy":1}
,"holding":{"ctrl":1}
,"ctrl":{"key":1}
,"key":{"select":1}
,"choose":{"edit":1}
,"edit":{"clone":1}
}
;Search.control.loadWordPairs(pairs);
