var pairs =
{
"deleting":{"macros":1}
,"macros":{"design":1,"objects":1,"want":1,"eliminated":1}
,"design":{"mode":1}
,"mode":{"delete":1}
,"delete":{"macro":1,"macros":1,"choose":1,"click":1,"button":1}
,"macro":{"macro\u0027s":1,"eliminated":1,"name":1,"names":1}
,"macro\u0027s":{"external":1}
,"external":{"pins":1}
,"pins":{"unrouted":1}
,"unrouted":{"components":1}
,"components":{"nets":1}
,"nets":{"part":1}
,"part":{"macro":1}
,"eliminated":{"macro":1,"database":1}
,"name":{"removed":1}
,"removed":{"database":1}
,"database":{"delete":1}
,"objects":{"dialog":1}
,"dialog":{"box":1}
,"box":{"display":1}
,"display":{"list":1}
,"list":{"macro":1}
,"names":{"select":1}
,"select":{"macros":1}
,"want":{"delete":1}
,"choose":{"edit":1}
,"edit":{"delete":1}
,"click":{"delete":1}
,"button":{"actions":1}
,"actions":{"panel":1}
,"panel":{"macros":1}
}
;Search.control.loadWordPairs(pairs);
