var pairs =
{
"listing":{"external":1}
,"external":{"pins":1,"pin":1}
,"pins":{"macro":1,"choose":1,"list":1,"currently":1,"output":1,"$extpin_0":1}
,"macro":{"mode":1,"list":1,"appears":1}
,"mode":{"list":1}
,"list":{"currently":1,"pins":1,"external":1}
,"currently":{"defined":1}
,"defined":{"external":1,"macro":1}
,"choose":{"design":1}
,"design":{"macro":1}
,"appears":{"tcl":1}
,"tcl":{"console":1}
,"console":{"shown":1}
,"shown":{"following":1}
,"following":{"example":1}
,"example":{"extpins":1}
,"extpins":{"external":1}
,"pin":{"name":1,"type":1,"summary":1,"count":1}
,"name":{"pin":1}
,"type":{"comp.pin":1}
,"comp.pin":{"location":1}
,"location":{"----------------------------------------------\u00A0":1}
,"----------------------------------------------\u00A0":{"input":1}
,"input":{"pins":1}
,"output":{"pins":1}
,"$extpin_0":{"syncoutput":1}
,"syncoutput":{"$comp_0.q5":1}
,"$comp_0.q5":{"external":1}
,"summary":{"number":1}
,"number":{"inputs":1,"outputs":1}
,"inputs":{"number":1}
,"outputs":{"total":1}
,"total":{"pin":1}
}
;Search.control.loadWordPairs(pairs);
