var pairs =
{
"site":{"attributes":1,"selected":1,"name":1,"preference":1,"prohibit":1,"future":1}
,"attributes":{"dialog":1}
,"dialog":{"box":1}
,"box":{"site":1,"feature":1,"cancel":1,"apply":1,"help":1}
,"selected":{"clicking":1,"applies":1}
,"clicking":{"attribute":1}
,"attribute":{"button":1,"open":1}
,"button":{"actions":1,"applies":1,"ignores":1}
,"actions":{"panel":1}
,"panel":{"choosing":1}
,"choosing":{"design":1}
,"design":{"attribute":1}
,"open":{"dialog":1}
,"feature":{"description":1}
,"description":{"name":1}
,"name":{"displays":1,"prohibit":1}
,"displays":{"site":1}
,"prohibit":{"selected":1,"site":1,"preference":1}
,"applies":{"prohibit":1,"option":1,"given":1}
,"preference":{"prevents":1,"reserve":1}
,"prevents":{"placement":1}
,"placement":{"component":1}
,"component":{"site":1}
,"reserve":{"site":1}
,"future":{"button":1}
,"option":{"closes":1,"may":1,"without":1}
,"closes":{"dialog":1}
,"cancel":{"button":1}
,"ignores":{"option":1}
,"may":{"specified":1}
,"specified":{"closes":1}
,"apply":{"button":1}
,"given":{"option":1}
,"without":{"closing":1}
,"closing":{"dialog":1}
,"help":{"opens":1,"topic":1}
,"opens":{"online":1}
,"online":{"help":1}
,"topic":{"dialog":1}
}
;Search.control.loadWordPairs(pairs);
