var pairs =
{
"logic":{"block":1,"selected":1,"editing":1,"changing":1}
,"block":{"view":1,"logic":1,"toolbar":1,"shows":1,"ram":1}
,"view":{"component":1,"using":1,"either":1,"(for":1,"editable":1,"logic":1,"dim":1,"clear":1,"attributes":1,"back":1,"returns":1}
,"component":{"selected":1,"open":1,"(for":1,"edit\u002Fstop":1,"logic":1,"posting":1,"configuration":1}
,"selected":{"open":1,"component":1}
,"open":{"logic":1,"block":1}
,"using":{"following":1}
,"following":{"methods":1}
,"methods":{"click":1}
,"click":{"editblock":1,"edit":1}
,"editblock":{"button":1,"press":1}
,"button":{"actions":1,"logic":1,"opens":1,"performs":1,"resets":1}
,"actions":{"toolbar":1}
,"toolbar":{"choose":1,"view":1}
,"choose":{"edit":1}
,"edit":{"editblock":1,"button":1,"toggles":1}
,"press":{"ctrl":1}
,"ctrl":{"double-click":1}
,"double-click":{"component":1}
,"either":{"schematic":1}
,"schematic":{"representation":1,"diagram":1}
,"representation":{"interior":1}
,"interior":{"selected":1}
,"(for":{"components":1}
,"components":{"slice":1,"ebr":1,"attributes":1,"topic":1}
,"slice":{"pio)":1}
,"pio)":{"tabular":1}
,"tabular":{"view":1}
,"ebr":{"pll":1}
,"pll":{"dsp":1,"configuration":1}
,"dsp":{"serdes)":1,"configuration":1}
,"serdes)":{"click":1}
,"editable":{"feature":1,"view":1}
,"feature":{"description":1}
,"description":{"logic":1}
,"shows":{"schematic":1}
,"diagram":{"tabular":1}
,"edit\u002Fstop":{"edit":1}
,"toggles":{"logic":1}
,"dim":{"uneditable":1}
,"uneditable":{"view":1}
,"clear":{"editable":1}
,"attributes":{"button":1,"dialog":1}
,"opens":{"components":1,"equations":1}
,"dialog":{"box":1}
,"box":{"equation":1,"component":1}
,"equation":{"button":1}
,"equations":{"dialog":1}
,"editing":{"drc":1,"components":1,"component":1,"pfu":1,"block":1}
,"drc":{"button":1}
,"performs":{"design":1}
,"design":{"rule":1}
,"rule":{"check":1}
,"check":{"current":1}
,"current":{"configuration":1}
,"configuration":{"component":1,"state":1,"changing":1}
,"posting":{"errors":1}
,"errors":{"warnings":1}
,"warnings":{"epic":1}
,"epic":{"tcl":1,"main":1}
,"tcl":{"console":1}
,"console":{"restore":1}
,"restore":{"button":1}
,"resets":{"component":1}
,"state":{"opened":1}
,"opened":{"logic":1}
,"back":{"minimizes":1}
,"minimizes":{"logic":1}
,"returns":{"epic":1}
,"main":{"window":1}
,"window":{"general":1}
,"general":{"information":1}
,"information":{"editing":1}
,"topic":{"editing":1}
,"pfu":{"logic":1}
,"changing":{"i\u002Fo":1,"pll":1,"dsp":1,"serdes":1}
,"i\u002Fo":{"types":1}
,"types":{"editing":1}
,"ram":{"contents":1}
,"contents":{"changing":1}
,"serdes":{"configuration":1}
}
;Search.control.loadWordPairs(pairs);
