var pairs =
{
"editing":{"component":1,"area":1,"click":1}
,"component":{"logic":1,"internal":1,"(for":1,"configuration":1,"edit":1,"following":1,"editing":1,"schematic":1,"design":1,"click":1}
,"logic":{"logic":1,"block":1,"configuration":1,"view":1}
,"block":{"view":1,"click":1,"views":1}
,"view":{"provides":1,"epic":1,"(for":1,"modify":1,"select":1,"object":1,"logic":1,"opens":1,"displays":1,"component":1,"view":1,"read-only":1,"first":1,"toolbar":1,"schematic":1,"returns":1,"dimmed":1,"using":1,"remains":1}
,"provides":{"interactive":1}
,"interactive":{"change":1}
,"change":{"component":1,"click":1}
,"internal":{"logic":1}
,"configuration":{"open":1,"run":1}
,"open":{"logic":1,"enable":1,"return":1}
,"epic":{"displays":1,"click":1}
,"displays":{"either":1,"logic":1}
,"either":{"window":1}
,"window":{"schematic":1,"opened":1}
,"schematic":{"representation":1,"tabular":1,"click":1}
,"representation":{"interior":1}
,"interior":{"selected":1}
,"selected":{"component":1}
,"(for":{"components":1,"ebr":1}
,"components":{"slice":1}
,"slice":{"pio":1,"component":1}
,"pio":{"elements)":1,"slice":1}
,"elements)":{"tabular":1}
,"tabular":{"view":1}
,"ebr":{"pll":1}
,"pll":{"dsp":1}
,"dsp":{"serdes)":1}
,"serdes)":{"work":1}
,"work":{"within":1}
,"within":{"logic":1}
,"modify":{"component":1}
,"run":{"logic":1,"design":1}
,"select":{"component":1}
,"edit":{"editing":1,"edit":1,"block":1,"button":1}
,"area":{"main":1}
,"main":{"view":1}
,"object":{"menu":1}
,"menu":{"click":1,"logic":1}
,"click":{"zoom":1,"editblock":1,"edit":1,"attributes":1,"drc":1,"stop":1,"back":1}
,"zoom":{"button":1}
,"button":{"toolbar":1,"actions":1,"logic":1,"return":1}
,"toolbar":{"enlarge":1,"view":1,"examine":1,"run":1}
,"enlarge":{"highlight":1}
,"highlight":{"component":1}
,"following":{"choose":1}
,"choose":{"edit":1}
,"editblock":{"button":1}
,"actions":{"panel":1}
,"panel":{"double-click":1}
,"double-click":{"component":1}
,"opens":{"separate":1}
,"separate":{"view":1}
,"read-only":{"dimmed":1,"view":1}
,"dimmed":{"view":1,"return":1}
,"first":{"open":1}
,"enable":{"editing":1}
,"attributes":{"button":1,"pio":1}
,"examine":{"attributes":1}
,"design":{"change":1,"rule":1}
,"drc":{"button":1,"results":1}
,"rule":{"check":1}
,"check":{"drc":1}
,"results":{"displayed":1}
,"displayed":{"tcl":1}
,"tcl":{"console":1}
,"console":{"finished":1}
,"finished":{"editing":1}
,"stop":{"edit":1}
,"returns":{"read-only":1}
,"return":{"main":1,"selecting":1}
,"back":{"button":1}
,"using":{"back":1}
,"remains":{"open":1}
,"selecting":{"window":1}
,"opened":{"block":1}
,"views":{"menu":1}
}
;Search.control.loadWordPairs(pairs);
