var pairs =
{
"getting":{"started":1}
,"started":{"epic":1}
,"epic":{"device":1,"running":1,"executable":1,"accessories":1,"shown":1,"session":1,"main":1,"tcl":1,"creating":1}
,"device":{"editor":1}
,"editor":{"stand-alone":1}
,"stand-alone":{"tool":1}
,"tool":{"launch":1}
,"launch":{"epic":1}
,"running":{"epic":1}
,"executable":{"shortcuts":1}
,"shortcuts":{"using":1}
,"using":{"start":1,"tcl":1}
,"start":{"menu":1,"new":1}
,"menu":{"open":1}
,"open":{"epic":1,"design":1}
,"accessories":{"folder":1}
,"folder":{"diamond":1}
,"diamond":{"installation":1}
,"installation":{"linux":1}
,"linux":{"command":1}
,"command":{"line":1,"prompt":1}
,"line":{"change":1}
,"change":{"desired":1}
,"desired":{"directory":1}
,"directory":{"open":1}
,"shown":{"following":1}
,"following":{"example":1}
,"example":{".\u002Fdiamond\u002F3.1_x64\u002Fbin\u002Flin64\u002F.\u002Fdiamond":1}
,".\u002Fdiamond\u002F3.1_x64\u002Fbin\u002Flin64\u002F.\u002Fdiamond":{"-epic":1}
,"-epic":{"start":1}
,"new":{"epic":1,"design":1,"designs":1}
,"session":{"epic":1}
,"main":{"window":1}
,"window":{"appears":1}
,"appears":{"design":1}
,"design":{"loaded":1,"macro":1}
,"loaded":{"file":1}
,"file":{"menu":1}
,"macro":{"create":1,"alternatively":1}
,"create":{"new":1}
,"alternatively":{"tcl":1}
,"tcl":{"command":1,"console":1,"commands":1}
,"prompt":{"beneath":1}
,"beneath":{"tcl":1}
,"console":{"load":1,"tab":1}
,"load":{"design":1}
,"commands":{"section":1,"available":1}
,"section":{"syntax":1}
,"syntax":{"descriptions":1}
,"descriptions":{"tcl":1}
,"available":{"epic":1}
,"creating":{"new":1}
,"designs":{"macros":1}
,"macros":{"opening":1,"using":1}
,"opening":{"designs":1}
,"tab":{"object":1}
,"object":{"definitions":1}
,"definitions":{"main":1}
}
;Search.control.loadWordPairs(pairs);
