var pairs =
{
"panning":{"main":1}
,"main":{"view":1}
,"view":{"several":1,"zooming":1,"indicator":1,"pan":1,"press":1,"scroll":1,"keys":1,"click":1}
,"several":{"ways":1}
,"ways":{"move":1}
,"move":{"around":1,"view":1}
,"around":{"main":1}
,"zooming":{"mouse":1}
,"mouse":{"wheel":1,"button":1}
,"wheel":{"arrow":1,"click":1,"drag":1}
,"arrow":{"keys":1,"key":1}
,"keys":{"keys":1,"space":1,"click":1,"pan":1}
,"space":{"bar":1}
,"bar":{"move":1,"click":1,"once":1,"rapidly":1}
,"indicator":{"box":1}
,"box":{"inside":1,"highlighted":1}
,"inside":{"world":1,"main":1,"view":1}
,"world":{"view":1}
,"pan":{"using":1,"horizontally":1,"vertically":1,"pan":1}
,"using":{"mouse":1,"arrow":1,"appropriate":1,"keys":1,"space":1,"world":1}
,"click":{"once":1,"inside":1}
,"once":{"inside":1,"repeatedly":1}
,"press":{"hold":1,"space":1}
,"hold":{"mouse":1,"space":1,"left":1}
,"drag":{"layout":1,"square":1}
,"layout":{"desired":1}
,"desired":{"direction":1}
,"direction":{"pan":1}
,"scroll":{"left":1}
,"left":{"right":1,"mouse":1}
,"right":{"down":1}
,"down":{"using":1}
,"appropriate":{"arrow":1}
,"key":{"pan":1}
,"horizontally":{"keys":1}
,"vertically":{"pan":1}
,"repeatedly":{"shift":1}
,"shift":{"display":1}
,"display":{"incrementally":1}
,"incrementally":{"hold":1}
,"rapidly":{"pan":1}
,"highlighted":{"square":1}
,"square":{"inside":1,"desired":1}
,"button":{"drag":1}
}
;Search.control.loadWordPairs(pairs);
