var pairs =
{
"moving":{"macro":1}
,"macro":{"design":1,"placed":1,"placing":1,"unused":1,"want":1,"move":1,"nets":1}
,"design":{"mode":1}
,"mode":{"move":1}
,"move":{"macro":1,"select":1,"macro\u0027s":1,"maintain":1}
,"placed":{"components":1,"macro":1}
,"components":{"unused":1,"macro":1}
,"unused":{"group":1,"site":1}
,"group":{"sites":1}
,"sites":{"swap":1,"select":1}
,"swap":{"command":1,"reference":1}
,"command":{"quicker":1}
,"quicker":{"unplacing":1}
,"unplacing":{"macro":1}
,"placing":{"new":1}
,"new":{"location":1}
,"location":{"move":1}
,"select":{"macro":1,"vacant":1}
,"want":{"move":1}
,"vacant":{"site":1}
,"site":{"want":1,"type":1,"components":1}
,"macro\u0027s":{"reference":1,"external":1}
,"reference":{"component":1}
,"component":{"reference":1,"selected":1,"moves":1,"macro\u0027s":1}
,"selected":{"site":1}
,"type":{"block":1}
,"block":{"i\u002Fo":1,"logic":1,"choose":1}
,"i\u002Fo":{"block":1}
,"logic":{"block":1}
,"choose":{"edit":1}
,"edit":{"swap":1}
,"moves":{"unused":1}
,"maintain":{"positions":1}
,"positions":{"relative":1}
,"relative":{"reference":1}
,"external":{"pins":1}
,"pins":{"routed":1}
,"routed":{"macro":1}
,"nets":{"pre-routed":1}
,"pre-routed":{"automatically":1}
,"automatically":{"routed":1}
}
;Search.control.loadWordPairs(pairs);
